In [1]:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="2,3"

%load_ext autoreload
%autoreload 2

In [2]:
import ipdb
from Data import *
from address import *
from modelGen import *
from utils import cf_eval, cleanup_gpu
from models import CausalCondLatentCF, latentCFpp, PrototypeLatentCF
from models import CondLatentCF # Note: get the vanilla CondLatentCF
import numpy as np
import random 
from tensorflow import random as tf_random
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from itertools import product
import argparse
import os
import pandas as pd

In [3]:
SEED = 23

os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf_random.set_seed(SEED)


CF_METHODS = {  
    "LatentCFpp": latentCFpp,
    "Prototype": PrototypeLatentCF,
    "CausalCACTUS": CausalCondLatentCF,
    "CACTUS": CondLatentCF
}

In [4]:
# Experimentos que a realizar
EXP = [
    {
        "name": "LatentCF++",
        "data": "GIVECREDIT",
        "classifier": "./exp/GIVECREDIT_class/config.json",
        "AE": "./exp/GIVECREDIT_AE/config.json",
        "CFmethod": "LatentCFpp",
        "context": [
            "ageAbove50",
            "Dependents"
        ],
        "epochs": 100,
        "tol": 0.001,
        "target_prob": 0.5,
        "learning_rate": 0.1
    },
    {
        "name": "Prototype C",
        "data": "GIVECREDIT",
        "classifier": "./exp/GIVECREDIT_class/config.json",
        "AE": "./exp/GIVECREDIT_AE/config.json",
        "CFmethod": "Prototype",
        "context": [
            "ageAbove50",
            "Dependents"
        ],
        "epochs": 100,
        "kappa": 0.0,
        "c": 1.0,
        "c_steps": 1,
        "beta": 0.1,
        "gamma": 0.0,
        "theta": 100.0,
        "clip": [
            -1000,
            1000
        ],
        "feat_range": [
            -4,
            4
        ],
        "lr": 0.01
    },
    {
        "name": "Prototype D",
        "data": "GIVECREDIT",
        "classifier": "./exp/GIVECREDIT_class/config.json",
        "AE": "./exp/GIVECREDIT_AE/config.json",
        "CFmethod": "Prototype",
        "context": [
            "ageAbove50",
            "Dependents"
        ],
        "epochs": 100,
        "kappa": 0.0,
        "c": 1.0,
        "c_steps": 1,
        "beta": 0.1,
        "gamma": 100.0,
        "theta": 100.0,
        "clip": [
            -1000,
            1000
        ],
        "feat_range": [
            -4,
            4
        ],
        "lr": 0.01
    },
    {
        "name": "CACTUS",
        "data": "GIVECREDIT",
        "classifier": "./exp/GIVECREDIT_class/config.json",
        "AE": "./exp/GIVECREDIT_CACTUS/config.json",
        "CFmethod": "CACTUS",
        "context": [
            "ageAbove50",
            "Dependents"
        ],
        "epochs": 300,
        "target_prob": 0.5,
        # "learning_rate": 0.005,
        "learning_rate": 0.01,
        "power": 0.5,
        "alpha": 0.7,
        "gamma": 0.1,
        "beta": 0.01,
        # "dynamicAlpha": True
        "dynamicAlpha": False
    },
    {
        "name": "CausalCACTUS",
        "data": "GIVECREDIT",
        "classifier": "./exp/GIVECREDIT_class/config.json",
        "AE": "./exp/GIVECREDIT_CACTUS/config.json",
        "CFmethod": "CausalCACTUS",
        "context": [
            "ageAbove50",
            "Dependents"
        ],
        "epochs": 300,
        "target_prob": 0.5,
        # "learning_rate": 0.005,
        "learning_rate": 0.01,
        "power": 0.5,
        "alpha": 0.7,
        "gamma": 0.1,
        "beta": 0.01,
        "dynamicAlpha": True
        # "dynamicAlpha": False
    }
]

In [5]:
import re
from collections import defaultdict
# TODO: make a function to convert the causal paths for all the test samples
def build_causal_index_map(input_features, graph_str):
    """
    Returns:
        child_to_parents: dict {child_idx: [parent_idx, ...]}
        parent_to_children: dict {parent_idx: [child_idx, ...]}
        feat2idx: dict {feature_name: index}
    """

    # Feature name to index
    feat2idx = {f: i for i, f in enumerate(input_features)}

    # Extract edges using regex
    edges = re.findall(r'(\w+)\s*->\s*(\w+)', graph_str)

    child_to_parents = defaultdict(list)
    parent_to_children = defaultdict(list)

    for parent, child in edges:

        if parent not in feat2idx or child not in feat2idx:
            raise ValueError(f"Feature in graph not found in dataset: {parent} or {child}")

        p_idx = feat2idx[parent]
        c_idx = feat2idx[child]

        child_to_parents[c_idx].append(p_idx)
        parent_to_children[p_idx].append(c_idx)

    return dict(child_to_parents), dict(parent_to_children), feat2idx

# credit_rex5_constraints_min.dot from downsampled
graph_str1 = """
strict digraph {
NumberRealEstateLoansOrLines;
NumberOfTimes90DaysLate;
NumberOfDependents;
age;
DebtRatio;
NumberOfTime3059DaysPastDueNotWorse;
NumberOfOpenCreditLinesAndLoans;
RevolvingUtilizationOfUnsecuredLines;
MonthlyIncome;
NumberOfTime6089DaysPastDueNotWorse;
NumberOfTimes90DaysLate -> NumberOfOpenCreditLinesAndLoans;
NumberOfTimes90DaysLate -> NumberRealEstateLoansOrLines;
NumberOfTimes90DaysLate -> RevolvingUtilizationOfUnsecuredLines;
NumberOfTimes90DaysLate -> MonthlyIncome;
NumberOfTime3059DaysPastDueNotWorse -> NumberOfOpenCreditLinesAndLoans;
NumberOfTime3059DaysPastDueNotWorse -> NumberRealEstateLoansOrLines;
NumberOfTime3059DaysPastDueNotWorse -> MonthlyIncome;
NumberOfOpenCreditLinesAndLoans -> DebtRatio;
RevolvingUtilizationOfUnsecuredLines -> NumberOfOpenCreditLinesAndLoans;
MonthlyIncome -> NumberOfOpenCreditLinesAndLoans;
}
"""

# credit_rex6_constraints_mod.dot from downsampled
graph_str2 = """ 
strict digraph {
NumberRealEstateLoansOrLines;
NumberOfTimes90DaysLate;
NumberOfDependents;
age;
DebtRatio;
NumberOfTime3059DaysPastDueNotWorse;
NumberOfOpenCreditLinesAndLoans;
RevolvingUtilizationOfUnsecuredLines;
MonthlyIncome;
NumberOfTime6089DaysPastDueNotWorse;
NumberRealEstateLoansOrLines -> DebtRatio;
NumberOfOpenCreditLinesAndLoans -> DebtRatio;
RevolvingUtilizationOfUnsecuredLines -> NumberOfOpenCreditLinesAndLoans;
MonthlyIncome -> NumberOfOpenCreditLinesAndLoans;
}
"""

In [6]:
# # CF generation
# child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
#     data.features_lbls,
#     # graph_str
#     graph_str1
# )
# print("Feature → index:")
# print(feat2idx)
# print("\nChild → Parents (index form):")
# print(child_to_parents_dict)

## Graph 1 (Minimum priors)

In [7]:
N = 50 
N_BOOTSTRAP = 5
# SEED_list = [23] * N_BOOTSTRAP
SEED_list = [12, 23, 34, 45, 56]

# Number of samples to compute the metrics for CF evaluation
METRICS = []

for i, exp in enumerate(EXP):
    print("\n" * 2)
    print("*" * 200)
    print(f"Running exp: {exp['name']} ({i}/{len(EXP)})")
    print("*" * 200)
    print("\n" * 2)
    
    # Reading the data
    CLASS_CONFIG_PATH = exp["classifier"]
    AE_CONFIG_PATH = exp["AE"]

    class_config = get_exp_config(CLASS_CONFIG_PATH)
    print("Reading data")
    data = getData(class_config)

    # Getting classifier
    classifier = modelGen(class_config["type"], data, params=class_config, debug=True)
    classifier.load()

    # Getting AE-based Model
    AE_config = get_exp_config(AE_CONFIG_PATH)
    aeModel = modelGen(AE_config["type"], data, params=AE_config, debug=True)
    aeModel.load()

    # CF generation
    child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
        data.features_lbls,
        # TODO: change the string below for graph_str1 and graph_str2
        graph_str1
    )
    print("Feature → index:")
    print(feat2idx)
    print("\nChild → Parents (index form):")
    print(child_to_parents_dict)
    
    if exp["name"] == "CausalCACTUS":
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train,
            x_min=data.X_train.min(axis=0),
            x_max=data.X_train.max(axis=0),
            causal_index_map=child_to_parents_dict
        )
    else:
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train
        )

    for trial in range(N_BOOTSTRAP):

        # --- Sampling test data ---
        SEED = SEED_list[trial]
        os.environ['PYTHONHASHSEED'] = str(SEED)
        random.seed(SEED)
        np.random.seed(SEED)
        tf_random.set_seed(SEED)
        rand_idx = np.random.choice(len(data.X_test), N, replace=True)
        
        # previous name: x
        X_test = data.X_test[rand_idx, ...]
        # previous name: contest
        context_test = data.context_test[exp['context']].values
        context_test = context_test[rand_idx, ...]

        context_training = data.context_train[exp['context']].values

        # previous name: y
        y_test = np.argmax(data.y_test[rand_idx, ...], axis=1)
        y_original_logits = classifier.predict(X_test)
        # previous name: y_
        y_original_labels = np.argmax(y_original_logits, axis=1)

        # --- CF generation ---
        # previous names: 
        # cf_x, cf_y_, x, __
        X_cf, y_cf_labels, X_internal, y_internal = CF_method.transform(
            X_test,
            y_original_labels,
            target_context=context_test,
            verbose=0
        )              
      
        # --- CF evaluation ---
        cf_scores, cf_scores_labels = cf_eval(
            data.X_train, # previous name: data.X_train
            context_training, # previous name: context_training,
            X_test, # previous name: x,
            X_cf, # previous name: cf_x, 
            y_original_labels, # previous name: y_,
            context_test, # previous name: context,
            y_cf_labels, # previous name: cf_y_
            data.scaler_inverse_transform(X_test),
            data.scaler_inverse_transform(X_cf),
            child_to_parents_dict
        )

        for i_metric, label in enumerate(cf_scores_labels):
            METRICS.append([
                exp["name"],
                exp["data"],
                exp["CFmethod"],
                label,
                cf_scores[i_metric]
            ])

    # Cleaning GPU models
    cleanup_gpu()

# --- Metrics aggregation ---
df_metrics = pd.DataFrame(
    data=METRICS,
    columns=["Model", "Dataset", "CFMethod", "Metric", "Value"]
)
df_metrics = df_metrics.round(3)
print(df_metrics)

********************************************************************************************************************************************************************************************************
Running exp: LatentCF++ (0/5)
********************************************************************************************************************************************************************************************************



Reading data




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Class Good Standing: 8334.0 samples
Class Default Risk: 8334.0 samples
Age above 50 att: 7061
Dependents more than one: 8256
----------------------------------------------------------------------------------------------------




Building model

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 dense (Dense)               (None, 64)                576

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,330
Trainable params: 34,562
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: GIVECREDIT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 model_1 (Functional)        (None, 16)                4656

 model_2 (Functional)        (None, 8)                 4648

=================================================================
Total params: 9,304
Trainable params: 9,304
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: GIVECREDIT_AE
Feature → index:
{'RevolvingUtilizationOfUnsecuredLines': 0, 'NumberOfTime3059DaysPastDueNotWorse': 1, 'DebtRatio': 2, 'MonthlyIncome': 3, 'NumberOfOpenCreditLinesAndLoans': 4, 'NumberOfTimes90DaysLate': 5, 'NumberRealEstateLoansOrLines': 6, 'NumberOfTime6089DaysPastDueNotWorse': 7}

Child → Parents (index form):
{4: [5, 1, 0, 3], 6: [5, 1], 0: [5], 3: [5, 1], 2: [4]}
Building model: latentCF [CF]
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 16)]              0

 model_2 (Functional)        (None, 8)                 4648

 model (Functional)          (None, 2)                 35330

=================================================================
Total params: 39,978
Trainable params: 39,210
Non-trainable params: 768
_________________________________________________________________
2/2 [==============================] - 1s 4ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 0 0 1 1 0 1 0 1 1 0
 1 0 1 0 1 0 0 0 1 0 1 1 0]
[0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 0 0 1 1 0 1 0 1 1 0
 1 0 1 0 1 0 0 0 1 0 1 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3252
Unique rows: 3228
After np.unique(): subset size: 3228

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

cf_samples_ shape: (19, 8)
X_ shape: (3228, 8)
lof_cf min/max: 1.0063414449814274 3.851773233463057
lof_train min/max: 0.9458280111225811 3.915395328227212
mean train LOF: 1.1417417999834432
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4447
Unique rows: 4431
After np.unique(): subset size: 4431
cf_samples_ shape: (11, 8)
X_ shape: (4431, 8)
lof_cf min/max: 0.9809950727661462 1.8884468672033021
lof_train min/max: 0.950888749716979 5.916160610353198
mean train LOF: 1.1399486438743094
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3530
Unique rows: 3518
After np.unique(): subset size: 3518
cf_samples_ shape: (10, 8)
X_ shape: (3518, 8)
lof_cf min/max: 1.0303032425564975 2.8047318991276895
lof_train min/max: 0.9494824814405077 47.345807648851135
mean train LOF: 1.1799951612379043
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2143
Unique rows: 2138
After np.unique(): subset size: 2138
cf_samples_ shape: (10, 8)
X_ shape: (2138, 8)
lof_cf min/max: 1.0113857090618494 2.26549949264985
lof_train min/max: 0.9441404779506231 12.281328646845447
mean train LOF: 1.1510846258883465
0.9809950727661462 1.2937864383407374 3.851773233463057 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 1 0 1 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1
 1 1 1 1 0 0 0 0 1 0 0 1 1]
[1 1 0 1 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1
 1 1 1 1 0 0 0 0 1 0 0 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3252
Unique rows: 3228

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

After np.unique(): subset size: 3228
cf_samples_ shape: (14, 8)
X_ shape: (3228, 8)
lof_cf min/max: 1.0061817398964585 1.6585761618527852
lof_train min/max: 0.9458280111225811 3.915395328227212
mean train LOF: 1.1417417999834432
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4447
Unique rows: 4431
After np.unique(): subset size: 4431
cf_samples_ shape: (17, 8)
X_ shape: (4431, 8)
lof_cf min/max: 0.9861963674700238 1.9766495910889341
lof_train min/max: 0.950888749716979 5.916160610353198
mean train LOF: 1.1399486438743094
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3530
Unique rows: 3518
After np.unique(): subset size: 3518
cf_samples_ shape: (14, 8)
X_ shape: (3518, 8)
lof_cf min/max: 1.0406227148343186 3.312569774848761
lof_train min/max: 0.9494824814405077 47.345807648851135
mean train LOF: 1.1799951612379043
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2143
Unique rows: 2138
After np.unique(): subset size: 2138
cf_samples_ shape: (5, 8)
X_ shape: (2138, 8)
lof_cf min/max: 1.0721226516161777 1.4975249966341644
lof_train min/max: 0.9441404779506231 12.281328646845447
mean train LOF: 1.1510846258883465
0.9861963674700238 1.211023022143678 3.312569774848761 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 1 0 1 0 1 0 1 1 0
 0 1 0 1 0 0 0 0 1 1 0 0 1]
[0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 1 0 1 0 1 0 1 1 0
 0 1 0 1 0 0 0 0 1 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3252
Unique rows: 3228
After np.unique(): subset size: 3228

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

cf_samples_ shape: (9, 8)
X_ shape: (3228, 8)
lof_cf min/max: 1.0686102008373388 2.5587066117900905
lof_train min/max: 0.9458280111225811 3.915395328227212
mean train LOF: 1.1417417999834432
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4447
Unique rows: 4431
After np.unique(): subset size: 4431
cf_samples_ shape: (18, 8)
X_ shape: (4431, 8)
lof_cf min/max: 0.9770362764942347 1.7057470318417869
lof_train min/max: 0.950888749716979 5.916160610353198
mean train LOF: 1.1399486438743094
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3530
Unique rows: 3518
After np.unique(): subset size: 3518
cf_samples_ shape: (16, 8)
X_ shape: (3518, 8)
lof_cf min/max: 0.9864258921867525 2.3273094937786505
lof_train min/max: 0.9494824814405077 47.345807648851135
mean train LOF: 1.1799951612379043
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2143
Unique rows: 2138
After np.unique(): subset size: 2138
cf_samples_ shape: (7, 8)
X_ shape: (2138, 8)
lof_cf min/max: 1.004237473374062 1.4701124698054326
lof_train min/max: 0.9441404779506231 12.281328646845447
mean train LOF: 1.1510846258883465
0.9770362764942347 1.255844256238795 2.5587066117900905 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 1 1 0 0 1 1 0 0 1 0 0 1 1 0 0 1 1 0 0
 1 1 0 0 1 1 1 0 1 0 1 1 1]
[1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 1 1 0 0 1 1 0 0 1 0 0 1 1 0 0 1 1 0 0
 1 1 0 0 1 1 1 0 1 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3252
Unique rows: 3228
After np.unique(): subset size: 3228

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

cf_samples_ shape: (8, 8)
X_ shape: (3228, 8)
lof_cf min/max: 1.0673342464821725 2.695055662483659
lof_train min/max: 0.9458280111225811 3.915395328227212
mean train LOF: 1.1417417999834432
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4447
Unique rows: 4431
After np.unique(): subset size: 4431
cf_samples_ shape: (14, 8)
X_ shape: (4431, 8)
lof_cf min/max: 1.0163558481372752 2.2905458874770166
lof_train min/max: 0.950888749716979 5.916160610353198
mean train LOF: 1.1399486438743094
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3530
Unique rows: 3518
After np.unique(): subset size: 3518
cf_samples_ shape: (20, 8)
X_ shape: (3518, 8)
lof_cf min/max: 1.0580434746632459 2.1729422422964153
lof_train min/max: 0.9494824814405077 47.345807648851135
mean train LOF: 1.1799951612379043
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2143
Unique rows: 2138
After np.unique(): subset size: 2138
cf_samples_ shape: (8, 8)
X_ shape: (2138, 8)
lof_cf min/max: 0.9909096186695429 1.6489512825233568
lof_train min/max: 0.9441404779506231 12.281328646845447
mean train LOF: 1.1510846258883465
0.9909096186695429 1.241183010929307 2.695055662483659 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 0 1 1 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0
 1 1 1 0 1 0 0 0 0 0 1 1 1]
[0 0 0 1 1 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0
 1 1 1 0 1 0 0 0 0 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3252
Unique rows: 3228
After np.unique(): subset size: 3228

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

cf_samples_ shape: (12, 8)
X_ shape: (3228, 8)
lof_cf min/max: 1.0745101176501881 3.173143698796526
lof_train min/max: 0.9458280111225811 3.915395328227212
mean train LOF: 1.1417417999834432
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4447
Unique rows: 4431
After np.unique(): subset size: 4431
cf_samples_ shape: (20, 8)
X_ shape: (4431, 8)
lof_cf min/max: 0.9653535044803127 2.4992990348745296
lof_train min/max: 0.950888749716979 5.916160610353198
mean train LOF: 1.1399486438743094
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3530
Unique rows: 3518
After np.unique(): subset size: 3518
cf_samples_ shape: (9, 8)
X_ shape: (3518, 8)
lof_cf min/max: 1.0346029322900354 2.0094410486022447
lof_train min/max: 0.9494824814405077 47.345807648851135
mean train LOF: 1.1799951612379043
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2143
Unique rows: 2138
After np.unique(): subset size: 2138
cf_samples_ shape: (9, 8)
X_ shape: (2138, 8)
lof_cf min/max: 1.0266486741101908 3.5047828027470236
lof_train min/max: 0.9441404779506231 12.281328646845447
mean train LOF: 1.1510846258883465
0.9653535044803127 1.4314802209222224 3.5047828027470236 50



********************************************************************************************************************************************************************************************************
Running exp: Prototype C (1/5)
********************************************************************************************************************************************************************************************************



Reading data




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Class Good Standing: 8334.0 samples
Class Default Risk: 8334.0 samples
Age above 50 att: 7107
Dependents more than one: 8235
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 dense (Dense)               (None, 64)                576

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,330
Trainable params: 34,562
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: GIVECREDIT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 model_1 (Functional)        (None, 16)                4656

 model_2 (Functional)        (None, 8)                 4648

=================================================================
Total params: 9,304
Trainable params: 9,304
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: GIVECREDIT_AE
Feature → index:
{'RevolvingUtilizationOfUnsecuredLines': 0, 'NumberOfTime3059DaysPastDueNotWorse': 1, 'DebtRatio': 2, 'MonthlyIncome': 3, 'NumberOfOpenCreditLinesAndLoans': 4, 'NumberOfTimes90DaysLate': 5, 'NumberRealEstateLoansOrLines': 6, 'NumberOfTime6089DaysPastDueNotWorse': 7}

Child → Parents (index form):
{4: [5, 1, 0, 3], 6: [5, 1], 0: [5], 3: [5, 1], 2: [4]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
WARNING:tensorflow:AutoGraph could not transform <bound method PrototypeLatentCF._loss of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f6e39d8fdf0>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <bound method PrototypeLatentCF._loss of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f6e39d8fdf0>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 1 1]
[0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (15, 8)
X_ shape: (3216, 8)
lof_cf min/max: 1.318749802683931 3.7733460590467187
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (9, 8)
X_ shape: (4379, 8)
lof_cf min/max: 1.3674606000616087 4.047109046812269
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (17, 8)
X_ shape: (3553, 8)
lof_cf min/max: 0.9962275901003517 3.904422174033793
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.1468475351876315 3.7158630551055833
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9962275901003517 2.13038808220075 4.047109046812269 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 0 1 0 0 0 0 0 1 1]
[1 1 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 0 1 0 0 0 0 0 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (17, 8)
X_ shape: (3216, 8)
lof_cf min/max: 1.1843830920238438 4.925692164891308
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (14, 8)
X_ shape: (4379, 8)
lof_cf min/max: 1.0124792635579194 3.6000663921692677
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (10, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.014841230122865 2.8456865613165334
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.1249446215080625 3.2637026965939895
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
1.0124792635579194 1.6008957534176531 4.925692164891308 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0
 1 1 0 1 0 0 0 0 1 1 1 0 0]
[1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0
 1 1 0 1 0 0 0 0 1 1 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (12, 8)
X_ shape: (3216, 8)
lof_cf min/max: 1.042967260604802 3.6185613138250123
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (15, 8)
X_ shape: (4379, 8)
lof_cf min/max: 1.0932959011964565 3.643757824677737
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (14, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.2210796222567977 3.678734371908448
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.0730935547823877 3.2311628922711515
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
1.042967260604802 1.7104143995269794 3.678734371908448 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0
 1 1 0 1 1 1 1 0 1 1 1 1 1]
[1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0
 1 1 0 1 1 1 1 0 1 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (14, 8)
X_ shape: (3216, 8)
lof_cf min/max: 1.0560696202763735 4.293544437426989
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (17, 8)
X_ shape: (4379, 8)
lof_cf min/max: 1.2886962509730666 4.8897047193023155
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (12, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.168405840192667 2.8243251910091236
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (7, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.1927267961654413 3.989018742850442
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
1.0560696202763735 1.8262312170587838 4.8897047193023155 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 1 1 1 1 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1
 1 0 1 0 1 0 0 0 0 0 1 1 1]
[1 0 1 1 1 1 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1
 1 0 1 0 1 0 0 0 0 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (9, 8)
X_ shape: (3216, 8)
lof_cf min/max: 1.208483181554751 3.5264616943679385
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (18, 8)
X_ shape: (4379, 8)
lof_cf min/max: 1.2912118838858957 4.111050911274372
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (15, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.0302048747399588 3.661898411643387
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (8, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.2642324737646613 2.329161117911176
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
1.0302048747399588 1.7373181781485667 4.111050911274372 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype D (2/5)
********************************************************************************************************************************************************************************************************



Reading data




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Class Good Standing: 8334.0 samples
Class Default Risk: 8334.0 samples
Age above 50 att: 7107
Dependents more than one: 8235
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 dense (Dense)               (None, 64)                576

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,330
Trainable params: 34,562
Non-trainable params: 768
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

restoring weights of model DNN: GIVECREDIT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 model_1 (Functional)        (None, 16)                4656

 model_2 (Functional)        (None, 8)                 4648

=================================================================
Total params: 9,304
Trainable params: 9,304
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: GIVECREDIT_AE
Feature → index:
{'RevolvingUtilizationOfUnsecuredLines': 0, 'NumberOfTime3059DaysPastDueNotWorse': 1, 'DebtRatio': 2, 'MonthlyIncome': 3, 'NumberOfOpenCreditLinesAndLoans': 4, 'NumberOfTimes90DaysLate': 5, 'NumberRealEstateLoansOrLines': 6, 'NumberOfTime6089DaysPastDueNotWorse': 7}

Child → Parents (index form):
{4: [5, 1, 0, 3], 6: [5, 1], 0: [5], 3: [5, 1], 2: [4]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 1 1]
[0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (15, 8)
X_ shape: (3216, 8)
lof_cf min/max: 1.0654916909392067 3.436875797214586
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (9, 8)
X_ shape: (4379, 8)
lof_cf min/max: 1.1609908395184885 2.5584422171318186
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (17, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.0416557279307606 2.1634225247878645
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.092674816587175 2.0909288308378238
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
1.0416557279307606 1.496568187771694 3.436875797214586 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 0 1 0 0 0 0 0 1 1]
[1 1 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 0 1 0 0 0 0 0 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (17, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9904801724018009 3.168320969521137
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (14, 8)
X_ shape: (4379, 8)
lof_cf min/max: 1.0724030353785425 4.74400498696663
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (10, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.0712638950717412 2.6733316116841426
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.1382964563915103 1.9059006486363759
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9904801724018009 1.5434047988348276 4.74400498696663 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0
 1 1 0 1 0 0 0 0 1 1 1 0 0]
[1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0
 1 1 0 1 0 0 0 0 1 1 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (12, 8)
X_ shape: (3216, 8)
lof_cf min/max: 1.0051736204044341 3.046636859653245
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (15, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.9719263061746256 3.3457378157721296
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (14, 8)
X_ shape: (3553, 8)
lof_cf min/max: 0.9838103207558808 2.8980088457596693
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.039475899408639 5.385614479715436
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9719263061746256 1.6315712473088595 5.385614479715436 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0
 1 1 0 1 1 1 1 0 1 1 1 1 1]
[1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0
 1 1 0 1 1 1 1 0 1 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (14, 8)
X_ shape: (3216, 8)
lof_cf min/max: 1.0909645034803537 2.729940830253678
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (17, 8)
X_ shape: (4379, 8)
lof_cf min/max: 1.193626777412402 2.932949131588943
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (12, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.1173969300477957 2.8123265674538214
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (7, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.061911391538213 2.242994838606579
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
1.061911391538213 1.753044836979973 2.932949131588943 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 1 1 1 1 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1
 1 0 1 0 1 0 0 0 0 0 1 1 1]
[1 0 1 1 1 1 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1
 1 0 1 0 1 0 0 0 0 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (9, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9972374946099869 2.951973354613488
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (18, 8)
X_ shape: (4379, 8)
lof_cf min/max: 1.1399843252370612 3.551601194208698
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (15, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.0539500309884322 2.5379462626823943
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (8, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.0356978850300254 2.979462348543526
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9972374946099869 1.6457154477686813 3.551601194208698 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CACTUS (3/5)
********************************************************************************************************************************************************************************************************



Reading data




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Class Good Standing: 8334.0 samples
Class Default Risk: 8334.0 samples
Age above 50 att: 7107
Dependents more than one: 8235
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 dense (Dense)               (None, 64)                576

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,330
Trainable params: 34,562
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: GIVECREDIT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 8)]          0           []

 model_1 (Functional)           (None, 4)            1476        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 8)            1480        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,966
Trainable params: 2,966
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: GIVECREDIT_CACTUS
Feature → index:
{'RevolvingUtilizationOfUnsecuredLines': 0, 'NumberOfTime3059DaysPastDueNotWorse': 1, 'DebtRatio': 2, 'MonthlyIncome': 3, 'NumberOfOpenCreditLinesAndLoans': 4, 'NumberOfTimes90DaysLate': 5, 'NumberRealEstateLoansOrLines': 6, 'NumberOfTime6089DaysPastDueNotWorse': 7}

Child → Parents (index form):
{4: [5, 1, 0, 3], 6: [5, 1], 0: [5], 3: [5, 1], 2: [4]}
Building model: CondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 8)                 1480

 model (Functional)          (None, 2)                 35330

=================================================================
Total params: 36,810
Trainable params: 0
Non-trainable params: 36,810
_________________________________________________________________
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 1 1]
[1 0 0 0 0 1 1 0 1 1 1 0 0 1 1 1 1 1 0 1 0 0 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1
 1 0 1 0 1 1 1 1 1 1 0 1 1]
0.72
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (15, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9713105813346383 1.6001947651062807
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (9, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.9690145015917421 1.2474231620272456
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (17, 8)
X_ shape: (3553, 8)
lof_cf min/max: 0.9960383701663891 3.7829622463066133
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 0.9699270651773544 1.206719669111322
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9690145015917421 1.0825272166822995 3.7829622463066133 50
2/2 [==============================] - 0s 4ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 0 1 0 0 0 0 0 1 1]
[1 1 1 1 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 1 0 1 1 1 1 0 0 0 1 1 1 1]
0.66
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (17, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9760092324487141 1.2742556588148735
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (14, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.9872897619969169 1.6764388980119194
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (10, 8)
X_ shape: (3553, 8)
lof_cf min/max: 0.9562317994087796 1.5805300233857371
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.0031811789950047 1.666135042121857
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9562317994087796 1.0975005498156132 1.6764388980119194 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0
 1 1 0 1 0 0 0 0 1 1 1 0 0]
[1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1
 1 1 0 1 0 0 0 0 1 0 1 1 0]
0.72
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (12, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9699071861300312 1.3187015818890828
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (15, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.9651897198189371 1.2245829973447537
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (14, 8)
X_ shape: (3553, 8)
lof_cf min/max: 0.9904184950656882 1.64112071771577
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 0.963458345429461 1.3688845752366423
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.963458345429461 1.0742195423256238 1.64112071771577 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0
 1 1 0 1 1 1 1 0 1 1 1 1 1]
[1 1 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 0 1 0 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 1
 1 0 0 1 1 1 1 0 1 1 1 1 1]
0.76
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (14, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9823759017832607 1.2394688932101647
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (17, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.959443645144197 1.5037020539516202
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (12, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.0084175422675299 2.489959368550819
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (7, 8)
X_ shape: (2167, 8)
lof_cf min/max: 0.9640604391589348 1.3156320737471312
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.959443645144197 1.104659299525332 2.489959368550819 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 1 1 1 1 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1
 1 0 1 0 1 0 0 0 0 0 1 1 1]
[1 1 1 0 0 1 1 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 1 1 0 1 1 1 1 0 1
 1 0 1 0 1 0 0 1 1 1 1 0 1]
0.58
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (9, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9687393416773256 1.4899745962572517
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (18, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.9647928736287762 1.495476359495773
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (15, 8)
X_ shape: (3553, 8)
lof_cf min/max: 0.9740054377442917 1.4741642131832835
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (8, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.067681177975326 1.3443064211843114
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9647928736287762 1.1400852099005654 1.495476359495773 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CausalCACTUS (4/5)
********************************************************************************************************************************************************************************************************



Reading data




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Class Good Standing: 8334.0 samples
Class Default Risk: 8334.0 samples
Age above 50 att: 7107
Dependents more than one: 8235
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 dense (Dense)               (None, 64)                576

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,330
Trainable params: 34,562
Non-trainable params: 768
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

restoring weights of model DNN: GIVECREDIT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 8)]          0           []

 model_1 (Functional)           (None, 4)            1476        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 8)            1480        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,966
Trainable params: 2,966
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: GIVECREDIT_CACTUS
Feature → index:
{'RevolvingUtilizationOfUnsecuredLines': 0, 'NumberOfTime3059DaysPastDueNotWorse': 1, 'DebtRatio': 2, 'MonthlyIncome': 3, 'NumberOfOpenCreditLinesAndLoans': 4, 'NumberOfTimes90DaysLate': 5, 'NumberRealEstateLoansOrLines': 6, 'NumberOfTime6089DaysPastDueNotWorse': 7}

Child → Parents (index form):
{4: [5, 1, 0, 3], 6: [5, 1], 0: [5], 3: [5, 1], 2: [4]}
Building model: CausalCondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 8)                 1480

 model (Functional)          (None, 2)                 35330

=================================================================
Total params: 36,810
Trainable params: 0
Non-trainable params: 36,810
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 1 1]
[1 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 0 1 1 1 0 1 0 1 0 0 0 0 0 0 1 0
 1 0 1 0 1 1 1 0 1 0 1 1 1]
0.9
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (15, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.971144501216769 1.31834607676366
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (9, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.9635929203256419 1.163886322491343
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (17, 8)
X_ shape: (3553, 8)
lof_cf min/max: 0.9700200023524579 3.7829622463066133
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 0.9612471062345612 1.3657223409870347
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9612471062345612 1.0438797680752137 3.7829622463066133 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 0 1 0 0 0 0 0 1 1]
[1 1 0 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1
 1 1 1 1 1 1 0 0 0 0 1 1 1]
0.9
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (17, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9760092324487141 1.3265305334413842
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (14, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.9590194296371019 1.2710298037490158
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (10, 8)
X_ shape: (3553, 8)
lof_cf min/max: 0.9545424282639426 1.564990229421091
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 0.9872707637581415 1.398147448579104
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9545424282639426 1.089890674819948 1.564990229421091 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0
 1 1 0 1 0 0 0 0 1 1 1 0 0]
[1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0
 1 1 0 1 0 0 0 0 1 1 1 1 0]
0.92
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (12, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9675698090240107 1.2338810235143767
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (15, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.9457660928791086 1.230223561232869
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (14, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.006467064885429 1.3375380631430223
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 0.9645650156408483 1.2730902829868629
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9457660928791086 1.054566201340312 1.3375380631430223 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0
 1 1 0 1 1 1 1 0 1 1 1 1 1]
[1 1 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 0 0 1 0 1 0
 1 1 0 1 1 1 1 0 1 1 1 1 1]
0.92
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (14, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.966730782073915 1.4975427152938676
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (17, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.9518937309530829 1.175531961804953
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (12, 8)
X_ shape: (3553, 8)
lof_cf min/max: 0.9847152231802414 1.7410675843460073
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (7, 8)
X_ shape: (2167, 8)
lof_cf min/max: 0.9635304770543658 1.162768414557973
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9518937309530829 1.084855630922946 1.7410675843460073 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 1 1 1 1 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1
 1 0 1 0 1 0 0 0 0 0 1 1 1]
[1 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 0 1 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 1
 1 0 1 0 1 0 0 1 0 1 1 1 1]
0.82
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (9, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9872142963152252 1.7190283387654206
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (18, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.968216923923668 1.3721144140196038
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (15, 8)
X_ shape: (3553, 8)
lof_cf min/max: 0.9665638221614681 1.285469789282342
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (8, 8)
X_ shape: (2167, 8)
lof_cf min/max: 0.9645178613450878 1.2263290014892234
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9645178613450878 1.0645721006515252 1.7190283387654206 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
            Model     Dataset      CFMethod                Metric  Value
0      LatentCF++  GIVECREDIT    LatentCFpp             proximity  2.138
1      LatentCF++  GIVECREDIT    LatentCFpp           n_proximity  0.756
2      LatentCF++  GIVECREDIT    LatentCFpp              validity  1.000
3      LatentCF++  GIVECREDIT    LatentCFpp           compactness  0.045
4      LatentCF++  GIVECREDIT    LatentCFpp           lof_context  1.443
..            ...         ...           ...                   ...    ...
220  CausalCACTUS  GIVECREDIT  CausalCACTUS           lof_context  1.110
221  CausalCACTUS  GIVECREDIT  CausalCACTUS  causal_validity_hard  0.400
222  CausalCACTUS  GIVECREDIT  CausalCACTUS  causal_validity_soft  0.840
223  CausalCACTUS  GIVECREDIT  CausalCACTUS    causal_compact_val  0.515
224  CausalCACTUS  GIVECREDIT  CausalCACTUS       inlier_fraction  0.944

[225 rows x 5 columns]

In [8]:
child_to_parents_dict

{4: [5, 1, 0, 3], 6: [5, 1], 0: [5], 3: [5, 1], 2: [4]}

In [9]:
# Pivoting the dataframe
df_metrics_pivot = df_metrics.pivot_table(
    index=["Dataset", "Model"],
    columns="Metric",
    values="Value",
    aggfunc=['mean', 'std']
)

desired_order = [
    "validity",
    "lof_context",
    "compactness",
    "n_proximity",
    "causal_validity_hard",
    "causal_validity_soft",
    "causal_compact_val",
    "inlier_fraction"
]
df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)
df_metrics_pivot = df_metrics_pivot[desired_order]

df_metrics_pivot.rename(
    columns={
        "validity": "Validity",
        "lof_context": "LOF",
        "compactness": "Compactness",
        "n_proximity": "Proximity",
        "causal_validity_hard": "Causal Validity (Hard)",
        "causal_validity_soft": "Causal Validity (Soft)",
        "causal_compact_val": "Causal Compact Validity",
        "inlier_fraction": "inlier_fraction"
    },
    inplace=True
)

df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)

# df_formatted = df_metrics_pivot.apply(
#     lambda x: x["mean"].map("${:2.2f}".format)
#     + " \\pm "
#     + x["std"].map("{:2.2f} $".format),
#     axis=1
# )
# df_formatted

df_formatted = df_metrics_pivot.apply(
    lambda x: (
        x["mean"].round(2).astype(str)
        + " ± "
        + x["std"].round(2).astype(str)
    ),
    axis=1
)
df_formatted

Metric                      Validity          LOF  Compactness    Proximity  \
Dataset    Model
GIVECREDIT CACTUS        0.69 ± 0.07  1.16 ± 0.02  0.09 ± 0.03  0.52 ± 0.03
           CausalCACTUS  0.89 ± 0.04  1.11 ± 0.01  0.25 ± 0.04  0.41 ± 0.02
           LatentCF++      1.0 ± 0.0   1.41 ± 0.1  0.05 ± 0.01   0.71 ± 0.1
           Prototype C     1.0 ± 0.0  2.02 ± 0.13  0.04 ± 0.02  1.12 ± 0.11
           Prototype D     1.0 ± 0.0  1.75 ± 0.11  0.04 ± 0.01  1.07 ± 0.04

Metric                  Causal Validity (Hard) Causal Validity (Soft)  \
Dataset    Model
GIVECREDIT CACTUS                  0.35 ± 0.02            0.78 ± 0.01
           CausalCACTUS            0.34 ± 0.04            0.78 ± 0.04
           LatentCF++              0.25 ± 0.03             0.7 ± 0.02
           Prototype C             0.53 ± 0.04            0.85 ± 0.03
           Prototype D             0.45 ± 0.11            0.82 ± 0.03

Metric                  Causal Compact Validity inlier_fraction
Dataset    Model
GIVECREDIT CACTUS                   0.39 ± 0.02     0.95 ± 0.03
           CausalCACTUS             0.45 ± 0.04     0.97 ± 0.02
           LatentCF++               0.33 ± 0.03     0.75 ± 0.08
           Prototype C               0.3 ± 0.02     0.33 ± 0.08
           Prototype D               0.3 ± 0.01     0.43 ± 0.07

## Graph 2 (Moderate priors)

In [ ]:
N = 50 
N_BOOTSTRAP = 5
# SEED_list = [23] * N_BOOTSTRAP
SEED_list = [11, 22, 33, 44, 55]

# Number of samples to compute the metrics for CF evaluation
METRICS = []

for i, exp in enumerate(EXP):
    print("\n" * 2)
    print("*" * 200)
    print(f"Running exp: {exp['name']} ({i}/{len(EXP)})")
    print("*" * 200)
    print("\n" * 2)
    
    # Reading the data
    CLASS_CONFIG_PATH = exp["classifier"]
    AE_CONFIG_PATH = exp["AE"]

    class_config = get_exp_config(CLASS_CONFIG_PATH)
    print("Reading data")
    data = getData(class_config)

    # Getting classifier
    classifier = modelGen(class_config["type"], data, params=class_config, debug=True)
    classifier.load()

    # Getting AE-based Model
    AE_config = get_exp_config(AE_CONFIG_PATH)
    aeModel = modelGen(AE_config["type"], data, params=AE_config, debug=True)
    aeModel.load()

    # CF generation
    child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
        data.features_lbls,
        # TODO: change the string below for graph_str1 and graph_str2
        graph_str2
    )
    print("Feature → index:")
    print(feat2idx)
    print("\nChild → Parents (index form):")
    print(child_to_parents_dict)
    
    if exp["name"] == "CausalCACTUS":
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train,
            x_min=data.X_train.min(axis=0),
            x_max=data.X_train.max(axis=0),
            causal_index_map=child_to_parents_dict
        )
    else:
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train
        )

    for trial in range(N_BOOTSTRAP):

        # --- Sampling test data ---
        SEED = SEED_list[trial]
        os.environ['PYTHONHASHSEED'] = str(SEED)
        random.seed(SEED)
        np.random.seed(SEED)
        tf_random.set_seed(SEED)
        rand_idx = np.random.choice(len(data.X_test), N, replace=True)
        
        # previous name: x
        X_test = data.X_test[rand_idx, ...]
        # previous name: contest
        context_test = data.context_test[exp['context']].values
        context_test = context_test[rand_idx, ...]

        context_training = data.context_train[exp['context']].values

        # previous name: y
        y_test = np.argmax(data.y_test[rand_idx, ...], axis=1)
        y_original_logits = classifier.predict(X_test)
        # previous name: y_
        y_original_labels = np.argmax(y_original_logits, axis=1)

        # --- CF generation ---
        # previous names: 
        # cf_x, cf_y_, x, __
        X_cf, y_cf_labels, X_internal, y_internal = CF_method.transform(
            X_test,
            y_original_labels,
            target_context=context_test,
            verbose=0
        )              
      
        # --- CF evaluation ---
        cf_scores, cf_scores_labels = cf_eval(
            data.X_train, # previous name: data.X_train
            context_training, # previous name: context_training,
            X_test, # previous name: x,
            X_cf, # previous name: cf_x, 
            y_original_labels, # previous name: y_,
            context_test, # previous name: context,
            y_cf_labels, # previous name: cf_y_
            data.scaler_inverse_transform(X_test),
            data.scaler_inverse_transform(X_cf),
            child_to_parents_dict
        )

        for i_metric, label in enumerate(cf_scores_labels):
            METRICS.append([
                exp["name"],
                exp["data"],
                exp["CFmethod"],
                label,
                cf_scores[i_metric]
            ])

    # Cleaning GPU models
    cleanup_gpu()

# --- Metrics aggregation ---
df_metrics = pd.DataFrame(
    data=METRICS,
    columns=["Model", "Dataset", "CFMethod", "Metric", "Value"]
)
df_metrics = df_metrics.round(3)
print(df_metrics)

********************************************************************************************************************************************************************************************************
Running exp: LatentCF++ (0/5)
********************************************************************************************************************************************************************************************************



Reading data




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Class Good Standing: 8334.0 samples
Class Default Risk: 8334.0 samples
Age above 50 att: 7107
Dependents more than one: 8235
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 dense (Dense)               (None, 64)                576

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,330
Trainable params: 34,562
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: GIVECREDIT_class

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 model_1 (Functional)        (None, 16)                4656

 model_2 (Functional)        (None, 8)                 4648

=================================================================
Total params: 9,304
Trainable params: 9,304
Non-trainable params: 0
_________________________________________________________________
restoring weights of model AE: GIVECREDIT_AE

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Feature → index:
{'RevolvingUtilizationOfUnsecuredLines': 0, 'NumberOfTime3059DaysPastDueNotWorse': 1, 'DebtRatio': 2, 'MonthlyIncome': 3, 'NumberOfOpenCreditLinesAndLoans': 4, 'NumberOfTimes90DaysLate': 5, 'NumberRealEstateLoansOrLines': 6, 'NumberOfTime6089DaysPastDueNotWorse': 7}

Child → Parents (index form):
{2: [6, 4], 4: [0, 3]}
Building model: latentCF [CF]
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 16)]              0

 model_2 (Functional)        (None, 8)                 4648

 model (Functional)          (None, 2)                 35330

=================================================================
Total params: 39,978
Trainable params: 39,210
Non-trainable params: 768
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 1 0 0 0 1 0 0 1 0 1 0
 0 1 1 1 0 0 1 1 1 1 1 1 1]
[1 0 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 1 0 0 0 1 0 0 1 0 1 0
 0 1 1 1 0 0 1 1 1 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

cf_samples_ shape: (15, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9647633915019425 1.9285869937320055
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (13, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.9740415571177771 2.8617953148678836
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (11, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.10765596821928 3.997533322804933
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (11, 8)
X_ shape: (2167, 8)
lof_cf min/max: 0.974838246528846 1.5196832934912998
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9647633915019425 1.2458985283915918 3.997533322804933 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 0 0 1 1 1 0 0 0 1 1 1 0 1 1 0 1 1 0 1
 0 1 1 0 1 1 1 0 1 0 0 0 0]
[1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 0 0 1 1 1 0 0 0 1 1 1 0 1 1 0 1 1 0 1
 0 1 1 0 1 1 1 0 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

cf_samples_ shape: (14, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9758424769662918 2.372545878057504
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (16, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.9956531038553613 2.1539993661512735
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (11, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.0078326948162704 3.6905784334044025
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (9, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.0696932251910904 2.0145746780773424
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9758424769662918 1.2528199036244119 3.6905784334044025 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 1 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0
 1 1 0 0 0 1 0 0 0 1 0 1 1]
[1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 1 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0
 1 1 0 0 0 1 0 0 0 1 0 1 1]
1.0

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (21, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9662387615622723 3.144979081790058
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (13, 8)
X_ shape: (4379, 8)
lof_cf min/max: 1.0052839179903097 2.670918246673902
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (10, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.0131291482506948 2.0398558036014984
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (6, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.0667247266739035 2.1494638184172565
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9662387615622723 1.263891148247001 3.144979081790058 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0
 1 0 1 0 1 0 1 0 0 1 1 1 0]
[1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0
 1 0 1 0 1 0 1 0 0 1 1 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (16, 8)
X_ shape: (3216, 8)

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

lof_cf min/max: 0.9820608408961107 2.615673558406867
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (19, 8)
X_ shape: (4379, 8)
lof_cf min/max: 1.0123894405165679 2.8158919160196763
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (7, 8)
X_ shape: (3553, 8)
lof_cf min/max: 0.9922910441455249 1.6349276106360149
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (8, 8)
X_ shape: (2167, 8)
lof_cf min/max: 0.9589013836492712 2.0685218925170026
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9589013836492712 1.240377729557782 2.8158919160196763 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0 1 0 0 1 1 1 1 1 0 1
 1 0 0 0 0 0 0 1 1 0 1 0 0]
[0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0 1 0 0 1 1 1 1 1 0 1
 1 0 0 0 0 0 0 1 1 0 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3243
Unique rows: 3216
After np.unique(): subset size: 3216
cf_samples_ shape: (15, 8)
X_ shape: (3216, 8)
lof_cf min/max: 0.9657282143791063 3.296102584066438
lof_train min/max: 0.9465570652688365 3.282124843560917
mean train LOF: 1.1444881201316588
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4393
Unique rows: 4379
After np.unique(): subset size: 4379
cf_samples_ shape: (20, 8)
X_ shape: (4379, 8)
lof_cf min/max: 0.989882089186926 2.356125424203789
lof_train min/max: 0.9533726709159543 61.731034094851054
mean train LOF: 1.1579012060688825
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3563
Unique rows: 3553
After np.unique(): subset size: 3553
cf_samples_ shape: (11, 8)
X_ shape: (3553, 8)
lof_cf min/max: 1.1177986068170218 2.080679758542825
lof_train min/max: 0.9489198921557647 10.298136548479652
mean train LOF: 1.1650175663041438
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2173
Unique rows: 2167
After np.unique(): subset size: 2167
cf_samples_ shape: (4, 8)
X_ shape: (2167, 8)
lof_cf min/max: 1.2286702235646998 2.2812715942625346
lof_train min/max: 0.949469837940335 4.919834985063315
mean train LOF: 1.1459632555760388
0.9657282143791063 1.3107941575954736 3.296102584066438 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype C (1/5)
********************************************************************************************************************************************************************************************************



Reading data




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Class Good Standing: 8334.0 samples
Class Default Risk: 8334.0 samples
Age above 50 att: 7093
Dependents more than one: 8188
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 dense (Dense)               (None, 64)                576

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,330
Trainable params: 34,562
Non-trainable params: 768
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

restoring weights of model DNN: GIVECREDIT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 model_1 (Functional)        (None, 16)                4656

 model_2 (Functional)        (None, 8)                 4648

=================================================================
Total params: 9,304
Trainable params: 9,304
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: GIVECREDIT_AE
Feature → index:
{'RevolvingUtilizationOfUnsecuredLines': 0, 'NumberOfTime3059DaysPastDueNotWorse': 1, 'DebtRatio': 2, 'MonthlyIncome': 3, 'NumberOfOpenCreditLinesAndLoans': 4, 'NumberOfTimes90DaysLate': 5, 'NumberRealEstateLoansOrLines': 6, 'NumberOfTime6089DaysPastDueNotWorse': 7}

Child → Parents (index form):
{2: [6, 4], 4: [0, 3]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 1
 0 1 1 0 0 0 0 0 1 1 1 0 1]
[1 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 1
 0 1 1 0 0 0 0 0 1 1 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (15, 8)
X_ shape: (3195, 8)
lof_cf min/max: 1.275388598029526 4.058531139634339
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (8, 8)
X_ shape: (4413, 8)
lof_cf min/max: 1.122618845977766 3.0113879418111824
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (17, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.1033820999299868 3.085415717256333
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (10, 8)
X_ shape: (2127, 8)
lof_cf min/max: 0.9999143836137254 2.5380608713039203
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
0.9999143836137254 1.7535145421328808 4.058531139634339 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 0 0 1
 0 1 1 0 1 1 0 0 1 0 0 0 0]
[1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 0 0 1
 0 1 1 0 1 1 0 0 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (11, 8)
X_ shape: (3195, 8)
lof_cf min/max: 1.224980474377693 3.172067052671683
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (11, 8)
X_ shape: (4413, 8)
lof_cf min/max: 1.0091093844931645 3.549835050115813
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (14, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.1734420761001616 3.085415717256333
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (14, 8)
X_ shape: (2127, 8)
lof_cf min/max: 1.1249102026299334 4.323654322646497
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
1.0091093844931645 1.7038073582581554 4.323654322646497 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 1 0 0 0 1 0 0 1]
[1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 1 0 0 0 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (21, 8)
X_ shape: (3195, 8)
lof_cf min/max: 1.2045521933531371 4.80495134615916
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (9, 8)
X_ shape: (4413, 8)
lof_cf min/max: 1.382679085449572 2.3189311868101448
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (13, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.025710898123955 3.8140968084830096
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (7, 8)
X_ shape: (2127, 8)
lof_cf min/max: 1.0389106228802105 1.8163095574763204
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
1.025710898123955 1.7636509798639493 4.80495134615916 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0
 1 1 0 0 1 0 1 0 0 1 0 1 0]
[0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0
 1 1 0 0 1 0 1 0 0 1 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (14, 8)
X_ shape: (3195, 8)
lof_cf min/max: 1.1095690819034265 2.6754610444344538
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (19, 8)
X_ shape: (4413, 8)
lof_cf min/max: 1.27190939798221 2.8420100529269425
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (11, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.0788135913342878 3.4263841777275506
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (6, 8)
X_ shape: (2127, 8)
lof_cf min/max: 1.5057860000518608 3.3161610806798727
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
1.0788135913342878 1.8632332877462214 3.4263841777275506 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 1 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1
 1 0 0 0 0 1 0 1 1 0 1 0 0]
[0 1 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1
 1 0 0 0 0 1 0 1 1 0 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (14, 8)
X_ shape: (3195, 8)
lof_cf min/max: 1.1442476688108203 4.277564160367281
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (21, 8)
X_ shape: (4413, 8)
lof_cf min/max: 1.2154915988007098 3.2607915389673496
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (9, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.194837712006853 4.785903389241265
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (6, 8)
X_ shape: (2127, 8)
lof_cf min/max: 1.8425302202038063 3.482096281582857
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
1.1442476688108203 2.070687077428367 4.785903389241265 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype D (2/5)
********************************************************************************************************************************************************************************************************



Reading data




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Class Good Standing: 8334.0 samples
Class Default Risk: 8334.0 samples
Age above 50 att: 7093
Dependents more than one: 8188
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 dense (Dense)               (None, 64)                576

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,330
Trainable params: 34,562
Non-trainable params: 768
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

restoring weights of model DNN: GIVECREDIT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 model_1 (Functional)        (None, 16)                4656

 model_2 (Functional)        (None, 8)                 4648

=================================================================
Total params: 9,304
Trainable params: 9,304
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: GIVECREDIT_AE
Feature → index:
{'RevolvingUtilizationOfUnsecuredLines': 0, 'NumberOfTime3059DaysPastDueNotWorse': 1, 'DebtRatio': 2, 'MonthlyIncome': 3, 'NumberOfOpenCreditLinesAndLoans': 4, 'NumberOfTimes90DaysLate': 5, 'NumberRealEstateLoansOrLines': 6, 'NumberOfTime6089DaysPastDueNotWorse': 7}

Child → Parents (index form):
{2: [6, 4], 4: [0, 3]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 1
 0 1 1 0 0 0 0 0 1 1 1 0 1]
[1 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 1
 0 1 1 0 0 0 0 0 1 1 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (15, 8)
X_ shape: (3195, 8)
lof_cf min/max: 1.1447203203156966 3.335346663055635
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (8, 8)
X_ shape: (4413, 8)
lof_cf min/max: 1.2243535496520466 3.4520499699745932
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (17, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.0605756335230345 3.2579191590522676
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (10, 8)
X_ shape: (2127, 8)
lof_cf min/max: 1.0881747766385936 2.812079845585771
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
1.0605756335230345 1.6647953170119356 3.4520499699745932 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 0 0 1
 0 1 1 0 1 1 0 0 1 0 0 0 0]
[1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 0 0 1
 0 1 1 0 1 1 0 0 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (11, 8)
X_ shape: (3195, 8)
lof_cf min/max: 1.0797175962914136 2.5431492294000684
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (11, 8)
X_ shape: (4413, 8)
lof_cf min/max: 1.0072624357105864 2.4048499525005296
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (14, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.1083731289560945 2.6754574105133844
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (14, 8)
X_ shape: (2127, 8)
lof_cf min/max: 1.0835275938532114 2.3948940170296056
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
1.0072624357105864 1.4153111198708404 2.6754574105133844 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 1 0 0 0 1 0 0 1]
[1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 1 0 0 0 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (21, 8)
X_ shape: (3195, 8)
lof_cf min/max: 1.0473640057280187 3.8294684113299704
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (9, 8)
X_ shape: (4413, 8)
lof_cf min/max: 1.1006103985218934 4.046019550953695
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (13, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.0570880525653261 2.922593449239869
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (7, 8)
X_ shape: (2127, 8)
lof_cf min/max: 1.1542971420478743 3.115579631208714
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
1.0473640057280187 1.4948902584136885 4.046019550953695 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0
 1 1 0 0 1 0 1 0 0 1 0 1 0]
[0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0
 1 1 0 0 1 0 1 0 0 1 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (14, 8)
X_ shape: (3195, 8)
lof_cf min/max: 1.2528671754389717 2.7435742483046814
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (19, 8)
X_ shape: (4413, 8)
lof_cf min/max: 1.0962705124315768 3.5411869554819497
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (11, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.0245251324101903 2.52542206245541
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (6, 8)
X_ shape: (2127, 8)
lof_cf min/max: 0.9851505615060957 1.614563106539719
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
0.9851505615060957 1.6010862632019598 3.5411869554819497 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 1 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1
 1 0 0 0 0 1 0 1 1 0 1 0 0]
[0 1 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1
 1 0 0 0 0 1 0 1 1 0 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (14, 8)
X_ shape: (3195, 8)
lof_cf min/max: 1.0112787693368956 3.1975238210222616
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (21, 8)
X_ shape: (4413, 8)
lof_cf min/max: 1.0448207838419012 3.245753783163413
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (9, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.1083731289560945 2.4499764324916122
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (6, 8)
X_ shape: (2127, 8)
lof_cf min/max: 1.063175477258719 1.8322184724854729
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
1.0112787693368956 1.642839987522208 3.245753783163413 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CACTUS (3/5)
********************************************************************************************************************************************************************************************************



Reading data




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Class Good Standing: 8334.0 samples
Class Default Risk: 8334.0 samples
Age above 50 att: 7093
Dependents more than one: 8188
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 dense (Dense)               (None, 64)                576

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,330
Trainable params: 34,562
Non-trainable params: 768
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

restoring weights of model DNN: GIVECREDIT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 8)]          0           []

 model_1 (Functional)           (None, 4)            1476        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 8)            1480        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,966
Trainable params: 2,966
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: GIVECREDIT_CACTUS
Feature → index:
{'RevolvingUtilizationOfUnsecuredLines': 0, 'NumberOfTime3059DaysPastDueNotWorse': 1, 'DebtRatio': 2, 'MonthlyIncome': 3, 'NumberOfOpenCreditLinesAndLoans': 4, 'NumberOfTimes90DaysLate': 5, 'NumberRealEstateLoansOrLines': 6, 'NumberOfTime6089DaysPastDueNotWorse': 7}

Child → Parents (index form):
{2: [6, 4], 4: [0, 3]}
Building model: CondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 8)                 1480

 model (Functional)          (None, 2)                 35330

=================================================================
Total params: 36,810
Trainable params: 0
Non-trainable params: 36,810
_________________________________________________________________
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 1
 0 1 1 0 0 0 0 0 1 1 1 0 1]
[0 1 0 0 0 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 0 1 1 0 0 1 0 1 0
 1 0 1 0 0 1 0 1 1 1 0 1 1]
0.6
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (15, 8)
X_ shape: (3195, 8)
lof_cf min/max: 0.9547095839069757 1.6819014036838187
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (8, 8)
X_ shape: (4413, 8)
lof_cf min/max: 0.9651189588711535 1.1693727412759132
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (17, 8)
X_ shape: (3584, 8)
lof_cf min/max: 0.960658105493065 1.70617606753533
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (10, 8)
X_ shape: (2127, 8)
lof_cf min/max: 0.9616443107264507 1.4059363966965432
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
0.9547095839069757 1.1009557119018318 1.70617606753533 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 0 0 1
 0 1 1 0 1 1 0 0 1 0 0 0 0]
[0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 1 0 1 1 0 1 0 0 1 1 0 0 1
 1 0 1 1 1 0 1 1 1 1 0 1 0]
0.56
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (11, 8)
X_ shape: (3195, 8)
lof_cf min/max: 0.9730380909766574 1.6413012347790759
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (11, 8)
X_ shape: (4413, 8)
lof_cf min/max: 0.9651189588711535 1.27806993232438
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (14, 8)
X_ shape: (3584, 8)
lof_cf min/max: 0.9751396706524937 1.3822788880771089
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (14, 8)
X_ shape: (2127, 8)
lof_cf min/max: 0.9982778805861379 1.3884022761878956
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
0.9651189588711535 1.120056015736466 1.6413012347790759 50
2/2 [==============================] - 0s 4ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 1 0 0 0 1 0 0 1]
[1 0 1 0 0 1 0 0 1 1 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 0 1 0 1
 1 1 0 1 1 1 0 1 0 0 1 0 0]
0.54
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (21, 8)
X_ shape: (3195, 8)
lof_cf min/max: 0.9835134782596564 1.8031294648740104
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (9, 8)
X_ shape: (4413, 8)
lof_cf min/max: 0.960544157803314 1.4587250734088266
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (13, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.0200277464722052 1.4848054303395763
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (7, 8)
X_ shape: (2127, 8)
lof_cf min/max: 0.9934833054516375 1.2603263567707335
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
0.960544157803314 1.0758856328597468 1.8031294648740104 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0
 1 1 0 0 1 0 1 0 0 1 0 1 0]
[0 0 1 0 1 0 1 0 1 0 1 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0 1 0 0 1 1 0 0 1 1 0 0
 1 0 0 1 1 0 0 1 0 1 0 1 0]
0.72
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (14, 8)
X_ shape: (3195, 8)
lof_cf min/max: 0.977188552395149 1.6548057261311566
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (19, 8)
X_ shape: (4413, 8)
lof_cf min/max: 0.9736232100066016 1.305295144891783
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (11, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.015826198099309 1.7639513626496408
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (6, 8)
X_ shape: (2127, 8)
lof_cf min/max: 0.9897071130261819 1.244721471375171
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
0.9736232100066016 1.0524769201068418 1.7639513626496408 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 1 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1
 1 0 0 0 0 1 0 1 1 0 1 0 0]
[1 1 1 1 1 1 1 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1
 0 0 1 0 1 0 1 1 1 0 1 0 1]
0.6
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (14, 8)
X_ shape: (3195, 8)
lof_cf min/max: 0.977594577934567 1.3834648370005758
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (21, 8)
X_ shape: (4413, 8)
lof_cf min/max: 0.9647089640728526 1.4820287224980095
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (9, 8)
X_ shape: (3584, 8)
lof_cf min/max: 0.9730198441936964 1.505478410142779
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (6, 8)
X_ shape: (2127, 8)
lof_cf min/max: 0.9708086966436982 1.2276031395727371
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
0.9647089640728526 1.0480163133966034 1.505478410142779 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CausalCACTUS (4/5)
********************************************************************************************************************************************************************************************************



Reading data




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Class Good Standing: 8334.0 samples
Class Default Risk: 8334.0 samples
Age above 50 att: 7093
Dependents more than one: 8188
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 8)]               0

 dense (Dense)               (None, 64)                576

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,330
Trainable params: 34,562
Non-trainable params: 768
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

restoring weights of model DNN: GIVECREDIT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 8)]          0           []

 model_1 (Functional)           (None, 4)            1476        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 8)            1480        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,966
Trainable params: 2,966
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: GIVECREDIT_CACTUS
Feature → index:
{'RevolvingUtilizationOfUnsecuredLines': 0, 'NumberOfTime3059DaysPastDueNotWorse': 1, 'DebtRatio': 2, 'MonthlyIncome': 3, 'NumberOfOpenCreditLinesAndLoans': 4, 'NumberOfTimes90DaysLate': 5, 'NumberRealEstateLoansOrLines': 6, 'NumberOfTime6089DaysPastDueNotWorse': 7}

Child → Parents (index form):
{2: [6, 4], 4: [0, 3]}
Building model: CausalCondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 8)                 1480

 model (Functional)          (None, 2)                 35330

=================================================================
Total params: 36,810
Trainable params: 0
Non-trainable params: 36,810
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 1
 0 1 1 0 0 0 0 0 1 1 1 0 1]
[1 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1 0 0 1 0 0 1
 1 1 1 0 0 0 0 0 1 1 1 1 1]
0.86
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (15, 8)
X_ shape: (3195, 8)
lof_cf min/max: 0.9750584039473872 1.7458508801036314
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (8, 8)
X_ shape: (4413, 8)
lof_cf min/max: 0.941431956647465 1.1054002233091467
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (17, 8)
X_ shape: (3584, 8)
lof_cf min/max: 0.9622440485504944 1.6881102129862229
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (10, 8)
X_ shape: (2127, 8)
lof_cf min/max: 0.9813258377663704 1.3640636574341334
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
0.941431956647465 1.09765628225267 1.7458508801036314 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 0 0 1
 0 1 1 0 1 1 0 0 1 0 0 0 0]
[1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 0 1
 1 1 1 0 1 1 0 0 1 0 0 0 0]
0.94
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (11, 8)
X_ shape: (3195, 8)
lof_cf min/max: 0.9828567574405701 1.7350546834457192
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (11, 8)
X_ shape: (4413, 8)
lof_cf min/max: 0.9659703131554692 1.421432008043142
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (14, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.0022226923209667 1.2867818149590058
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (14, 8)
X_ shape: (2127, 8)
lof_cf min/max: 0.9674873272926581 1.5444190656631733
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
0.9659703131554692 1.0975589798502194 1.7350546834457192 50
2/2 [==============================] - 0s 3ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 1 0 0 0 1 0 0 1]
[1 0 1 0 1 1 0 0 0 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0
 1 1 0 0 1 1 0 1 0 1 1 0 1]
0.84
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (21, 8)
X_ shape: (3195, 8)
lof_cf min/max: 0.9691630957873529 1.5529803819005537
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (9, 8)
X_ shape: (4413, 8)
lof_cf min/max: 0.9422277080202868 1.62231927018684
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (13, 8)
X_ shape: (3584, 8)
lof_cf min/max: 0.9904920590296237 1.2570179635447452
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (7, 8)
X_ shape: (2127, 8)
lof_cf min/max: 0.974300232750693 1.2160239162547308
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
0.9422277080202868 1.0720336022692645 1.62231927018684 50
2/2 [==============================] - 0s 4ms/step

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but QuantileTransformer was fitted without feature names
  warnings.warn(

[0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0
 1 1 0 0 1 0 1 0 0 1 0 1 0]
[0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 0 1 0 0 1 1 0 0 1 1 0 0
 1 1 0 0 1 0 1 0 0 1 0 1 0]
0.88
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3217
Unique rows: 3195
After np.unique(): subset size: 3195
cf_samples_ shape: (14, 8)
X_ shape: (3195, 8)
lof_cf min/max: 0.9654472529413438 1.1591560264950738
lof_train min/max: 0.9500319961567154 4.697967518621444
mean train LOF: 1.1470414414914387
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 4431
Unique rows: 4413
After np.unique(): subset size: 4413
cf_samples_ shape: (19, 8)
X_ shape: (4413, 8)
lof_cf min/max: 0.966472372379683 1.304448421058649
lof_train min/max: 0.9444151923412731 7.6460548321558175
mean train LOF: 1.1380723585473191
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 3592
Unique rows: 3584
After np.unique(): subset size: 3584
cf_samples_ shape: (11, 8)
X_ shape: (3584, 8)
lof_cf min/max: 1.0044582221974125 1.5554209632220615
lof_train min/max: 0.9469616370384104 15.920893159441457
mean train LOF: 1.164748825110481
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 2132
Unique rows: 2127
After np.unique(): subset size: 2127
cf_samples_ shape: (6, 8)
X_ shape: (2127, 8)
lof_cf min/max: 0.9902834787811057 1.1733864544796213
lof_train min/max: 0.944696938718346 4.845439340211145
mean train LOF: 1.1479598987891169
0.9654472529413438 1.0749336344310194 1.5554209632220615 50
2/2 [==============================] - 0s 3ms/step

In [13]:
child_to_parents_dict

{2: [6, 4], 4: [0, 3]}

In [14]:
# Pivoting the dataframe
df_metrics_pivot = df_metrics.pivot_table(
    index=["Dataset", "Model"],
    columns="Metric",
    values="Value",
    aggfunc=['mean', 'std']
)

desired_order = [
    "validity",
    "lof_context",
    "compactness",
    "n_proximity",
    "causal_validity_hard",
    "causal_validity_soft",
    "causal_compact_val",
    "inlier_fraction"
]
df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)
df_metrics_pivot = df_metrics_pivot[desired_order]

df_metrics_pivot.rename(
    columns={
        "validity": "Validity",
        "lof_context": "LOF",
        "compactness": "Compactness",
        "n_proximity": "Proximity",
        "causal_validity_hard": "Causal Validity (Hard)",
        "causal_validity_soft": "Causal Validity (Soft)",
        "causal_compact_val": "Causal Compact Validity",
        "inlier_fraction": "inlier_fraction"
    },
    inplace=True
)

df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)

# df_formatted = df_metrics_pivot.apply(
#     lambda x: x["mean"].map("${:2.2f}".format)
#     + " \\pm "
#     + x["std"].map("{:2.2f} $".format),
#     axis=1
# )
# df_formatted

df_formatted = df_metrics_pivot.apply(
    lambda x: (
        x["mean"].round(2).astype(str)
        + " ± "
        + x["std"].round(2).astype(str)
    ),
    axis=1
)
df_formatted

Metric                      Validity          LOF  Compactness    Proximity  \
Dataset    Model
GIVECREDIT CACTUS         0.6 ± 0.07  1.13 ± 0.03  0.09 ± 0.02  0.52 ± 0.03
           CausalCACTUS  0.87 ± 0.04  1.12 ± 0.03  0.26 ± 0.04  0.42 ± 0.02
           LatentCF++      1.0 ± 0.0   1.4 ± 0.03   0.06 ± 0.0  0.66 ± 0.07
           Prototype C     1.0 ± 0.0  1.99 ± 0.15  0.04 ± 0.02  1.23 ± 0.06
           Prototype D     1.0 ± 0.0   1.71 ± 0.1  0.04 ± 0.01   1.1 ± 0.02

Metric                  Causal Validity (Hard) Causal Validity (Soft)  \
Dataset    Model
GIVECREDIT CACTUS                  0.86 ± 0.04            0.93 ± 0.02
           CausalCACTUS            0.86 ± 0.05            0.93 ± 0.03
           LatentCF++               0.8 ± 0.05             0.9 ± 0.02
           Prototype C              0.9 ± 0.05            0.95 ± 0.03
           Prototype D             0.94 ± 0.03            0.97 ± 0.02

Metric                  Causal Compact Validity inlier_fraction
Dataset    Model
GIVECREDIT CACTUS                   0.47 ± 0.03     0.96 ± 0.03
           CausalCACTUS             0.53 ± 0.02     0.96 ± 0.02
           LatentCF++               0.42 ± 0.01     0.73 ± 0.06
           Prototype C              0.34 ± 0.02     0.27 ± 0.07
           Prototype D              0.36 ± 0.02     0.46 ± 0.08