In [1]:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="2,3"

%load_ext autoreload
%autoreload 2

In [2]:
import ipdb
from Data import *
from address import *
from modelGen import *
from utils import cf_eval, cleanup_gpu
from models import CausalCondLatentCF, latentCFpp, PrototypeLatentCF
from models import CondLatentCF # Note: get the vanilla CondLatentCF
import numpy as np
import random 
from tensorflow import random as tf_random
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from itertools import product
import argparse
import os
import pandas as pd

In [3]:
SEED = 23

os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf_random.set_seed(SEED)


CF_METHODS = {  
    "LatentCFpp": latentCFpp,
    "Prototype": PrototypeLatentCF,
    "CausalCACTUS": CausalCondLatentCF,
    "CACTUS": CondLatentCF
}

In [4]:
# Experimentos que a realizar
EXP = [
    {
        "name": "LatentCF++",
        "data": "ADULT",
        "classifier": "./exp/ADULT_class/config.json",
        "AE": "./exp/ADULT_AE/config.json",
        "CFmethod": "LatentCFpp",
        "context": [
            "sex",
            "race"
        ],
        "epochs": 100,
        "tol": 0.001,
        "target_prob": 0.5,
        "learning_rate": 0.1
    },
    {
        "name": "Prototype C",
        "data": "ADULT",
        "classifier": "./exp/ADULT_class/config.json",
        "AE": "./exp/ADULT_AE/config.json",
        "CFmethod": "Prototype",
        "context": [
            "sex",
            "race"
        ],
        "epochs": 100,
        "kappa": 0.0,
        "c": 1.0,
        "c_steps": 1,
        "beta": 0.1,
        "gamma": 0.0,
        "theta": 100.0,
        "clip": [
            -1000,
            1000
        ],
        "feat_range": [
            -4,
            4
        ],
        "lr": 0.01
    },
    {
        "name": "Prototype D",
        "data": "ADULT",
        "classifier": "./exp/ADULT_class/config.json",
        "AE": "./exp/ADULT_AE/config.json",
        "CFmethod": "Prototype",
        "context": [
            "sex",
            "race"
        ],
        "epochs": 100,
        "kappa": 0.0,
        "c": 1.0,
        "c_steps": 1,
        "beta": 0.1,
        "gamma": 100.0,
        "theta": 100.0,
        "clip": [
            -1000,
            1000
        ],
        "feat_range": [
            -4,
            4
        ],
        "lr": 0.01
    },
    {
        "name": "CACTUS",
        "data": "ADULT",
        "classifier": "./exp/ADULT_class/config.json",
        "AE": "./exp/ADULT_CACTUS/config.json",
        "CFmethod": "CACTUS",
        "context": [
            "sex",
            "race"
        ],
        "epochs": 300,
        "target_prob": 0.5,
        # "learning_rate": 0.005,
        "learning_rate": 0.01,
        "power": 0.5,
        "alpha": 0.7,
        "gamma": 0.1,
        "beta": 0.01,
        # "dynamicAlpha": True
        "dynamicAlpha": False
    },
    {
        "name": "CausalCACTUS",
        "data": "ADULT",
        "classifier": "./exp/ADULT_class/config.json",
        "AE": "./exp/ADULT_CACTUS/config.json",
        "CFmethod": "CausalCACTUS",
        "context": [
            "sex",
            "race"
        ],
        "epochs": 300,
        "target_prob": 0.5,
        # "learning_rate": 0.005,
        "learning_rate": 0.01,
        "power": 0.5,
        "alpha": 0.7,
        "gamma": 0.1,
        "beta": 0.01,
        "dynamicAlpha": True
        # "dynamicAlpha": False
    }
]

In [5]:
import re
from collections import defaultdict
# TODO: make a function to convert the causal paths for all the test samples
def build_causal_index_map(input_features, graph_str):
    """
    Returns:
        child_to_parents: dict {child_idx: [parent_idx, ...]}
        parent_to_children: dict {parent_idx: [child_idx, ...]}
        feat2idx: dict {feature_name: index}
    """

    # Feature name to index
    feat2idx = {f: i for i, f in enumerate(input_features)}

    # Extract edges using regex
    edges = re.findall(r'(\w+)\s*->\s*(\w+)', graph_str)

    child_to_parents = defaultdict(list)
    parent_to_children = defaultdict(list)

    for parent, child in edges:

        if parent not in feat2idx or child not in feat2idx:
            raise ValueError(f"Feature in graph not found in dataset: {parent} or {child}")

        p_idx = feat2idx[parent]
        c_idx = feat2idx[child]

        child_to_parents[c_idx].append(p_idx)
        parent_to_children[p_idx].append(c_idx)

    return dict(child_to_parents), dict(parent_to_children), feat2idx

# adult_rex5_constraints_min.dot
graph_str1 = """ 
strict digraph {
educationnum;
workclass;
occupation;
capitalloss;
sex;
race;
capitalgain;
hoursperweek;
maritalstatus;
educationnum -> occupation;
workclass -> hoursperweek;
workclass -> occupation;
capitalgain -> hoursperweek;
capitalgain -> maritalstatus;
hoursperweek -> occupation;
hoursperweek -> maritalstatus;
}
"""

# adult_rex6_constraints_mod.dot
graph_str2 = """
strict digraph {
educationnum;
workclass;
occupation;
capitalloss;
sex;
race;
capitalgain;
hoursperweek;
maritalstatus;
workclass -> hoursperweek;
workclass -> occupation;
capitalgain -> hoursperweek;
capitalgain -> occupation;
hoursperweek -> occupation;
}
"""

# # CF generation
# child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
#     data.features_lbls,
#     # graph_str
#     graph_str1
# )
# print("Feature → index:")
# print(feat2idx)
# print("\nChild → Parents (index form):")
# print(child_to_parents_dict)

In [6]:
# data.features_lbls

# # self.actionable_vars
# """
# "educationnum", "workclass", "occupation", "hoursperweek", "capitalgain", "capitalloss", "maritalstatus"
# """

## Graph 1 (Minimum priors)

In [7]:
N = 50 # TODO: rerun: unscaled LOF
N_BOOTSTRAP = 5
# SEED_list = [23] * N_BOOTSTRAP
SEED_list = [12, 23, 34, 45, 56]

# Number of samples to compute the metrics for CF evaluation
METRICS = []

for i, exp in enumerate(EXP):
    print("\n" * 2)
    print("*" * 200)
    print(f"Running exp: {exp['name']} ({i}/{len(EXP)})")
    print("*" * 200)
    print("\n" * 2)
    
    # Reading the data
    CLASS_CONFIG_PATH = exp["classifier"]
    AE_CONFIG_PATH = exp["AE"]

    class_config = get_exp_config(CLASS_CONFIG_PATH)
    print("Reading data")
    data = getData(class_config)

    # Getting classifier
    classifier = modelGen(class_config["type"], data, params=class_config, debug=True)
    classifier.load()

    # Getting AE-based Model
    AE_config = get_exp_config(AE_CONFIG_PATH)
    aeModel = modelGen(AE_config["type"], data, params=AE_config, debug=True)
    aeModel.load()

    # CF generation
    child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
        data.features_lbls,
        # TODO: change the string below for graph_str1 and graph_str2
        graph_str1
    )
    print("Feature → index:")
    print(feat2idx)
    print("\nChild → Parents (index form):")
    print(child_to_parents_dict)
    
    if exp["name"] == "CausalCACTUS":
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train,
            x_min=data.X_train.min(axis=0),
            x_max=data.X_train.max(axis=0),
            causal_index_map=child_to_parents_dict
        )
    else:
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train
        )

    for trial in range(N_BOOTSTRAP):

        # --- Sampling test data ---
        SEED = SEED_list[trial]
        os.environ['PYTHONHASHSEED'] = str(SEED)
        random.seed(SEED)
        np.random.seed(SEED)
        tf_random.set_seed(SEED)
        rand_idx = np.random.choice(len(data.X_test), N, replace=True)
        
        # previous name: x
        X_test = data.X_test[rand_idx, ...]
        # previous name: contest
        context_test = data.context_test[exp['context']].values
        context_test = context_test[rand_idx, ...]

        context_training = data.context_train[exp['context']].values

        # previous name: y
        y_test = np.argmax(data.y_test[rand_idx, ...], axis=1)
        y_original_logits = classifier.predict(X_test)
        # previous name: y_
        y_original_labels = np.argmax(y_original_logits, axis=1)

        # --- CF generation ---
        # previous names: 
        # cf_x, cf_y_, x, __
        X_cf, y_cf_labels, X_internal, y_internal = CF_method.transform(
            X_test,
            y_original_labels,
            target_context=context_test,
            verbose=0
        )              

        # TODO: One-hot encoding for Adult
        # self.features_lbls = [
        #     "educationnum",
        #     "workclass",
        #     "occupation",
        #     "hoursperweek",
        #     "capitalgain",
        #     "capitalloss",
        #     "maritalstatus"
        # ]
        cat_idx = [1, 2, 6] #     "workclass", "occupation", "maritalstatus"
        num_idx = [0, 3, 4, 5]
        X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])
        
        # --- CF evaluation ---
        cf_scores, cf_scores_labels = cf_eval(
            data.X_train, # previous name: data.X_train
            context_training, # previous name: context_training,
            X_test, # previous name: x,
            X_cf, # previous name: cf_x, 
            y_original_labels, # previous name: y_,
            context_test, # previous name: context,
            y_cf_labels, # previous name: cf_y_
            data.scaler_inverse_transform(X_test),
            data.scaler_inverse_transform(X_cf),
            child_to_parents_dict, 
            cat_idx,
            num_idx
        )

        for i_metric, label in enumerate(cf_scores_labels):
            METRICS.append([
                exp["name"],
                exp["data"],
                exp["CFmethod"],
                label,
                cf_scores[i_metric]
            ])

    # Cleaning GPU models
    cleanup_gpu()

# --- Metrics aggregation ---
df_metrics = pd.DataFrame(
    data=METRICS,
    columns=["Model", "Dataset", "CFMethod", "Metric", "Value"]
)
df_metrics = df_metrics.round(3)
print(df_metrics)

********************************************************************************************************************************************************************************************************
Running exp: LatentCF++ (0/5)
********************************************************************************************************************************************************************************************************



Reading data
sex
1    20380
0     9782
Name: count, dtype: int64
race
1    25933
0     4229
Name: count, dtype: int64

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:112: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:113: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["race"]))

----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 15016
Positive class (>50K): 7508.0
Context 'sex=Male': 10996
Context 'race=White': 13129
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 dense (Dense)               (None, 64)                512

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,266
Trainable params: 34,498
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: ADULT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 model_1 (Functional)        (None, 16)                4640

 model_2 (Functional)        (None, 7)                 4631

=================================================================
Total params: 9,271
Trainable params: 9,271
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: ADULT_AE
Feature → index:
{'educationnum': 0, 'workclass': 1, 'occupation': 2, 'hoursperweek': 3, 'capitalgain': 4, 'capitalloss': 5, 'maritalstatus': 6}

Child → Parents (index form):
{2: [0, 1, 3], 3: [1, 4], 6: [4, 3]}
Building model: latentCF [CF]
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 16)]              0

 model_2 (Functional)        (None, 7)                 4631

 model (Functional)          (None, 2)                 35266

=================================================================
Total params: 39,897
Trainable params: 39,129
Non-trainable params: 768
_________________________________________________________________
2/2 [==============================] - 1s 4ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 0
 0 1 0 0 0 1 1 1 1 1 1 1 1]
[0 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 1
 0 1 0 0 0 1 1 1 1 1 1 1 1]
0.98
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (9, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9788621639527944 1.1930356132560826
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9843660142156235 1.1627609409601214
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (39, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9936941340175348 1.4526094057192518
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9788621639527944 1.0614878711910394 1.4526094057192518 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1
 0 1 1 0 0 1 1 1 0 1 1 1 1]
[0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1
 0 1 1 0 0 1 1 1 0 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (4, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0939281848308082 1.2050949454113618
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.001534772156054 1.236064838481456
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (6, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.0041527954520633 1.2536470731662868
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (30, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9889227435135645 1.6431635517613927
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9889227435135645 1.1176170531170833 1.6431635517613927 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 1]
[1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (4, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0154475352419048 1.1379312125983647
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (13, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9795164961867019 1.465441603792258
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (3, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9989401694278685 1.211466601561349
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (30, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9841070530054636 1.5378331290597165
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9795164961867019 1.0806746944573928 1.5378331290597165 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 0 0 1
 0 1 1 1 1 1 0 1 1 0 1 1 1]
[0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 0 0 1
 0 1 1 1 1 1 0 1 1 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (2, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0806904028161501 1.1196666438133387
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (8, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.005733547281349 1.2323544481930728
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9905609056936018 1.4520071337983222
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (36, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9855281566104594 1.421536248648794
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9855281566104594 1.1204512732947578 1.4520071337983222 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0
 0 1 0 0 1 0 1 1 1 1 0 1 1]
[1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 1 0 1 1 0 0 1 1 0
 0 1 0 0 1 0 1 1 1 1 1 1 1]
0.96
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (2, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.1744247574343512 1.3037835550941388
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (12, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9937380849985078 1.6200140250140938
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (1, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.1742287231371107 1.1742287231371107
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (35, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9808038612402541 1.354330676592504
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9808038612402541 1.150511193057629 1.6200140250140938 50



********************************************************************************************************************************************************************************************************
Running exp: Prototype C (1/5)
********************************************************************************************************************************************************************************************************



Reading data
sex
1    20380
0     9782
Name: count, dtype: int64
race
1    25933
0     4229
Name: count, dtype: int64

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:112: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:113: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["race"]))

----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 15016
Positive class (>50K): 7508.0
Context 'sex=Male': 10996
Context 'race=White': 13129
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 dense (Dense)               (None, 64)                512

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,266
Trainable params: 34,498
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: ADULT_class
Building model
Building model: AE [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 model_1 (Functional)        (None, 16)                4640

 model_2 (Functional)        (None, 7)                 4631

=================================================================
Total params: 9,271
Trainable params: 9,271
Non-trainable params: 0
_________________________________________________________________
restoring weights of model AE: ADULT_AE
Feature → index:
{'educationnum': 0, 'workclass': 1, 'occupation': 2, 'hoursperweek': 3, 'capitalgain': 4, 'capitalloss': 5, 'maritalstatus': 6}

Child → Parents (index form):
{2: [0, 1, 3], 3: [1, 4], 6: [4, 3]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
WARNING:tensorflow:AutoGraph could not transform <bound method PrototypeLatentCF._loss of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f844eff6cd0>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <bound method PrototypeLatentCF._loss of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f844eff6cd0>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[0 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 0
 0 1 0 0 0 1 1 1 1 1 1 1 1]
[0 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 0
 0 1 0 0 0 1 1 1 1 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (9, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.314592901318092 3.434120781654731
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.4324199818818868 2.8115650396187726
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (39, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.1022187906975534 3.6568320135173646
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.1022187906975534 2.4543933224313683 3.6568320135173646 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1
 0 1 1 0 0 1 1 1 0 1 1 1 1]
[0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1
 0 1 1 0 0 1 1 1 0 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (4, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.5360097335662424 2.7955434291886867
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.314592901318092 3.434120781654731
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (6, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.491099658646859 3.0257633801070156
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (30, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.2149804158811293 3.203254139037041
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.2149804158811293 2.283093524538214 3.434120781654731 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 1]
[1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (4, 32)
X_ shape: (463, 32)
lof_cf min/max: 2.3851305619000716 3.267899824341047
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (13, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.2577418506629214 2.940603989691679
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (3, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.9249535470231927 2.849681161968911
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (30, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.2107869743228528 3.158711044568697
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.2107869743228528 2.233485651839145 3.267899824341047 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 0 0 1
 0 1 1 1 1 1 0 1 1 0 1 1 1]
[0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 0 0 1
 0 1 1 1 1 1 0 1 1 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (2, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.5360097335662424 2.3963115483143613
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (8, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.2584246864975919 2.8343241824361893
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.7689074636477655 2.368607950778985
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (36, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.1909344424307167 3.377396611981351
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.1909344424307167 2.089274070092654 3.377396611981351 50
2/2 [==============================] - 0s 4ms/step
[1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0
 0 1 0 0 1 0 1 1 1 1 0 1 1]
[1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0
 0 1 0 0 1 0 1 1 1 1 0 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (2, 32)
X_ shape: (463, 32)
lof_cf min/max: 2.256724819254174 2.8133232815765497
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (12, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.7437889923793481 3.107748209212186
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (1, 32)
X_ shape: (698, 32)
lof_cf min/max: 3.605817690273221 3.605817690273221
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (35, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.3709063153987286 3.395435920468847
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.3709063153987286 2.541941578671901 3.605817690273221 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype D (2/5)
********************************************************************************************************************************************************************************************************



Reading data
sex
1    20380
0     9782
Name: count, dtype: int64
race
1    25933
0     4229
Name: count, dtype: int64

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:112: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:113: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["race"]))

----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 15016
Positive class (>50K): 7508.0
Context 'sex=Male': 10996
Context 'race=White': 13129
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 dense (Dense)               (None, 64)                512

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,266
Trainable params: 34,498
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: ADULT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 model_1 (Functional)        (None, 16)                4640

 model_2 (Functional)        (None, 7)                 4631

=================================================================
Total params: 9,271
Trainable params: 9,271
Non-trainable params: 0
_________________________________________________________________
restoring weights of model AE: ADULT_AE

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Feature → index:
{'educationnum': 0, 'workclass': 1, 'occupation': 2, 'hoursperweek': 3, 'capitalgain': 4, 'capitalloss': 5, 'maritalstatus': 6}

Child → Parents (index form):
{2: [0, 1, 3], 3: [1, 4], 6: [4, 3]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 0
 0 1 0 0 0 1 1 1 1 1 1 1 1]
[0 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 0
 0 1 0 0 0 1 1 1 1 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (9, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.389037748810018 3.0692014669033973
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.9306545088889726 2.9113976036382416
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (39, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.1782456848754723 3.0248885058921617
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.1782456848754723 2.0791989160066517 3.0692014669033973 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1
 0 1 1 0 0 1 1 1 0 1 1 1 1]
[0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1
 0 1 1 0 0 1 1 1 0 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (4, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.2269896219010377 3.079892929922478
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.0728112098919336 2.711155951087626
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (6, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9965046357577445 2.6228468633075743
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (30, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.1959799999910918 3.0014992894047583
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9965046357577445 2.143972972087404 3.079892929922478 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 1]
[1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (4, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.3257826166780002 2.5654772852849876
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (13, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.2444959968384148 2.891049967377228
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (3, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.284691956055229 2.4244424076645448
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (30, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.2211478206871478 2.944162154509362
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.2211478206871478 1.892269886663138 2.944162154509362 50
2/2 [==============================] - 0s 4ms/step
[0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 0 0 1
 0 1 1 1 1 1 0 1 1 0 1 1 1]
[0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 0 0 1
 0 1 1 1 1 1 0 1 1 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (2, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.8236773316596795 2.0486522459468204
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (8, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.392301176725331 2.6315184201926045
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.7773070841762602 2.9138356750342926
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (36, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.1782456848754723 3.3364232284965967
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.1782456848754723 1.883240082639393 3.3364232284965967 50
2/2 [==============================] - 0s 3ms/step
[1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0
 0 1 0 0 1 0 1 1 1 1 0 1 1]
[1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0
 0 1 0 0 1 0 1 1 1 1 0 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (2, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.5500303872558219 3.164159771103206
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (12, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.339181226656059 2.8044742964634213
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (1, 32)
X_ shape: (698, 32)
lof_cf min/max: 2.378657363785091 2.378657363785091
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (35, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.1201586890193298 3.0014992894047583
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.1201586890193298 1.735589271624292 3.164159771103206 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CACTUS (3/5)
********************************************************************************************************************************************************************************************************



Reading data
sex
1    20380
0     9782
Name: count, dtype: int64
race
1    25933
0     4229
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 15016
Positive class (>50K): 7508.0
Context 'sex=Male': 10996
Context 'race=White': 13129
----------------------------------------------------------------------------------------------------




Building model

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:112: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:113: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["race"]))

Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 dense (Dense)               (None, 64)                512

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,266
Trainable params: 34,498
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: ADULT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 7)]          0           []

 model_1 (Functional)           (None, 4)            1444        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 7)            1447        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,901
Trainable params: 2,901
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: ADULT_CACTUS
Feature → index:
{'educationnum': 0, 'workclass': 1, 'occupation': 2, 'hoursperweek': 3, 'capitalgain': 4, 'capitalloss': 5, 'maritalstatus': 6}

Child → Parents (index form):
{2: [0, 1, 3], 3: [1, 4], 6: [4, 3]}
Building model: CondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 7)                 1447

 model (Functional)          (None, 2)                 35266

=================================================================
Total params: 36,713
Trainable params: 0
Non-trainable params: 36,713
_________________________________________________________________
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 4ms/step
[0 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 0
 0 1 0 0 0 1 1 1 1 1 1 1 1]
[1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1
 0 1 0 0 0 0 0 0 1 1 1 1 1]
0.64
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (9, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9780719190453645 1.4817239672929816
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9926604204121091 1.1241241566336915
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (39, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.998271192656278 1.3153804152724873
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9780719190453645 1.0806585009653216 1.4817239672929816 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1
 0 1 1 0 0 1 1 1 0 1 1 1 1]
[1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 1
 1 0 1 0 0 1 1 0 0 0 0 1 1]
0.64
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (4, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.2300779050592683 1.3936694734328974
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9780719190453645 1.2009124360670842
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (6, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9776389266628347 1.237086521579571
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (30, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9816611163556128 1.510619968891171
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9776389266628347 1.13172124455272 1.510619968891171 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 1]
[0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 1 1 1 1
 0 0 0 0 0 0 0 0 0 0 0 1 0]
0.66
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (4, 32)
X_ shape: (463, 32)
lof_cf min/max: 0.9883884605699347 1.243587053994674
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (13, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9800910245800438 1.3882537378819955
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (3, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9809271282245167 1.1675108519289787
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (30, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.998271192656278 1.3071141295907027
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9800910245800438 1.093982231316957 1.3882537378819955 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 0 0 1
 0 1 1 1 1 1 0 1 1 0 1 1 1]
[0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0 1 1 1 0 0 0 0 1
 0 1 1 0 1 1 0 1 1 0 1 1 1]
0.8
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (2, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.2023609907332837 1.3936694734328974
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (8, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9786104169023095 1.2004643010459373
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.981947965344926 1.356651464498932
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (36, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9782848511999442 1.2648335420841554
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9782848511999442 1.0849363418661655 1.3936694734328974 50
2/2 [==============================] - 0s 3ms/step
[1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0
 0 1 0 0 1 0 1 1 1 1 0 1 1]
[1 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 1 1 0
 0 1 0 1 1 0 1 0 0 0 1 1 1]
0.64
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (2, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0716501651444508 1.2801288032493285
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (12, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9897816304949321 1.3614268424127431
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (1, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.174026415597954 1.174026415597954
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (35, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9800506378024586 1.3288519887530728
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9800506378024586 1.080520648161331 1.3614268424127431 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CausalCACTUS (4/5)
********************************************************************************************************************************************************************************************************



Reading data
sex
1    20380
0     9782
Name: count, dtype: int64
race
1    25933
0     4229
Name: count, dtype: int64

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:112: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:113: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["race"]))

----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 15016
Positive class (>50K): 7508.0
Context 'sex=Male': 10996
Context 'race=White': 13129
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 dense (Dense)               (None, 64)                512

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,266
Trainable params: 34,498
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: ADULT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 7)]          0           []

 model_1 (Functional)           (None, 4)            1444        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 7)            1447        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,901
Trainable params: 2,901
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: ADULT_CACTUS
Feature → index:
{'educationnum': 0, 'workclass': 1, 'occupation': 2, 'hoursperweek': 3, 'capitalgain': 4, 'capitalloss': 5, 'maritalstatus': 6}

Child → Parents (index form):
{2: [0, 1, 3], 3: [1, 4], 6: [4, 3]}
Building model: CausalCondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 7)                 1447

 model (Functional)          (None, 2)                 35266

=================================================================
Total params: 36,713
Trainable params: 0
Non-trainable params: 36,713
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 0
 0 1 0 0 0 1 1 1 1 1 1 1 1]
[1 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 0 0 0 1
 0 1 0 0 0 1 0 1 1 1 1 1 1]
0.88
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (9, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9780719190453645 1.4116355596065262
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9722499693234254 1.0048765877476893
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (39, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9791670168362046 1.3936012560870616
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9722499693234254 1.038896229549707 1.4116355596065262 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1
 0 1 1 0 0 1 1 1 0 1 1 1 1]
[0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 1 1 1 0 1 0 0 1 1 0 0 1 0 0 0
 0 1 1 0 0 1 1 1 0 1 1 1 1]
0.9
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (4, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.1568720178953453 1.3039197124573785
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9762042290204545 1.3563947285674647
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (6, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9787978058206358 1.2154663616676444
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (30, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9781479283495539 1.4299586841566105
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9762042290204545 1.0252244377878692 1.4299586841566105 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 1]
[1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 1 0 1
 0 0 0 0 0 0 0 0 0 0 0 1 1]
0.88
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (4, 32)
X_ shape: (463, 32)
lof_cf min/max: 0.9890072166832654 1.2758551374061162
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (13, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9793323435525605 1.3784375811229914
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (3, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9747088363945007 1.0223737937892714
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (30, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9795715775535906 1.1612250833599171
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9747088363945007 1.0208230483149898 1.3784375811229914 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 0 0 1
 0 1 1 1 1 1 0 1 1 0 1 1 1]
[0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 0 0 1
 0 1 1 1 1 1 0 1 1 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (2, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0259668528974946 1.1568720178953453
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (8, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9804326350051373 1.3993544917100327
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9792606872806437 1.3830180562252563
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (36, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9789553412679304 1.3271809995155175
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9789553412679304 1.0358830517441877 1.3993544917100327 50
2/2 [==============================] - 0s 3ms/step
[1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0
 0 1 0 0 1 0 1 1 1 1 0 1 1]
[1 1 0 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 1 0 1 1 0 0 1 1 0
 0 1 0 0 1 0 1 1 1 0 1 1 1]
0.92
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (2, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0954113166082757 1.2106403492019133
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (12, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9844670521418161 1.3614268424127431
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (1, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.1791213419998832 1.1791213419998832
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (35, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9794401662115693 1.3167857594632721
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9794401662115693 1.0379859448226685 1.3614268424127431 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
            Model Dataset      CFMethod                Metric  Value
0      LatentCF++   ADULT    LatentCFpp             proximity  1.399
1      LatentCF++   ADULT    LatentCFpp           n_proximity  0.529
2      LatentCF++   ADULT    LatentCFpp              validity  0.980
3      LatentCF++   ADULT    LatentCFpp           compactness  0.400
4      LatentCF++   ADULT    LatentCFpp           lof_context  1.112
..            ...     ...           ...                   ...    ...
220  CausalCACTUS   ADULT  CausalCACTUS           lof_context  1.087
221  CausalCACTUS   ADULT  CausalCACTUS  causal_validity_hard  0.840
222  CausalCACTUS   ADULT  CausalCACTUS  causal_validity_soft  0.947
223  CausalCACTUS   ADULT  CausalCACTUS    causal_compact_val  0.489
224  CausalCACTUS   ADULT  CausalCACTUS       inlier_fraction  1.000

[225 rows x 5 columns]

In [8]:
child_to_parents_dict

{2: [0, 1, 3], 3: [1, 4], 6: [4, 3]}

In [9]:
# Pivoting the dataframe
df_metrics_pivot = df_metrics.pivot_table(
    index=["Dataset", "Model"],
    columns="Metric",
    values="Value",
    aggfunc=['mean', 'std']
)

desired_order = [
    "validity",
    "lof_context",
    "compactness",
    "n_proximity",
    "causal_validity_hard",
    "causal_validity_soft",
    "causal_compact_val",
    "inlier_fraction"
]
df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)
df_metrics_pivot = df_metrics_pivot[desired_order]

df_metrics_pivot.rename(
    columns={
        "validity": "Validity",
        "lof_context": "LOF",
        "compactness": "Compactness",
        "n_proximity": "Proximity",
        "causal_validity_hard": "Causal Validity (Hard)",
        "causal_validity_soft": "Causal Validity (Soft)",
        "causal_compact_val": "Causal Compact Validity",
        "inlier_fraction": "inlier_fraction"
    },
    inplace=True
)

df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)

# df_formatted = df_metrics_pivot.apply(
#     lambda x: x["mean"].map("${:2.2f}".format)
#     + " \\pm "
#     + x["std"].map("{:2.2f} $".format),
#     axis=1
# )
# df_formatted

df_formatted = df_metrics_pivot.apply(
    lambda x: (
        x["mean"].round(2).astype(str)
        + " ± "
        + x["std"].round(2).astype(str)
    ),
    axis=1
)
df_formatted

Metric                   Validity          LOF  Compactness    Proximity  \
Dataset Model
ADULT   CACTUS        0.68 ± 0.07  1.12 ± 0.01  0.33 ± 0.03  0.65 ± 0.02
        CausalCACTUS  0.92 ± 0.05  1.08 ± 0.01  0.47 ± 0.03  0.59 ± 0.03
        LatentCF++    0.99 ± 0.02  1.13 ± 0.01  0.36 ± 0.03   0.6 ± 0.09
        Prototype C     1.0 ± 0.0  2.29 ± 0.15  0.06 ± 0.01  2.83 ± 0.13
        Prototype D     1.0 ± 0.0   2.01 ± 0.1  0.07 ± 0.01  2.57 ± 0.11

Metric               Causal Validity (Hard) Causal Validity (Soft)  \
Dataset Model
ADULT   CACTUS                  0.95 ± 0.02            0.98 ± 0.01
        CausalCACTUS            0.92 ± 0.06            0.97 ± 0.02
        LatentCF++               1.0 ± 0.01              1.0 ± 0.0
        Prototype C               1.0 ± 0.0              1.0 ± 0.0
        Prototype D               1.0 ± 0.0              1.0 ± 0.0

Metric               Causal Compact Validity inlier_fraction
Dataset Model
ADULT   CACTUS                   0.34 ± 0.03       1.0 ± 0.0
        CausalCACTUS             0.48 ± 0.03       1.0 ± 0.0
        LatentCF++               0.33 ± 0.04     0.99 ± 0.01
        Prototype C              0.07 ± 0.02      0.1 ± 0.09
        Prototype D              0.08 ± 0.01     0.17 ± 0.07

In [10]:
# # self.actionable_vars
# """
# "educationnum", "workclass", "occupation", "hoursperweek", "capitalgain", "capitalloss", "maritalstatus"
# """

print(data.scaler_inverse_transform(X_test))
print(data.scaler_inverse_transform(X_cf))

[[   10     2    13    48     0     0     0]
 [   13     2    12    45     0     0     4]
 [   14     2    11    40     0     0     2]
 [   13     2    11    60     0     0     2]
 [   10     2     9    54     0     0     5]
 [   14     2     3    50     0     0     2]
 [   10     2    11    50     0     0     2]
 [   10     2     2    40     0     0     2]
 [   13     2     0    40     0     0     4]
 [   10     3    11    60     0     0     2]
 [   10     2     9    40     0     0     2]
 [   13     5     9    45     0     0     2]
 [   15     3     3    55     0  2415     2]
 [   10     2     0    40     0     0     6]
 [    9     2     0    35     0     0     4]
 [    9     2     2    40     0     0     4]
 [    9     2     7    40     0     0     4]
 [   13     2     3    40     0     0     4]
 [    6     2     5    40     0     0     0]
 [   13     2     9    50     0  1485     2]
 [   15     3     9    55     0     0     2]
 [   12     2    12    40 14344     0     4]
 [    9     4     9    60     0     0     2]
 [    7     2     5    40  7688     0     2]
 [   15     2     9    30     0     0     2]
 [    2     2    11    50     0     0     2]
 [   15     4     9    50 99999     0     2]
 [    9     2     9    10     0     0     2]
 [    9     2     7    25     0     0     4]
 [   11     2    12    43     0     0     2]
 [    9     0     7    32     0     0     4]
 [    9     1    10    40     0     0     6]
 [   14     1     9    40     0     0     2]
 [   10     2    11    40     0     0     2]
 [    9     2     2    40     0     0     2]
 [   10     2     0    25     0     0     4]
 [   13     3     4    40     0     0     2]
 [   13     2     0    44  5178     0     2]
 [    9     2     7     4     0     0     2]
 [   11     2     2    40     0     0     2]
 [   13     2     0    40     0     0     2]
 [    9     2     0    30     0     0     4]
 [    9     3     3    40     0     0     2]
 [   10     2     9    25     0     0     2]
 [    9     2     2    28     0     0     0]
 [   10     2     7    16     0     0     4]
 [    6     2     0    70     0     0     0]
 [   13     1     9    75 99999     0     2]
 [    7     2     8    75     0     0     4]
 [    9     2     0    30     0     0     4]]
[[   11     2    13    54  1082   173     0]
 [   14     3    12    51  3793    42     4]
 [   12     3    11    40   462     0     2]
 [   10     2    11    41   209     0     3]
 [   14     2     9    46 15106     0     4]
 [   11     2     4    42   275     0     3]
 [    8     2    11    53   226     0     2]
 [    9     2     2    39   760     0     2]
 [   14     2     0    41 10232    71     4]
 [    9     4    11    62   589     0     2]
 [    9     2     8    47     0    20     2]
 [   12     5     9    47     0    36     3]
 [   15     3     3    55     0  2415     2]
 [   13     2     1    39  1644    55     6]
 [    8     3     0    43   157     0     2]
 [   11     2     2    37   683     0     2]
 [   12     2     8    41     0     0     2]
 [   13     2     3    50  1073     0     4]
 [   12     3     5    54  1032    87     0]
 [   10     2     8    47     0  1601     2]
 [   10     4     8    61   519     0     2]
 [   12     2    12    37    77     0     3]
 [   10     4     9    60   309     0     2]
 [    8     2     5    40   121     0     2]
 [   13     2     9    43   359    19     3]
 [    8     2    11    53   181     0     2]
 [   15     4     9    50 99999     0     2]
 [   10     1     9    28     0    15     2]
 [   14     2     7    41 10731     0     3]
 [    8     2    12    45   197     0     2]
 [   14     1     7    33 10363     0     3]
 [   14     3    12    43   227     0     6]
 [   11     2     9    35     0     0     2]
 [    8     2    11    43     0     0     2]
 [    9     2     2    43   828     0     2]
 [   13     3     0    24 12041    24     3]
 [   12     4     4    43   971     0     2]
 [   13     2     0    44  1019    59     3]
 [   11     1     8    32     0    23     2]
 [   10     2     2    38   735     0     2]
 [   11     1     0    36   470     0     2]
 [    9     2     0    31     0     0     2]
 [    9     3     3    42   771     0     2]
 [   10     2     9    36     0     0     2]
 [   10     2     2    45  1222    65     0]
 [   14     2     8    43  4830     0     4]
 [    6     2     0    70     0     0     0]
 [   13     1     9    75 99999     0     2]
 [    9     3     8    51     0     0     2]
 [    9     2     0    31     0     0     2]]

In [11]:
# self.features_lbls = [
#     "educationnum",
#     "workclass",
#     "occupation",
#     "hoursperweek",
#     "capitalgain",
#     "capitalloss",
#     "maritalstatus"
# ]
cat_idx = [1, 2, 6] #     "workclass", "occupation", "maritalstatus"
num_idx = [0, 3, 4, 5]

X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])

# --- CF evaluation ---
cf_scores, cf_scores_labels = cf_eval(
    data.X_train, # previous name: data.X_train
    context_training, # previous name: context_training,
    X_test, # previous name: x,
    X_cf, # previous name: cf_x, 
    y_original_labels, # previous name: y_,
    context_test, # previous name: context,
    y_cf_labels, # previous name: cf_y_
    data.scaler_inverse_transform(X_test),
    data.scaler_inverse_transform(X_cf),
    child_to_parents_dict,
    cat_idx,
    num_idx
)

print(cf_scores, cf_scores_labels)

[1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0
 0 1 0 0 1 0 1 1 1 1 0 1 1]
[1 1 0 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 1 0 1 1 0 0 1 1 0
 0 1 0 0 1 0 1 1 1 0 1 1 1]
0.92
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (2, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0954113166082757 1.2106403492019133
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (12, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9844670521418161 1.3614268424127431
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (1, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.1791213419998832 1.1791213419998832
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (35, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9794401662115693 1.3167857594632721
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9794401662115693 1.0379859448226685 1.3614268424127431 50
[1.5020299828076222, 0.5677139708959416, 0.92, 0.49142857142857144, 1.087172397588258, 0.84, 0.9466666666666665, 0.4885714285714285, 1.0] ['proximity', 'n_proximity', 'validity', 'compactness', 'lof_context', 'causal_validity_hard', 'causal_validity_soft', 'causal_compact_val', 'inlier_fraction']

## Graph 2 (Moderate priors)

In [12]:
N = 50 # TODO: rerun: unscaled LOF
N_BOOTSTRAP = 5
# SEED_list = [23] * N_BOOTSTRAP
SEED_list = [11, 22, 33, 44, 55]

# Number of samples to compute the metrics for CF evaluation
METRICS = []

for i, exp in enumerate(EXP):
    print("\n" * 2)
    print("*" * 200)
    print(f"Running exp: {exp['name']} ({i}/{len(EXP)})")
    print("*" * 200)
    print("\n" * 2)
    
    # Reading the data
    CLASS_CONFIG_PATH = exp["classifier"]
    AE_CONFIG_PATH = exp["AE"]

    class_config = get_exp_config(CLASS_CONFIG_PATH)
    print("Reading data")
    data = getData(class_config)

    # Getting classifier
    classifier = modelGen(class_config["type"], data, params=class_config, debug=True)
    classifier.load()

    # Getting AE-based Model
    AE_config = get_exp_config(AE_CONFIG_PATH)
    aeModel = modelGen(AE_config["type"], data, params=AE_config, debug=True)
    aeModel.load()

    # CF generation
    child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
        data.features_lbls,
        # TODO: change the string below for graph_str1 and graph_str2
        graph_str2
    )
    print("Feature → index:")
    print(feat2idx)
    print("\nChild → Parents (index form):")
    print(child_to_parents_dict)
    
    if exp["name"] == "CausalCACTUS":
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train,
            x_min=data.X_train.min(axis=0),
            x_max=data.X_train.max(axis=0),
            causal_index_map=child_to_parents_dict
        )
    else:
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train
        )

    for trial in range(N_BOOTSTRAP):

        # --- Sampling test data ---
        SEED = SEED_list[trial]
        os.environ['PYTHONHASHSEED'] = str(SEED)
        random.seed(SEED)
        np.random.seed(SEED)
        tf_random.set_seed(SEED)
        rand_idx = np.random.choice(len(data.X_test), N, replace=True)
        
        # previous name: x
        X_test = data.X_test[rand_idx, ...]
        # previous name: contest
        context_test = data.context_test[exp['context']].values
        context_test = context_test[rand_idx, ...]

        context_training = data.context_train[exp['context']].values

        # previous name: y
        y_test = np.argmax(data.y_test[rand_idx, ...], axis=1)
        y_original_logits = classifier.predict(X_test)
        # previous name: y_
        y_original_labels = np.argmax(y_original_logits, axis=1)

        # --- CF generation ---
        # previous names: 
        # cf_x, cf_y_, x, __
        X_cf, y_cf_labels, X_internal, y_internal = CF_method.transform(
            X_test,
            y_original_labels,
            target_context=context_test,
            verbose=0
        )              

        # TODO: One-hot encoding for Adult
        # self.features_lbls = [
        #     "educationnum",
        #     "workclass",
        #     "occupation",
        #     "hoursperweek",
        #     "capitalgain",
        #     "capitalloss",
        #     "maritalstatus"
        # ]
        cat_idx = [1, 2, 6] #     "workclass", "occupation", "maritalstatus"
        num_idx = [0, 3, 4, 5]
        X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])
        
        # --- CF evaluation ---
        cf_scores, cf_scores_labels = cf_eval(
            data.X_train, # previous name: data.X_train
            context_training, # previous name: context_training,
            X_test, # previous name: x,
            X_cf, # previous name: cf_x, 
            y_original_labels, # previous name: y_,
            context_test, # previous name: context,
            y_cf_labels, # previous name: cf_y_
            data.scaler_inverse_transform(X_test),
            data.scaler_inverse_transform(X_cf),
            child_to_parents_dict, 
            cat_idx,
            num_idx
        )

        for i_metric, label in enumerate(cf_scores_labels):
            METRICS.append([
                exp["name"],
                exp["data"],
                exp["CFmethod"],
                label,
                cf_scores[i_metric]
            ])

    # Cleaning GPU models
    cleanup_gpu()

# --- Metrics aggregation ---
df_metrics = pd.DataFrame(
    data=METRICS,
    columns=["Model", "Dataset", "CFMethod", "Metric", "Value"]
)
df_metrics = df_metrics.round(3)
print(df_metrics)

********************************************************************************************************************************************************************************************************
Running exp: LatentCF++ (0/5)
********************************************************************************************************************************************************************************************************



Reading data
sex
1    20380
0     9782
Name: count, dtype: int64
race
1    25933
0     4229
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 15016
Positive class (>50K): 7508.0
Context 'sex=Male': 10996
Context 'race=White': 13129
----------------------------------------------------------------------------------------------------




Building model

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:112: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:113: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["race"]))

Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 dense (Dense)               (None, 64)                512

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,266
Trainable params: 34,498
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: ADULT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 model_1 (Functional)        (None, 16)                4640

 model_2 (Functional)        (None, 7)                 4631

=================================================================
Total params: 9,271
Trainable params: 9,271
Non-trainable params: 0
_________________________________________________________________
restoring weights of model AE: ADULT_AE

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Feature → index:
{'educationnum': 0, 'workclass': 1, 'occupation': 2, 'hoursperweek': 3, 'capitalgain': 4, 'capitalloss': 5, 'maritalstatus': 6}

Child → Parents (index form):
{3: [1, 4], 2: [1, 4, 3]}
Building model: latentCF [CF]
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 16)]              0

 model_2 (Functional)        (None, 7)                 4631

 model (Functional)          (None, 2)                 35266

=================================================================
Total params: 39,897
Trainable params: 39,129
Non-trainable params: 768
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1
 0 0 1 0 0 1 1 1 1 1 1 0 0]
[0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1
 0 0 1 0 0 1 1 1 1 1 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.145929556360847 1.1894382490504538
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.984365170289657 1.2384196405014845
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.0188346724011779 1.2030836713778672
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (35, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9816881235695095 2.011250665471431
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9816881235695095 1.0603451500312058 2.011250665471431 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 0 1 1 0 1 0 0 0]
[1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 0 1 1 0 1 0 0 0]
0.98
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (1, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.247148315752875 1.247148315752875
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (6, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9875348419541874 1.545523844195504
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (3, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.0100483711964896 1.1840278511186508
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (40, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9860893744233266 1.3539812195711092
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9860893744233266 1.0924175304504615 1.545523844195504 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 1
 1 1 0 1 0 1 1 1 0 0 1 1 0]
[1 0 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 1
 1 1 0 1 0 1 1 1 0 0 1 1 1]
0.98
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0244155166277857 1.2196607672650839
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9853208890158157 1.272433788704896
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.016088568748688 4.617506002589126
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (33, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9864943500512878 1.3843266089668285
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9853208890158157 1.1415481192064938 4.617506002589126 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 1 1 1
 1 1 0 0 0 0 1 0 0 1 0 0 1]
[1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 1 1 1
 1 1 0 0 0 0 1 0 0 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (1, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.371742197762137 1.371742197762137
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (5, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.030089532747668 1.7322153694696119
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.0119371248002584 1.1322660946865346
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (42, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9808038612402541 1.537685654275024
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9808038612402541 1.0752190600876979 1.7322153694696119 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0
 1 0 1 0 1 1 0 1 1 1 0 0 1]
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0
 1 0 1 0 1 1 0 1 1 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.146134350534839 1.2018276266975725
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.0198991956504155 1.2733476456427288
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.0305967470270097 1.1835145155900426
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (33, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9862707958662007 1.5634270797697156
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9862707958662007 1.118674060756904 1.5634270797697156 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype C (1/5)
********************************************************************************************************************************************************************************************************



Reading data
sex
1    20380
0     9782
Name: count, dtype: int64
race
1    25933
0     4229
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 15016
Positive class (>50K): 7508.0
Context 'sex=Male': 10996
Context 'race=White': 13129
----------------------------------------------------------------------------------------------------




Building model

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:112: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:113: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["race"]))

Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 dense (Dense)               (None, 64)                512

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,266
Trainable params: 34,498
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: ADULT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 model_1 (Functional)        (None, 16)                4640

 model_2 (Functional)        (None, 7)                 4631

=================================================================
Total params: 9,271
Trainable params: 9,271
Non-trainable params: 0
_________________________________________________________________
restoring weights of model AE: ADULT_AE

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Feature → index:
{'educationnum': 0, 'workclass': 1, 'occupation': 2, 'hoursperweek': 3, 'capitalgain': 4, 'capitalloss': 5, 'maritalstatus': 6}

Child → Parents (index form):
{3: [1, 4], 2: [1, 4, 3]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1
 0 0 1 0 0 1 1 1 1 1 1 0 0]
[0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1
 0 0 1 0 0 1 1 1 1 1 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.4790804417450734 2.8133232815765497
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.314592901318092 3.4606751151998902
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.5322807247531942 2.988290036933394
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (35, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.1489033519123046 3.25498121026793
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.1489033519123046 2.3170810599019473 3.4606751151998902 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 0 1 1 0 1 0 0 0]
[1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 0 1 1 0 1 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (1, 32)
X_ shape: (463, 32)
lof_cf min/max: 3.0678796927863794 3.0678796927863794
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (6, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.5708395243699136 2.668850803281697
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (3, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.3707594554603508 2.8115650396187726
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (40, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.17640872003961 3.4966258814925326
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.17640872003961 2.393751670814122 3.4966258814925326 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 1
 1 1 0 1 0 1 1 1 0 0 1 1 0]
[1 0 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 1
 1 1 0 1 0 1 1 1 0 0 1 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.313490783107518 3.6336273993309085
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.314592901318092 3.496650370076987
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.7944135087996067 2.473075306072937
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (33, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.2812490634393106 3.35726657162224
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.2812490634393106 2.1289882615548796 3.6336273993309085 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 1 1 1
 1 1 0 0 0 0 1 0 0 1 0 0 1]
[1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 1 1 1
 1 1 0 0 0 0 1 0 0 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (1, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.8323187944984152 1.8323187944984152
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (5, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.538502639994075 3.463496521413538
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 2.2967902108779654 2.5949106839246436
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (42, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.2149804158811293 3.1515189452469894
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.2149804158811293 2.128211254433773 3.463496521413538 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0
 1 0 1 0 1 1 0 1 1 1 0 0 1]
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0
 1 0 1 0 1 1 0 1 1 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.4658173535555032 2.3687983148566376
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.3743280233402537 2.940603989691679
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.6022775860251985 2.5066301660819446
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (33, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.0815824798046731 3.3983179004147632
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.0815824798046731 2.2277891601294852 3.3983179004147632 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype D (2/5)
********************************************************************************************************************************************************************************************************



Reading data
sex
1    20380
0     9782
Name: count, dtype: int64
race
1    25933
0     4229
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 15016
Positive class (>50K): 7508.0
Context 'sex=Male': 10996
Context 'race=White': 13129
----------------------------------------------------------------------------------------------------




Building model

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:112: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:113: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["race"]))

Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 dense (Dense)               (None, 64)                512

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,266
Trainable params: 34,498
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: ADULT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 model_1 (Functional)        (None, 16)                4640

 model_2 (Functional)        (None, 7)                 4631

=================================================================
Total params: 9,271
Trainable params: 9,271
Non-trainable params: 0
_________________________________________________________________
restoring weights of model AE: ADULT_AE

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Feature → index:
{'educationnum': 0, 'workclass': 1, 'occupation': 2, 'hoursperweek': 3, 'capitalgain': 4, 'capitalloss': 5, 'maritalstatus': 6}

Child → Parents (index form):
{3: [1, 4], 2: [1, 4, 3]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1
 0 0 1 0 0 1 1 1 1 1 1 0 0]
[0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1
 0 0 1 0 0 1 1 1 1 1 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.5500303872558219 2.128564946353139
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.336103795122755 2.711155951087626
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.2734742408845918 1.8857679400501914
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (35, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.2064886678932756 3.1495644180757627
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.2064886678932756 2.0670811068497543 3.1495644180757627 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 0 1 1 0 1 0 0 0]
[1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 0 1 1 0 1 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (1, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.5754745377548616 1.5754745377548616
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (6, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.1310709185935857 2.545590723227454
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (3, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.4630062618624442 2.9113976036382416
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (40, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.2070077368137233 3.1261626903167237
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.1310709185935857 2.1572959312232003 3.1261626903167237 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 1
 1 1 0 1 0 1 1 1 0 0 1 1 0]
[1 0 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 1
 1 1 0 1 0 1 1 1 0 0 1 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.4126257988523152 2.0388567535608377
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.3470234721224215 2.9498259723725244
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.4562617367089041 2.91019454438291
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (33, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.0491134626899703 3.1187026285717683
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.0491134626899703 1.9498556153407445 3.1187026285717683 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 1 1 1
 1 1 0 0 0 0 1 0 0 1 0 0 1]
[1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 1 1 1
 1 1 0 0 0 0 1 0 0 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (1, 32)
X_ shape: (463, 32)
lof_cf min/max: 2.1511921144542274 2.1511921144542274
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (5, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.4876793824732908 2.980185410145144
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.0541645316691832 1.4728760503440952
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (42, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.2685725463072395 3.1221775240145146
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.0541645316691832 1.9345334081675598 3.1221775240145146 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0
 1 0 1 0 1 1 0 1 1 1 0 0 1]
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0
 1 0 1 0 1 1 0 1 1 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.5722578299357934 2.862285202256576
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.1874912727781506 2.9249073468259574
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.3776541501939144 1.8896118602645744
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (33, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.1063325981709176 3.210175082807803
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.1063325981709176 1.7449146066651573 3.210175082807803 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CACTUS (3/5)
********************************************************************************************************************************************************************************************************



Reading data
sex
1    20380
0     9782
Name: count, dtype: int64
race
1    25933
0     4229
Name: count, dtype: int64

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:112: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:113: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["race"]))

----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 15016
Positive class (>50K): 7508.0
Context 'sex=Male': 10996
Context 'race=White': 13129
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 dense (Dense)               (None, 64)                512

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,266
Trainable params: 34,498
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: ADULT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 7)]          0           []

 model_1 (Functional)           (None, 4)            1444        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 7)            1447        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,901
Trainable params: 2,901
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: ADULT_CACTUS
Feature → index:
{'educationnum': 0, 'workclass': 1, 'occupation': 2, 'hoursperweek': 3, 'capitalgain': 4, 'capitalloss': 5, 'maritalstatus': 6}

Child → Parents (index form):
{3: [1, 4], 2: [1, 4, 3]}
Building model: CondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 7)                 1447

 model (Functional)          (None, 2)                 35266

=================================================================
Total params: 36,713
Trainable params: 0
Non-trainable params: 36,713
_________________________________________________________________
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 4ms/step
[0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1
 0 0 1 0 0 1 1 1 1 1 1 0 0]
[0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1
 0 0 1 0 0 1 0 0 0 0 0 0 1]
0.68
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0716501651444508 1.4818479080483975
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9780719190453645 1.2009124360670842
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.0566791517567602 1.1743634492248363
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (35, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9804691022807579 1.3222242020379626
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9780719190453645 1.0640755951585985 1.4818479080483975 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 0 1 1 0 1 0 0 0]
[1 0 0 0 0 1 0 1 1 1 0 1 0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0
 0 0 1 0 0 0 1 1 1 0 0 0 0]
0.72
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (1, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0039378465948963 1.0039378465948963
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (6, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9726630109706204 1.3151736019177889
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (3, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.0051428831045792 1.1698453118795935
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (40, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9815965614946084 1.3354620574478382
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9726630109706204 1.0750331981953454 1.3354620574478382 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 1
 1 1 0 1 0 1 1 1 0 0 1 1 0]
[1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 1 0 0 0 0 0 1]
0.6
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0176928312490654 1.2904891728791146
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.97560957157667 1.2174235962480051
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9963333683933695 3.363349676927511
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (33, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9935036630109412 1.3233194951775595
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.97560957157667 1.0963934827559019 3.363349676927511 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 1 1 1
 1 1 0 0 0 0 1 0 0 1 0 0 1]
[0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 1 0 1
 1 1 0 0 0 0 1 0 0 1 0 0 1]
0.78
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (1, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.1322458871310108 1.1322458871310108
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (5, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.006568852482159 1.2273261502853754
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.116703426744831 1.1786597175090932
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (42, 32)
X_ shape: (4008, 32)
lof_cf min/max: 1.0026406755166073 1.4430351502056906
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
1.0026406755166073 1.0875322088357247 1.4430351502056906 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0
 1 0 1 0 1 1 0 1 1 1 0 0 1]
[0 1 0 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1
 0 0 1 0 0 0 0 1 0 1 0 1 1]
0.74
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0951355204122588 1.243995916817747
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9734618973104352 1.242629451914041
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.1261999868106585 1.2539805482769342
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (33, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9848561878159324 1.2525433198258349
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9734618973104352 1.1142752356606405 1.2539805482769342 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CausalCACTUS (4/5)
********************************************************************************************************************************************************************************************************



Reading data
sex
1    20380
0     9782
Name: count, dtype: int64
race
1    25933
0     4229
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 15016
Positive class (>50K): 7508.0
Context 'sex=Male': 10996
Context 'race=White': 13129
----------------------------------------------------------------------------------------------------




Building model

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:112: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Adult.py:113: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["race"]))

Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 7)]               0

 dense (Dense)               (None, 64)                512

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,266
Trainable params: 34,498
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: ADULT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 7)]          0           []

 model_1 (Functional)           (None, 4)            1444        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 7)            1447        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,901
Trainable params: 2,901
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: ADULT_CACTUS
Feature → index:
{'educationnum': 0, 'workclass': 1, 'occupation': 2, 'hoursperweek': 3, 'capitalgain': 4, 'capitalloss': 5, 'maritalstatus': 6}

Child → Parents (index form):
{3: [1, 4], 2: [1, 4, 3]}
Building model: CausalCondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 7)                 1447

 model (Functional)          (None, 2)                 35266

=================================================================
Total params: 36,713
Trainable params: 0
Non-trainable params: 36,713
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
[0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1
 0 0 1 0 0 1 1 1 1 1 1 0 0]
[0 0 1 0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 0 1 0 0 1 1 0 1 0 1 0 1 1 0
 0 0 1 0 0 1 0 0 0 0 1 0 1]
0.7
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0897336121893433 1.1603896399836826
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9762042290204545 1.3626302604159977
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.0398294462813626 1.1289326666774318
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (35, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9783706703535558 1.3222242020379626
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9762042290204545 1.0374130394461711 1.3626302604159977 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 0 1 1 0 1 0 0 0]
[1 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0]
0.76
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (1, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.1067274510640732 1.1067274510640732
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (6, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9837234353152459 1.5651514000107307
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (3, 32)
X_ shape: (698, 32)
lof_cf min/max: 1.0039833107729872 1.049682945320463
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (40, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9796452109178883 1.3184600278008767
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9796452109178883 1.0284414957675725 1.5651514000107307 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 1
 1 1 0 1 0 1 1 1 0 0 1 1 0]
[1 0 0 1 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 1
 1 0 0 1 0 1 0 1 0 0 1 1 1]
0.8
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.0213094145251365 1.1010925430936214
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9762042290204545 1.356632405221199
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9805025914237778 3.363349676927511
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (33, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9811267298824575 1.2774522604082377
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9762042290204545 1.0267991932234941 3.363349676927511 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 1 1 1
 1 1 0 0 0 0 1 0 0 1 0 0 1]
[1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 0 0 0 1 0 0 1 0 0 1]
0.92
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (1, 32)
X_ shape: (463, 32)
lof_cf min/max: 1.159023128064207 1.159023128064207
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (5, 32)
X_ shape: (1685, 32)
lof_cf min/max: 1.0026587559360187 1.5513023363266292
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (2, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.971406776319656 1.0177988428326625
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (42, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9786120813738961 1.1932111903221638
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.971406776319656 1.022694848800087 1.5513023363266292 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0
 1 0 1 0 1 1 0 1 1 1 0 0 1]
[1 0 0 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 1
 0 0 1 0 1 1 0 1 1 1 0 1 1]
0.84
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 586
Unique rows: 463
After np.unique(): subset size: 463
cf_samples_ shape: (3, 32)
X_ shape: (463, 32)
lof_cf min/max: 0.9813191431679352 1.1484253165494402
lof_train min/max: 0.9607420081499042 3.8237559974730537
mean train LOF: 1.0990765555438358
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 2643
Unique rows: 1685
After np.unique(): subset size: 1685
cf_samples_ shape: (10, 32)
X_ shape: (1685, 32)
lof_cf min/max: 0.9738300570679033 1.4944933584919113
lof_train min/max: 0.971333142018786 3.581064342213689
mean train LOF: 1.0679051195043303
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 942
Unique rows: 698
After np.unique(): subset size: 698
cf_samples_ shape: (4, 32)
X_ shape: (698, 32)
lof_cf min/max: 0.9855121351868751 1.1117434858743005
lof_train min/max: 0.9632347814799089 3.378928094406576
mean train LOF: 1.078076412326804
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 7841
Unique rows: 4008
After np.unique(): subset size: 4008
cf_samples_ shape: (33, 32)
X_ shape: (4008, 32)
lof_cf min/max: 0.9785667133164476 1.372747829652347
lof_train min/max: 0.9650715464335687 1.9025903028583988
mean train LOF: 1.0610038163960378
0.9738300570679033 1.0298913094969162 1.4944933584919113 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
            Model Dataset      CFMethod                Metric  Value
0      LatentCF++   ADULT    LatentCFpp             proximity  1.201
1      LatentCF++   ADULT    LatentCFpp           n_proximity  0.454
2      LatentCF++   ADULT    LatentCFpp              validity  1.000
3      LatentCF++   ADULT    LatentCFpp           compactness  0.386
4      LatentCF++   ADULT    LatentCFpp           lof_context  1.114
..            ...     ...           ...                   ...    ...
220  CausalCACTUS   ADULT  CausalCACTUS           lof_context  1.076
221  CausalCACTUS   ADULT  CausalCACTUS  causal_validity_hard  0.880
222  CausalCACTUS   ADULT  CausalCACTUS  causal_validity_soft  0.940
223  CausalCACTUS   ADULT  CausalCACTUS    causal_compact_val  0.490
224  CausalCACTUS   ADULT  CausalCACTUS       inlier_fraction  0.975

[225 rows x 5 columns]

In [13]:
child_to_parents_dict

{3: [1, 4], 2: [1, 4, 3]}

In [14]:
# Pivoting the dataframe
df_metrics_pivot = df_metrics.pivot_table(
    index=["Dataset", "Model"],
    columns="Metric",
    values="Value",
    aggfunc=['mean', 'std']
)

desired_order = [
    "validity",
    "lof_context",
    "compactness",
    "n_proximity",
    "causal_validity_hard",
    "causal_validity_soft",
    "causal_compact_val",
    "inlier_fraction"
]
df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)
df_metrics_pivot = df_metrics_pivot[desired_order]

df_metrics_pivot.rename(
    columns={
        "validity": "Validity",
        "lof_context": "LOF",
        "compactness": "Compactness",
        "n_proximity": "Proximity",
        "causal_validity_hard": "Causal Validity (Hard)",
        "causal_validity_soft": "Causal Validity (Soft)",
        "causal_compact_val": "Causal Compact Validity",
        "inlier_fraction": "inlier_fraction"
    },
    inplace=True
)

df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)

# df_formatted = df_metrics_pivot.apply(
#     lambda x: x["mean"].map("${:2.2f}".format)
#     + " \\pm "
#     + x["std"].map("{:2.2f} $".format),
#     axis=1
# )
# df_formatted

df_formatted = df_metrics_pivot.apply(
    lambda x: (
        x["mean"].round(2).astype(str)
        + " ± "
        + x["std"].round(2).astype(str)
    ),
    axis=1
)
df_formatted

Metric                   Validity          LOF  Compactness    Proximity  \
Dataset Model
ADULT   CACTUS         0.7 ± 0.07  1.12 ± 0.02  0.33 ± 0.03  0.64 ± 0.05
        CausalCACTUS   0.8 ± 0.08  1.07 ± 0.02  0.55 ± 0.03  0.47 ± 0.06
        LatentCF++    0.99 ± 0.01  1.14 ± 0.04  0.36 ± 0.02  0.58 ± 0.09
        Prototype C     1.0 ± 0.0  2.23 ± 0.05  0.06 ± 0.01  2.82 ± 0.09
        Prototype D     1.0 ± 0.0  2.01 ± 0.07  0.07 ± 0.02  2.62 ± 0.08

Metric               Causal Validity (Hard) Causal Validity (Soft)  \
Dataset Model
ADULT   CACTUS                  0.94 ± 0.04            0.97 ± 0.02
        CausalCACTUS            0.89 ± 0.04            0.95 ± 0.02
        LatentCF++                1.0 ± 0.0              1.0 ± 0.0
        Prototype C               1.0 ± 0.0              1.0 ± 0.0
        Prototype D               1.0 ± 0.0              1.0 ± 0.0

Metric               Causal Compact Validity inlier_fraction
Dataset Model
ADULT   CACTUS                   0.34 ± 0.03     0.97 ± 0.04
        CausalCACTUS             0.54 ± 0.04     0.96 ± 0.02
        LatentCF++               0.33 ± 0.03     0.97 ± 0.03
        Prototype C              0.06 ± 0.01     0.13 ± 0.07
        Prototype D              0.08 ± 0.02     0.24 ± 0.07