In [1]:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="2,3"

%load_ext autoreload
%autoreload 2

In [2]:
import ipdb
from Data import *
from address import *
from modelGen import *
from utils import cf_eval, cleanup_gpu
from models import CausalCondLatentCF, latentCFpp, PrototypeLatentCF
from models import CondLatentCF # Note: get the vanilla CondLatentCF
import numpy as np
import random 
from tensorflow import random as tf_random
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from itertools import product
import argparse
import os
import pandas as pd

In [3]:
SEED = 23

os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf_random.set_seed(SEED)

CF_METHODS = {  
    "LatentCFpp": latentCFpp,
    "Prototype": PrototypeLatentCF,
    "CausalCACTUS": CausalCondLatentCF,
    "CACTUS": CondLatentCF
}

In [4]:
# Experimentos que a realizar
EXP = [
    {
        "name": "LatentCF++",
        "data": "LAW",
        "classifier": "./exp/LAW_class/config.json",
        "AE": "./exp/LAW_AE/config.json",
        "CFmethod": "LatentCFpp",
        "context": [
            "male",
            "racetxt"
        ],
        "epochs": 100,
        "tol": 0.001,
        "target_prob": 0.5,
        "learning_rate": 0.1
    },
    {
        "name": "Prototype C",
        "data": "LAW",
        "classifier": "./exp/LAW_class/config.json",
        "AE": "./exp/LAW_AE/config.json",
        "CFmethod": "Prototype",
        "context": [
            "male",
            "racetxt"
        ],
        "epochs": 100,
        "kappa": 0.0,
        "c": 1.0,
        "c_steps": 1,
        "beta": 0.1,
        "gamma": 0.0,
        "theta": 100.0,
        "clip": [
            -1000,
            1000
        ],
        "feat_range": [
            -4,
            4
        ],
        "lr": 0.01
    },
    {
        "name": "Prototype D",
        "data": "LAW",
        "classifier": "./exp/LAW_class/config.json",
        "AE": "./exp/LAW_AE/config.json",
        "CFmethod": "Prototype",
        "context": [
            "male",
            "racetxt"
        ],
        "epochs": 100,
        "kappa": 0.0,
        "c": 1.0,
        "c_steps": 1,
        "beta": 0.1,
        "gamma": 100.0,
        "theta": 100.0,
        "clip": [
            -1000,
            1000
        ],
        "feat_range": [
            -4,
            4
        ],
        "lr": 0.01
    },
    {
        "name": "CACTUS",
        "data": "LAW",
        "classifier": "./exp/LAW_class/config.json",
        "AE": "./exp/LAW_CACTUS/config.json",
        "CFmethod": "CACTUS",
        "context": [
            "male",
            "racetxt"
        ],
        "epochs": 300,
        "target_prob": 0.5,
        # "learning_rate": 0.005,
        "learning_rate": 0.01,
        "power": 0.5,
        "alpha": 0.7,
        "gamma": 0.1,
        "beta": 0.01,
        # "dynamicAlpha": True
        "dynamicAlpha": False
    },
    {
        "name": "CausalCACTUS",
        "data": "LAW",
        "classifier": "./exp/LAW_class/config.json",
        "AE": "./exp/LAW_CACTUS/config.json",
        "CFmethod": "CausalCACTUS",
        "context": [
            "male",
            "racetxt"
        ],
        "epochs": 300,
        "target_prob": 0.5,
        # "learning_rate": 0.005,
        "learning_rate": 0.01,
        "power": 0.5,
        "alpha": 0.7,
        "gamma": 0.1,
        "beta": 0.01,
        "dynamicAlpha": True
        # "dynamicAlpha": False
    }
]

In [5]:
import re
from collections import defaultdict
# TODO: make a function to convert the causal paths for all the test samples
def build_causal_index_map(input_features, graph_str):
    """
    Returns:
        child_to_parents: dict {child_idx: [parent_idx, ...]}
        parent_to_children: dict {parent_idx: [child_idx, ...]}
        feat2idx: dict {feature_name: index}
    """

    # Feature name to index
    feat2idx = {f: i for i, f in enumerate(input_features)}

    # Extract edges using regex
    edges = re.findall(r'(\w+)\s*->\s*(\w+)', graph_str)

    child_to_parents = defaultdict(list)
    parent_to_children = defaultdict(list)

    for parent, child in edges:

        if parent not in feat2idx or child not in feat2idx:
            raise ValueError(f"Feature in graph not found in dataset: {parent} or {child}")

        p_idx = feat2idx[parent]
        c_idx = feat2idx[child]

        child_to_parents[c_idx].append(p_idx)
        parent_to_children[p_idx].append(c_idx)

    return dict(child_to_parents), dict(parent_to_children), feat2idx

# credit_rex5_constraints_min.dot
graph_str1 = """ 
strict digraph {
fulltime;
zgpa;
zfygpa;
faminc;
decile1b;
racetxt;
male;
ugpa;
decile3;
lsat;
tier;
fulltime -> faminc;
zgpa -> lsat;
zgpa -> ugpa;
zfygpa -> faminc;
decile1b -> lsat;
decile3 -> ugpa;
decile3 -> lsat;
decile3 -> faminc;
tier -> zgpa;
}
"""

# adult_rex6_constraints_mod.dot
graph_str2 = """
strict digraph {
fulltime;
zgpa;
zfygpa;
faminc;
decile1b;
racetxt;
male;
ugpa;
decile3;
lsat;
tier;
fulltime -> faminc;
ugpa -> decile3;
lsat -> decile1b;
}
"""

# # CF generation
# child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
#     data.features_lbls,
#     # graph_str
#     graph_str1
# )
# print("Feature → index:")
# print(feat2idx)
# print("\nChild → Parents (index form):")
# print(child_to_parents_dict)

In [6]:
# data.features_lbls

## Graph 1 (Minimum priors)

In [7]:
N = 50 
N_BOOTSTRAP = 5
# SEED_list = [23] * N_BOOTSTRAP
SEED_list = [12, 23, 34, 45, 56]

# Number of samples to compute the metrics for CF evaluation
METRICS = []
for i, exp in enumerate(EXP):
    print("\n" * 2)
    print("*" * 200)
    print(f"Running exp: {exp['name']} ({i}/{len(EXP)})")
    print("*" * 200)
    print("\n" * 2)
    
    # Reading the data
    CLASS_CONFIG_PATH = exp["classifier"]
    AE_CONFIG_PATH = exp["AE"]

    class_config = get_exp_config(CLASS_CONFIG_PATH)
    print("Reading data")
    data = getData(class_config)

    # Getting classifier
    classifier = modelGen(class_config["type"], data, params=class_config, debug=True)
    classifier.load()

    # Getting AE-based Model
    AE_config = get_exp_config(AE_CONFIG_PATH)
    aeModel = modelGen(AE_config["type"], data, params=AE_config, debug=True)
    aeModel.load()

    # CF generation
    child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
        data.features_lbls,
        # TODO: change the string below for graph_str1 and graph_str2
        graph_str1
    )
    print("Feature → index:")
    print(feat2idx)
    print("\nChild → Parents (index form):")
    print(child_to_parents_dict)
    
    if exp["name"] == "CausalCACTUS":
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train,
            x_min=data.X_train.min(axis=0),
            x_max=data.X_train.max(axis=0),
            causal_index_map=child_to_parents_dict
        )
    else:
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train
        )

    for trial in range(N_BOOTSTRAP):

        # --- Sampling test data ---
        SEED = SEED_list[trial]
        os.environ['PYTHONHASHSEED'] = str(SEED)
        random.seed(SEED)
        np.random.seed(SEED)
        tf_random.set_seed(SEED)
        rand_idx = np.random.choice(len(data.X_test), N, replace=True)
        
        # previous name: x
        X_test = data.X_test[rand_idx, ...]
        # previous name: contest
        context_test = data.context_test[exp['context']].values
        context_test = context_test[rand_idx, ...]

        context_training = data.context_train[exp['context']].values

        # previous name: y
        y_test = np.argmax(data.y_test[rand_idx, ...], axis=1)
        y_original_logits = classifier.predict(X_test)
        # previous name: y_
        y_original_labels = np.argmax(y_original_logits, axis=1)

        # --- CF generation ---
        # previous names: 
        # cf_x, cf_y_, x, __
        X_cf, y_cf_labels, X_internal, y_internal = CF_method.transform(
            X_test,
            y_original_labels,
            target_context=context_test,
            verbose=0
        )              

        # TODO: One-hot encoding function for datasets with catergorical features
        cat_idx = [8] #     "tier"
        num_idx = [0, 1, 2, 3, 4, 5, 6, 7]
        X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])
        
        # --- CF evaluation ---
        cf_scores, cf_scores_labels = cf_eval(
            data.X_train, # previous name: data.X_train
            context_training, # previous name: context_training,
            X_test, # previous name: x,
            X_cf, # previous name: cf_x, 
            y_original_labels, # previous name: y_,
            context_test, # previous name: context,
            y_cf_labels, # previous name: cf_y_
            data.scaler_inverse_transform(X_test),
            data.scaler_inverse_transform(X_cf),
            child_to_parents_dict, 
            cat_idx,
            num_idx
        )

        for i_metric, label in enumerate(cf_scores_labels):
            METRICS.append([
                exp["name"],
                exp["data"],
                exp["CFmethod"],
                label,
                cf_scores[i_metric]
            ])

    # Cleaning GPU models
    cleanup_gpu()

# --- Metrics aggregation ---
df_metrics = pd.DataFrame(
    data=METRICS,
    columns=["Model", "Dataset", "CFMethod", "Metric", "Value"]
)
df_metrics = df_metrics.round(3)
print(df_metrics)

********************************************************************************************************************************************************************************************************
Running exp: LatentCF++ (0/5)
********************************************************************************************************************************************************************************************************



Reading data
male
1    10550
0     8142
Name: count, dtype: int64
racetxt
1    17491
0     1201
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 3672
Positive class: 1836.0
Context 'sex=Male': 1992
Context 'race=White': 3138
----------------------------------------------------------------------------------------------------




Building model

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:100: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["male"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["racetxt"]))

Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 dense (Dense)               (None, 64)                640

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,394
Trainable params: 34,626
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: LAW_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 model_1 (Functional)        (None, 16)                4672

 model_2 (Functional)        (None, 9)                 4665

=================================================================
Total params: 9,337
Trainable params: 9,337
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: LAW_AE
Feature → index:
{'lsat': 0, 'ugpa': 1, 'zfygpa': 2, 'zgpa': 3, 'faminc': 4, 'decile1b': 5, 'decile3': 6, 'fulltime': 7, 'tier': 8}

Child → Parents (index form):
{4: [7, 2, 6], 0: [3, 5, 6], 1: [3, 6], 3: [8]}
Building model: latentCF [CF]
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 16)]              0

 model_2 (Functional)        (None, 9)                 4665

 model (Functional)          (None, 2)                 35394

=================================================================
Total params: 40,059
Trainable params: 39,291
Non-trainable params: 768
_________________________________________________________________
2/2 [==============================] - 1s 4ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 0 0]
[0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9868247261310692 1.1204000635900395
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (16, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9607764510318263 1.2564887006629033
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (4, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.0081615170781122 1.3682734081701595
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (25, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9715371012115244 1.3381340971659634
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9607764510318263 1.0285167868703504 1.3682734081701595 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 1 1
 0 1 0 0 0 0 0 1 1 0 0 1 0]
[1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 1 1
 0 1 0 0 0 0 0 1 1 0 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0508921698567588 1.327932253595671
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (15, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9614934049753691 1.4062960537778775
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (5, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.070554379875673 1.4716124092112273
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (27, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9809492444864105 1.6088994064712643
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9614934049753691 1.0780133623684676 1.6088994064712643 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1 1 1 0
 0 0 0 0 0 1 1 1 0 0 0 1 0]
[0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1 1 1 0
 0 0 0 0 0 1 1 1 0 0 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.014394050511157 1.172448348605873
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (14, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.0240761515525547 1.2022094998778414
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.049544189571297 1.7198666847794013
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (28, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9756017735468607 1.5781579369077232
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9756017735468607 1.0638009750144097 1.7198666847794013 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1
 0 1 0 1 1 1 0 1 1 1 1 1 0]
[0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 1
 0 1 0 1 1 1 0 1 1 1 1 1 0]
0.98
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9953124589613479 1.1875624131072002
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9767678448456912 1.7264528984810616
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.0218012547790232 1.2269120213097273
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (24, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9625490694551228 1.4165444780463632
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9625490694551228 1.0524603058822386 1.7264528984810616 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1
 0 1 1 0 1 0 0 1 0 0 1 0 0]
[1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1
 0 1 1 0 1 0 0 1 0 0 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0300606053975807 1.1757762519717654
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (12, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9591242291676036 1.2959542990663504
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (4, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.1000148237963157 1.367077496375293
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (31, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9846919165808881 1.5545069250757062
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9591242291676036 1.071308826705975 1.5545069250757062 50



********************************************************************************************************************************************************************************************************
Running exp: Prototype C (1/5)
********************************************************************************************************************************************************************************************************



Reading data
male
1    10550
0     8142
Name: count, dtype: int64
racetxt
1    17491
0     1201
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 3672
Positive class: 1836.0
Context 'sex=Male': 1992
Context 'race=White': 3138
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 dense (Dense)               (None, 64)                640

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:100: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["male"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["racetxt"]))

 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,394
Trainable params: 34,626
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: LAW_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 model_1 (Functional)        (None, 16)                4672

 model_2 (Functional)        (None, 9)                 4665

=================================================================
Total params: 9,337
Trainable params: 9,337
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: LAW_AE
Feature → index:
{'lsat': 0, 'ugpa': 1, 'zfygpa': 2, 'zgpa': 3, 'faminc': 4, 'decile1b': 5, 'decile3': 6, 'fulltime': 7, 'tier': 8}

Child → Parents (index form):
{4: [7, 2, 6], 0: [3, 5, 6], 1: [3, 6], 3: [8]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
WARNING:tensorflow:AutoGraph could not transform <bound method PrototypeLatentCF._loss of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f5fec17c2b0>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <bound method PrototypeLatentCF._loss of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f5fec17c2b0>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 0 0]
[0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.6922187092278271 3.6908603840675567
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (16, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.4861828891417692 3.8099096046727325
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (4, 14)
X_ shape: (165, 14)
lof_cf min/max: 2.07703548577073 2.410394561812308
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (25, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.3346983142605167 5.166636362123884
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.3346983142605167 2.5641025608517545 5.166636362123884 50
2/2 [==============================] - 0s 3ms/step
[1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 1 1
 0 1 0 0 0 0 0 1 1 0 0 1 0]
[1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 1 1
 0 1 0 0 0 0 0 1 1 0 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 2.320787108608789 3.3218947841219078
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (15, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.632989261518644 4.02061333771279
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (5, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.512298026956047 2.5806294524959315
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (27, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.359480525474033 4.512286878774929
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.359480525474033 2.794622071129707 4.512286878774929 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1 1 1 0
 0 0 0 0 0 1 1 1 0 0 0 1 0]
[0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1 1 1 0
 0 0 0 0 0 1 1 1 0 0 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.6013837976013907 3.4546909037652727
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (14, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.0424577608258538 4.849564685603226
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 2.045357051793947 2.7668073132994797
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (28, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.1879694475584108 4.531244479012094
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.0424577608258538 2.7361648278542345 4.849564685603226 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1
 0 1 0 1 1 1 0 1 1 1 1 1 0]
[0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1
 0 1 0 1 1 1 0 1 1 1 1 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.4714381951962447 2.9617345809341633
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.3547281483946962 3.413377164726439
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.7029131191023303 2.7032593657884276
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (24, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.846474615767108 4.310882878010512
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.3547281483946962 2.5840257938817546 4.310882878010512 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1
 0 1 1 0 1 0 0 1 0 0 1 0 0]
[1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1
 0 1 1 0 1 0 0 1 0 0 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.7203896921571413 2.899536359276932
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (12, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.1587774013893932 3.9979976441902094
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (4, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.8189786798512853 2.242030293493848
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (31, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.7561588822442453 4.367113230698539
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.1587774013893932 2.558039677501262 4.367113230698539 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype D (2/5)
********************************************************************************************************************************************************************************************************



Reading data
male
1    10550
0     8142
Name: count, dtype: int64
racetxt
1    17491
0     1201
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 3672
Positive class: 1836.0
Context 'sex=Male': 1992
Context 'race=White': 3138
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 dense (Dense)               (None, 64)                640

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:100: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["male"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["racetxt"]))

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,394
Trainable params: 34,626
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: LAW_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 model_1 (Functional)        (None, 16)                4672

 model_2 (Functional)        (None, 9)                 4665

=================================================================
Total params: 9,337
Trainable params: 9,337
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: LAW_AE
Feature → index:
{'lsat': 0, 'ugpa': 1, 'zfygpa': 2, 'zgpa': 3, 'faminc': 4, 'decile1b': 5, 'decile3': 6, 'fulltime': 7, 'tier': 8}

Child → Parents (index form):
{4: [7, 2, 6], 0: [3, 5, 6], 1: [3, 6], 3: [8]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 0 0]
[0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.7078985953680181 2.1224890977266324
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (16, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.3209790411251863 2.860670579046198
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (4, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.5280277162287597 2.3011336524147787
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (25, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.1997989335880384 4.016667120220452
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.1997989335880384 2.0097972863732902 4.016667120220452 50
2/2 [==============================] - 0s 3ms/step
[1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 1 1
 0 1 0 0 0 0 0 1 1 0 0 1 0]
[1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 1 1
 0 1 0 0 0 0 0 1 1 0 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.967644168948802 2.459352997457593
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (15, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.011845231857341 2.60510438759229
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (5, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.7077312825608626 2.351299766817474
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (27, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.2682615278515867 4.016667120220452
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.011845231857341 2.0068618415600783 4.016667120220452 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1 1 1 0
 0 0 0 0 0 1 1 1 0 0 0 1 0]
[0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1 1 1 0
 0 0 0 0 0 1 1 1 0 0 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.5292129168769235 2.3047355307219317
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (14, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.1616532656210108 2.681930533536978
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.5837770125506343 2.126697586768056
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (28, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.0828681356180219 2.9487349477845686
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.0828681356180219 1.9303379176178512 2.9487349477845686 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1
 0 1 0 1 1 1 0 1 1 1 1 1 0]
[0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1
 0 1 0 1 1 1 0 1 1 1 1 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.3851693516875014 2.370074606461563
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.1689453405567654 3.8485899701213993
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.4027335235338962 2.40541988586972
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (24, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.1251053375412852 4.016667120220452
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.1251053375412852 1.9827233024714317 4.016667120220452 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1
 0 1 1 0 1 0 0 1 0 0 1 0 0]
[1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1
 0 1 1 0 1 0 0 1 0 0 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.5292129168769235 2.3431475660157144
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (12, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.2492388511001666 2.6316857383787773
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (4, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.485662239032915 1.590391055728515
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (31, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.2729069281458114 2.8013081965943045
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.2492388511001666 1.9086563398686958 2.8013081965943045 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CACTUS (3/5)
********************************************************************************************************************************************************************************************************



Reading data
male
1    10550
0     8142
Name: count, dtype: int64
racetxt
1    17491
0     1201
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 3672
Positive class: 1836.0
Context 'sex=Male': 1992
Context 'race=White': 3138
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:100: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["male"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["racetxt"]))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 dense (Dense)               (None, 64)                640

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,394
Trainable params: 34,626
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: LAW_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 9)]          0           []

 model_1 (Functional)           (None, 4)            1508        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 9)            1513        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 3,031
Trainable params: 3,031
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: LAW_CACTUS
Feature → index:
{'lsat': 0, 'ugpa': 1, 'zfygpa': 2, 'zgpa': 3, 'faminc': 4, 'decile1b': 5, 'decile3': 6, 'fulltime': 7, 'tier': 8}

Child → Parents (index form):
{4: [7, 2, 6], 0: [3, 5, 6], 1: [3, 6], 3: [8]}
Building model: CondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 9)                 1513

 model (Functional)          (None, 2)                 35394

=================================================================
Total params: 36,907
Trainable params: 0
Non-trainable params: 36,907
_________________________________________________________________
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 0 0]
[0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0
 1 1 0 1 0 0 0 0 0 1 0 0 0]
0.68
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9895111622526231 1.1621812789647192
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (16, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9494748058855789 1.3426380958837731
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (4, 14)
X_ shape: (165, 14)
lof_cf min/max: 0.9719531027837028 1.3118655249302598
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (25, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9626973544659276 1.1226809404194433
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9494748058855789 1.01930586334637 1.3426380958837731 50
2/2 [==============================] - 0s 3ms/step
[1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 1 1
 0 1 0 0 0 0 0 1 1 0 0 1 0]
[1 1 0 1 1 1 0 1 0 0 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1
 1 0 1 1 0 0 0 1 1 0 0 0 1]
0.7
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.970307826414172 1.3517918393768449
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (15, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9494748058855789 1.2301413251441684
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (5, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.0601327620408223 1.3264723814559576
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (27, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9578383257052149 1.326299080933874
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9494748058855789 1.0745784639779161 1.3517918393768449 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1 1 1 0
 0 0 0 0 0 1 1 1 0 0 0 1 0]
[1 1 1 1 0 0 0 1 1 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 1 1 1 1 1 1
 0 1 0 0 1 1 1 0 0 0 0 0 0]
0.74
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9769185404866247 1.1349866427754443
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (14, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9900569703039918 1.1899791441219068
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.0117485654091265 1.3704891443683958
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (28, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9736291652186079 1.2282420800772405
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9736291652186079 1.0501979359470923 1.3704891443683958 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1
 0 1 0 1 1 1 0 1 1 1 1 1 0]
[1 0 0 1 1 0 1 0 1 0 0 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 0 0 1 0 1
 0 1 1 1 1 1 1 0 1 1 0 1 0]
0.66
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.982822588452354 1.0998392403054849
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9611591587563414 1.3016091641303575
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 0.9675598694097408 1.2186086388146462
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (24, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9617776623158724 1.1865002104844855
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9611591587563414 1.0223075906773533 1.3016091641303575 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1
 0 1 1 0 1 0 0 1 0 0 1 0 0]
[1 0 1 0 1 1 0 0 1 1 1 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 0 0 0 0 0 0 0]
0.78
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9769185404866247 1.070011508120956
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (12, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9436762995222555 1.218887597176984
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (4, 14)
X_ shape: (165, 14)
lof_cf min/max: 0.9713093881200431 1.2387504109122334
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (31, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9644019079467312 1.3575531613092686
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9436762995222555 1.0175776553741556 1.3575531613092686 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CausalCACTUS (4/5)
********************************************************************************************************************************************************************************************************



Reading data
male
1    10550
0     8142
Name: count, dtype: int64
racetxt
1    17491
0     1201
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 3672
Positive class: 1836.0
Context 'sex=Male': 1992
Context 'race=White': 3138
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 dense (Dense)               (None, 64)                640

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:100: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["male"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["racetxt"]))

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,394
Trainable params: 34,626
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: LAW_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 9)]          0           []

 model_1 (Functional)           (None, 4)            1508        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 9)            1513        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 3,031
Trainable params: 3,031
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: LAW_CACTUS
Feature → index:
{'lsat': 0, 'ugpa': 1, 'zfygpa': 2, 'zgpa': 3, 'faminc': 4, 'decile1b': 5, 'decile3': 6, 'fulltime': 7, 'tier': 8}

Child → Parents (index form):
{4: [7, 2, 6], 0: [3, 5, 6], 1: [3, 6], 3: [8]}
Building model: CausalCondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 9)                 1513

 model (Functional)          (None, 2)                 35394

=================================================================
Total params: 36,907
Trainable params: 0
Non-trainable params: 36,907
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
[0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 0
 1 0 0 1 0 0 0 0 0 1 0 0 0]
[0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0
 1 1 0 1 0 0 0 0 0 1 0 0 0]
0.78
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9895111622526231 1.1725056500511024
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (16, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9541257994646444 1.2645253121738684
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (4, 14)
X_ shape: (165, 14)
lof_cf min/max: 0.9719531027837028 1.2272022067814206
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (25, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9660857616879833 1.1152416312903866
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9541257994646444 1.0134389198291494 1.2645253121738684 50
2/2 [==============================] - 0s 3ms/step
[1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 1 1
 0 1 0 0 0 0 0 1 1 0 0 1 0]
[1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1
 1 0 1 1 0 0 0 1 1 0 0 0 1]
0.76
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9591917450009613 1.3139999443570443
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (15, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9529377290286851 1.2733400408651863
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (5, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.060425816384108 1.2137251931826338
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (27, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9572865341569204 1.326299080933874
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9529377290286851 1.0491913158479265 1.326299080933874 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1 1 1 0
 0 0 0 0 0 1 1 1 0 0 0 1 0]
[1 1 1 1 0 0 0 1 1 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1
 0 1 0 0 0 1 1 0 0 0 0 0 0]
0.78
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0038540023649731 1.2228813865968384
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (14, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9606864063542041 1.1516716385116261
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.0117485654091265 1.1961363931418734
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (28, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9769269688543364 1.169901948105586
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9606864063542041 1.019517447450038 1.2228813865968384 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1
 0 1 0 1 1 1 0 1 1 1 1 1 0]
[1 0 0 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 0 1 0 1
 0 1 0 1 1 1 1 0 1 1 0 1 0]
0.82
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9659462638622818 1.0381830937037466
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9616821642625376 1.1071452302491942
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.0151234195335637 1.145838248989011
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (24, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9550625390231905 1.1364117742306756
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9550625390231905 1.0167200471770488 1.145838248989011 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1
 0 1 1 0 1 0 0 1 0 0 1 0 0]
[1 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 1 1 1 0 0
 0 0 1 0 1 0 0 1 0 0 0 0 0]
0.88
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0038540023649731 1.0702465089471858
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (12, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9510664947867516 1.1149647747792517
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (4, 14)
X_ shape: (165, 14)
lof_cf min/max: 0.9744191368359223 1.2272022067814206
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (31, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.961255258220692 1.365735141997353
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9510664947867516 1.0032080089702782 1.365735141997353 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
            Model Dataset      CFMethod                Metric  Value
0      LatentCF++     LAW    LatentCFpp             proximity  1.424
1      LatentCF++     LAW    LatentCFpp           n_proximity  0.475
2      LatentCF++     LAW    LatentCFpp              validity  1.000
3      LatentCF++     LAW    LatentCFpp           compactness  0.142
4      LatentCF++     LAW    LatentCFpp           lof_context  1.065
..            ...     ...           ...                   ...    ...
220  CausalCACTUS     LAW  CausalCACTUS           lof_context  1.029
221  CausalCACTUS     LAW  CausalCACTUS  causal_validity_hard  0.380
222  CausalCACTUS     LAW  CausalCACTUS  causal_validity_soft  0.845
223  CausalCACTUS     LAW  CausalCACTUS    causal_compact_val  0.277
224  CausalCACTUS     LAW  CausalCACTUS       inlier_fraction  1.000

[225 rows x 5 columns]

In [8]:
child_to_parents_dict

{4: [7, 2, 6], 0: [3, 5, 6], 1: [3, 6], 3: [8]}

In [9]:
# Pivoting the dataframe
df_metrics_pivot = df_metrics.pivot_table(
    index=["Dataset", "Model"],
    columns="Metric",
    values="Value",
    aggfunc=['mean', 'std']
)

desired_order = [
    "validity",
    "lof_context",
    "compactness",
    "n_proximity",
    "causal_validity_hard",
    "causal_validity_soft",
    "causal_compact_val",
    "inlier_fraction"
]
df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)
df_metrics_pivot = df_metrics_pivot[desired_order]

df_metrics_pivot.rename(
    columns={
        "validity": "Validity",
        "lof_context": "LOF",
        "compactness": "Compactness",
        "n_proximity": "Proximity",
        "causal_validity_hard": "Causal Validity (Hard)",
        "causal_validity_soft": "Causal Validity (Soft)",
        "causal_compact_val": "Causal Compact Validity",
        "inlier_fraction": "inlier_fraction"
    },
    inplace=True
)

df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)

# df_formatted = df_metrics_pivot.apply(
#     lambda x: x["mean"].map("${:2.2f}".format)
#     + " \\pm "
#     + x["std"].map("{:2.2f} $".format),
#     axis=1
# )
# df_formatted

df_formatted = df_metrics_pivot.apply(
    lambda x: (
        x["mean"].round(2).astype(str)
        + " ± "
        + x["std"].round(2).astype(str)
    ),
    axis=1
)
df_formatted

Metric                   Validity          LOF  Compactness    Proximity  \
Dataset Model
LAW     CACTUS        0.71 ± 0.05  1.06 ± 0.02  0.19 ± 0.05  0.52 ± 0.04
        CausalCACTUS   0.8 ± 0.05  1.04 ± 0.01  0.29 ± 0.04  0.38 ± 0.03
        LatentCF++     1.0 ± 0.01   1.1 ± 0.02  0.13 ± 0.01  0.51 ± 0.04
        Prototype C     1.0 ± 0.0  2.65 ± 0.07  0.03 ± 0.01   2.3 ± 0.05
        Prototype D     1.0 ± 0.0  2.01 ± 0.07  0.03 ± 0.01  1.84 ± 0.07

Metric               Causal Validity (Hard) Causal Validity (Soft)  \
Dataset Model
LAW     CACTUS                  0.51 ± 0.07            0.88 ± 0.02
        CausalCACTUS            0.48 ± 0.07            0.87 ± 0.02
        LatentCF++              0.21 ± 0.06             0.8 ± 0.02
        Prototype C             0.82 ± 0.05            0.95 ± 0.01
        Prototype D              0.8 ± 0.08            0.95 ± 0.02

Metric               Causal Compact Validity inlier_fraction
Dataset Model
LAW     CACTUS                   0.26 ± 0.05       1.0 ± 0.0
        CausalCACTUS             0.33 ± 0.04       1.0 ± 0.0
        LatentCF++                0.17 ± 0.0     0.98 ± 0.04
        Prototype C               0.08 ± 0.0     0.04 ± 0.02
        Prototype D              0.09 ± 0.01     0.14 ± 0.05

In [10]:
print(data.scaler_inverse_transform(X_test))
print(data.scaler_inverse_transform(X_cf))

[[ 2.70e+01  2.90e+00 -3.60e-01 -1.09e+00  4.00e+00  4.00e+00  2.00e+00
   1.00e+00  1.00e+00]
 [ 3.60e+01  3.60e+00  5.90e-01  0.00e+00  3.00e+00  7.00e+00  5.00e+00
   1.00e+00  5.00e+00]
 [ 4.10e+01  2.50e+00  1.00e-01 -9.50e-01  3.00e+00  6.00e+00  2.00e+00
   2.00e+00  2.00e+00]
 [ 3.70e+01  3.90e+00  1.04e+00  2.12e+00  4.00e+00  9.00e+00  1.00e+01
   1.00e+00  1.00e+00]
 [ 4.35e+01  3.00e+00  1.36e+00  1.22e+00  3.00e+00  1.00e+01  9.00e+00
   1.00e+00  4.00e+00]
 [ 3.90e+01  3.30e+00 -1.30e-01 -1.10e+00  4.00e+00  5.00e+00  2.00e+00
   1.00e+00  2.00e+00]
 [ 3.25e+01  3.50e+00  1.40e-01 -1.60e-01  3.00e+00  6.00e+00  5.00e+00
   1.00e+00  2.00e+00]
 [ 3.70e+01  3.20e+00 -5.10e-01 -9.90e-01  3.00e+00  3.00e+00  2.00e+00
   1.00e+00  3.00e+00]
 [ 3.70e+01  2.70e+00 -6.30e-01 -1.43e+00  4.00e+00  3.00e+00  1.00e+00
   1.00e+00  1.00e+00]
 [ 3.60e+01  2.50e+00  1.30e-01  1.80e-01  4.00e+00  6.00e+00  6.00e+00
   1.00e+00  1.00e+00]
 [ 4.70e+01  3.90e+00  2.20e-01 -2.00e-02  3.00e+00  6.00e+00  5.00e+00
   1.00e+00  5.00e+00]
 [ 3.40e+01  2.70e+00 -6.70e-01 -7.30e-01  4.00e+00  3.00e+00  3.00e+00
   1.00e+00  2.00e+00]
 [ 2.60e+01  3.20e+00 -1.57e+00 -1.95e+00  3.00e+00  1.00e+00  1.00e+00
   1.00e+00  3.00e+00]
 [ 3.80e+01  3.00e+00 -6.90e-01 -7.30e-01  3.00e+00  3.00e+00  3.00e+00
   1.00e+00  2.00e+00]
 [ 4.40e+01  3.10e+00 -6.70e-01 -1.70e-01  4.00e+00  3.00e+00  5.00e+00
   1.00e+00  3.00e+00]
 [ 3.60e+01  3.00e+00  3.60e-01  7.30e-01  4.00e+00  7.00e+00  8.00e+00
   1.00e+00  2.00e+00]
 [ 3.30e+01  2.60e+00  1.75e+00 -5.40e-01  3.00e+00  1.00e+01  3.00e+00
   2.00e+00  3.00e+00]
 [ 2.80e+01  3.80e+00 -1.46e+00 -1.48e+00  3.00e+00  1.00e+00  1.00e+00
   1.00e+00  2.00e+00]
 [ 3.70e+01  2.70e+00  1.30e-01 -1.70e-01  4.00e+00  6.00e+00  5.00e+00
   1.00e+00  1.00e+00]
 [ 2.50e+01  3.90e+00  1.69e+00  1.85e+00  3.00e+00  1.00e+01  1.00e+01
   1.00e+00  1.00e+00]
 [ 3.10e+01  3.30e+00 -5.00e-02  2.80e-01  4.00e+00  5.00e+00  7.00e+00
   1.00e+00  4.00e+00]
 [ 2.45e+01  2.20e+00 -1.73e+00 -1.34e+00  4.00e+00  1.00e+00  1.00e+00
   1.00e+00  2.00e+00]
 [ 4.30e+01  3.00e+00 -5.90e-01 -1.34e+00  4.00e+00  3.00e+00  1.00e+00
   1.00e+00  5.00e+00]
 [ 3.30e+01  2.90e+00  5.80e-01 -4.00e-02  3.00e+00  7.00e+00  5.00e+00
   1.00e+00  3.00e+00]
 [ 2.80e+01  3.00e+00 -3.00e-01 -1.00e+00  4.00e+00  4.00e+00  2.00e+00
   1.00e+00  3.00e+00]
 [ 3.45e+01  2.70e+00 -1.60e-01  1.70e-01  4.00e+00  5.00e+00  6.00e+00
   1.00e+00  1.00e+00]
 [ 3.60e+01  2.90e+00 -8.00e-01 -8.60e-01  3.00e+00  2.00e+00  3.00e+00
   1.00e+00  2.00e+00]
 [ 3.70e+01  3.90e+00  1.04e+00  2.12e+00  4.00e+00  9.00e+00  1.00e+01
   1.00e+00  1.00e+00]
 [ 3.20e+01  3.60e+00  1.90e-01  0.00e+00  3.00e+00  6.00e+00  6.00e+00
   1.00e+00  1.00e+00]
 [ 2.90e+01  2.10e+00 -1.41e+00 -1.31e+00  4.00e+00  1.00e+00  2.00e+00
   2.00e+00  3.00e+00]
 [ 3.20e+01  3.40e+00 -3.70e-01 -3.80e-01  4.00e+00  4.00e+00  4.00e+00
   1.00e+00  1.00e+00]
 [ 2.00e+01  3.20e+00 -2.00e-01 -4.00e-01  4.00e+00  4.00e+00  4.00e+00
   1.00e+00  3.00e+00]
 [ 3.70e+01  3.10e+00 -8.60e-01 -1.21e+00  5.00e+00  2.00e+00  2.00e+00
   1.00e+00  2.00e+00]
 [ 3.10e+01  3.30e+00 -1.02e+00 -1.25e+00  4.00e+00  2.00e+00  2.00e+00
   1.00e+00  2.00e+00]
 [ 3.50e+01  3.60e+00  4.10e-01 -1.18e+00  3.00e+00  7.00e+00  2.00e+00
   1.00e+00  3.00e+00]
 [ 3.20e+01  2.90e+00  2.40e-01  3.60e-01  2.00e+00  6.00e+00  7.00e+00
   2.00e+00  2.00e+00]
 [ 2.47e+01  2.60e+00 -1.54e+00 -1.43e+00  3.00e+00  1.00e+00  1.00e+00
   1.00e+00  1.00e+00]
 [ 3.90e+01  3.60e+00  1.60e-01  7.80e-01  3.00e+00  6.00e+00  8.00e+00
   2.00e+00  3.00e+00]
 [ 3.20e+01  2.80e+00 -1.71e+00 -2.21e+00  2.00e+00  1.00e+00  1.00e+00
   1.00e+00  3.00e+00]
 [ 2.70e+01  3.70e+00 -1.72e+00 -1.54e+00  4.00e+00  1.00e+00  1.00e+00
   1.00e+00  1.00e+00]
 [ 4.20e+01  3.50e+00 -7.00e-02  7.00e-02  3.00e+00  5.00e+00  6.00e+00
   2.00e+00  4.00e+00]
 [ 3.50e+01  3.00e+00 -8.20e-01 -1.24e+00  3.00e+00  2.00e+00  2.00e+00
   1.00e+00  1.00e+00]
 [ 4.00e+01  3.60e+00  1.40e+00  9.10e-01  3.00e+00  1.00e+01  9.00e+00
   1.00e+00  2.00e+00]
 [ 3.40e+01  3.30e+00  6.30e-01  1.15e+00  4.00e+00  8.00e+00  9.00e+00
   1.00e+00  2.00e+00]
 [ 2.27e+01  2.20e+00 -1.17e+00 -3.00e-01  4.00e+00  1.00e+00  4.00e+00
   2.00e+00  2.00e+00]
 [ 3.90e+01  2.60e+00  1.68e+00  7.60e-01  3.00e+00  1.00e+01  8.00e+00
   2.00e+00  4.00e+00]
 [ 4.00e+01  3.60e+00 -4.50e-01 -4.00e-01  4.00e+00  3.00e+00  4.00e+00
   1.00e+00  3.00e+00]
 [ 3.20e+01  2.80e+00 -1.71e+00 -2.21e+00  2.00e+00  1.00e+00  1.00e+00
   1.00e+00  3.00e+00]
 [ 4.00e+01  3.80e+00  7.90e-01  1.60e-01  3.00e+00  8.00e+00  6.00e+00
   1.00e+00  4.00e+00]
 [ 3.40e+01  3.50e+00  1.14e+00  1.08e+00  4.00e+00  9.00e+00  9.00e+00
   1.00e+00  4.00e+00]]
[[ 3.03154984e+01  3.05526066e+00 -8.21575701e-01 -1.03675151e+00
   4.54547024e+00  2.64309049e+00  2.56184101e+00  1.00000000e+00
   1.00000000e+00]
 [ 4.14366188e+01  3.89276981e+00 -1.39633613e-02 -4.42403667e-02
   2.62989140e+00  4.94920349e+00  5.09046459e+00  1.00000000e+00
   5.00000000e+00]
 [ 3.79793091e+01  2.70041776e+00 -5.92793562e-02 -1.85272306e-01
   2.87835884e+00  5.02291441e+00  4.65729380e+00  2.00000000e+00
   3.00000000e+00]
 [ 3.46081123e+01  3.18800092e+00  1.29124439e+00  1.35036993e+00
   3.20242500e+00  9.30022526e+00  9.40685749e+00  1.00000000e+00
   1.00000000e+00]
 [ 4.35000000e+01  3.00000000e+00  1.36000001e+00  1.22000003e+00
   3.00000000e+00  1.00000000e+01  9.00000000e+00  1.00000000e+00
   4.00000000e+00]
 [ 3.57693710e+01  3.32176280e+00 -3.64848137e-01 -5.31324625e-01
   4.42650986e+00  3.86452699e+00  3.78823900e+00  1.00000000e+00
   2.00000000e+00]
 [ 3.07801399e+01  3.60538697e+00 -1.95141062e-01 -3.32755685e-01
   3.07588863e+00  4.85012674e+00  4.74017859e+00  1.00000000e+00
   2.00000000e+00]
 [ 3.80189400e+01  3.15917349e+00 -7.59425819e-01 -1.00601971e+00
   2.92969084e+00  2.54917216e+00  2.22990966e+00  1.00000000e+00
   3.00000000e+00]
 [ 3.74233742e+01  2.86660147e+00 -4.54820693e-01 -7.46682405e-01
   4.55621052e+00  3.66766953e+00  3.23962855e+00  1.00000000e+00
   2.00000000e+00]
 [ 3.69675026e+01  2.47456574e+00  4.09502327e-01  1.79999992e-01
   3.65573001e+00  7.06353807e+00  6.54592085e+00  1.00000000e+00
   1.00000000e+00]
 [ 4.22988396e+01  3.85465813e+00 -1.26141310e-01 -2.03256205e-01
   2.70029736e+00  4.41744757e+00  4.47058630e+00  1.00000000e+00
   5.00000000e+00]
 [ 3.58499489e+01  3.04013348e+00 -5.39856911e-01 -8.06128681e-01
   3.33443856e+00  3.10110474e+00  2.77620888e+00  1.00000000e+00
   2.00000000e+00]
 [ 2.60000000e+01  3.20000005e+00 -1.56999993e+00 -1.94999993e+00
   3.00000000e+00  1.00000012e+00  1.00000000e+00  1.00000000e+00
   3.00000000e+00]
 [ 3.56197662e+01  3.03485847e+00 -5.07568240e-01 -7.54359424e-01
   3.15715599e+00  3.24034452e+00  2.95070529e+00  1.00000000e+00
   2.00000000e+00]
 [ 4.03971443e+01  2.99596095e+00 -5.01245499e-01 -7.68769979e-01
   4.13359642e+00  3.52269006e+00  3.09151816e+00  1.00000000e+00
   3.00000000e+00]
 [ 3.74296532e+01  2.71032095e+00  3.90284419e-01  1.97961971e-01
   4.00000000e+00  6.95273256e+00  6.59243107e+00  1.00000000e+00
   2.00000000e+00]
 [ 3.69208527e+01  2.65347433e+00  5.46607077e-01  3.40197861e-01
   2.60111475e+00  7.03401232e+00  6.41259575e+00  2.00000000e+00
   3.00000000e+00]
 [ 3.20183067e+01  3.46592021e+00 -1.06482089e+00 -1.22397661e+00
   2.86705971e+00  1.87943804e+00  1.84520030e+00  1.00000000e+00
   3.00000000e+00]
 [ 3.52171402e+01  2.68369389e+00  1.30000010e-01 -1.15000971e-01
   4.07159138e+00  5.96293783e+00  5.51999855e+00  1.00000000e+00
   1.00000000e+00]
 [ 2.61539459e+01  3.97954059e+00  5.35275519e-01  3.36961031e-01
   2.09382486e+00  6.98614454e+00  6.37944269e+00  1.00000000e+00
   1.00000000e+00]
 [ 4.04454193e+01  3.52064109e+00 -9.47581902e-02 -2.29888260e-01
   3.09436154e+00  4.56824493e+00  4.47041035e+00  1.00000000e+00
   4.00000000e+00]
 [ 2.45000000e+01  2.20000005e+00 -1.73000002e+00 -1.34000003e+00
   4.00000000e+00  1.00000012e+00  1.00000000e+00  1.00000000e+00
   2.00000000e+00]
 [ 4.39280548e+01  3.48172069e+00 -1.03530109e+00 -1.16513884e+00
   3.80187798e+00  2.30489349e+00  2.16281056e+00  1.00000000e+00
   5.00000000e+00]
 [ 3.86628380e+01  2.70270109e+00 -1.19833939e-01 -4.00669098e-01
   3.42338514e+00  4.66051435e+00  4.11056376e+00  1.00000000e+00
   2.00000000e+00]
 [ 3.32936325e+01  3.31496572e+00 -1.05505371e+00 -1.23901284e+00
   3.62555623e+00  1.86254561e+00  1.79125476e+00  1.00000000e+00
   2.00000000e+00]
 [ 3.55543327e+01  2.69549513e+00  2.03398004e-01 -2.47440748e-02
   3.90042901e+00  6.23485708e+00  5.81182289e+00  1.00000000e+00
   1.00000000e+00]
 [ 3.54996758e+01  2.92808747e+00 -5.20419419e-01 -7.29779661e-01
   2.73166347e+00  3.26437259e+00  3.08582711e+00  1.00000000e+00
   2.00000000e+00]
 [ 3.46081123e+01  3.18800092e+00  1.29124439e+00  1.35036993e+00
   3.20242500e+00  9.30022526e+00  9.40685749e+00  1.00000000e+00
   1.00000000e+00]
 [ 3.08813801e+01  3.41290259e+00  1.48945823e-01  2.93109007e-02
   2.89112234e+00  6.03191900e+00  5.87219381e+00  1.00000000e+00
   1.00000000e+00]
 [ 3.56838455e+01  2.06303024e+00 -9.62117314e-01 -1.10519850e+00
   2.38416505e+00  2.30844998e+00  2.28782749e+00  2.00000000e+00
   3.00000000e+00]
 [ 3.30566750e+01  3.28556299e+00 -3.70000005e-01 -5.35934508e-01
   3.86381984e+00  4.00000000e+00  3.87591171e+00  1.00000000e+00
   1.00000000e+00]
 [ 3.22228241e+01  3.36201215e+00 -1.01888633e+00 -1.19461668e+00
   2.98024106e+00  1.93524778e+00  1.89165735e+00  1.00000000e+00
   3.00000000e+00]
 [ 3.79800453e+01  3.21351027e+00 -7.75085449e-01 -9.54258859e-01
   5.00000000e+00  2.91779566e+00  2.81518555e+00  1.00000000e+00
   3.00000000e+00]
 [ 3.32934647e+01  3.27155018e+00 -9.44282115e-01 -1.16041577e+00
   3.67187977e+00  2.03552485e+00  1.91712284e+00  1.00000000e+00
   2.00000000e+00]
 [ 3.67123222e+01  3.59999990e+00 -2.08965361e-01 -3.12922329e-01
   2.92004347e+00  4.44127131e+00  4.43414450e+00  1.00000000e+00
   3.00000000e+00]
 [ 3.08231812e+01  2.78340340e+00  4.23832476e-01  2.66757011e-01
   2.63924718e+00  6.40977907e+00  6.00628853e+00  2.00000000e+00
   1.00000000e+00]
 [ 2.46999989e+01  2.59999990e+00 -1.54000008e+00 -1.42999995e+00
   3.00000000e+00  1.00000012e+00  1.00000000e+00  1.00000000e+00
   1.00000000e+00]
 [ 3.70631676e+01  3.24533606e+00  5.22712767e-01  4.24548805e-01
   3.58725047e+00  7.25432634e+00  6.94925022e+00  2.00000000e+00
   3.00000000e+00]
 [ 3.20000000e+01  2.79999995e+00 -1.71000004e+00 -2.21000004e+00
   2.00000000e+00  1.00000012e+00  1.00000000e+00  1.00000000e+00
   3.00000000e+00]
 [ 3.38590851e+01  3.45768023e+00 -7.99307346e-01 -1.02321744e+00
   3.58630419e+00  2.32903409e+00  2.18900967e+00  1.00000000e+00
   2.00000000e+00]
 [ 3.92559738e+01  3.23784161e+00  1.13074698e-01  7.00000152e-02
   3.44521832e+00  6.30986691e+00  6.00000000e+00  2.00000000e+00
   4.00000000e+00]
 [ 3.58239174e+01  3.02772331e+00 -5.36902785e-01 -7.80710638e-01
   3.04960990e+00  3.13693237e+00  2.86559725e+00  1.00000000e+00
   2.00000000e+00]
 [ 3.50765533e+01  3.04774427e+00  1.59976995e+00  1.63828361e+00
   3.31854248e+00  9.78469849e+00  9.82974625e+00  1.00000000e+00
   1.00000000e+00]
 [ 3.15303898e+01  3.49866939e+00  6.57078564e-01  7.23609924e-01
   3.51052213e+00  7.64887524e+00  7.87428761e+00  1.00000000e+00
   1.00000000e+00]
 [ 3.16735020e+01  2.12157536e+00 -6.56385541e-01 -8.46113801e-01
   2.23772454e+00  2.91701674e+00  2.81199312e+00  2.00000000e+00
   3.00000000e+00]
 [ 4.02235756e+01  3.03128123e+00  4.24246609e-01  3.06830227e-01
   3.24891114e+00  7.27256680e+00  6.77383184e+00  2.00000000e+00
   4.00000000e+00]
 [ 3.79324989e+01  3.59999990e+00 -5.13350189e-01 -6.27801120e-01
   4.11629152e+00  3.35057282e+00  3.40265036e+00  1.00000000e+00
   3.00000000e+00]
 [ 3.20000000e+01  2.79999995e+00 -1.71000004e+00 -2.21000004e+00
   2.00000000e+00  1.00000012e+00  1.00000000e+00  1.00000000e+00
   3.00000000e+00]
 [ 3.85878563e+01  3.87296700e+00  1.67369619e-01  1.60000011e-01
   2.19427919e+00  5.89663887e+00  6.00000000e+00  1.00000000e+00
   4.00000000e+00]
 [ 3.94474678e+01  3.94899082e+00 -1.57078445e-01 -1.78898722e-01
   2.94280505e+00  4.52673912e+00  4.72717190e+00  1.00000000e+00
   4.00000000e+00]]

In [11]:
# TODO: One-hot encode categorical features
# cat_idx = [1, 2, 6] # "workclass", "occupation", "maritalstatus"
# num_idx = [0, 3, 4, 5]
# X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])

# --- CF evaluation ---
cf_scores, cf_scores_labels = cf_eval(
    data.X_train, # previous name: data.X_train
    context_training, # previous name: context_training,
    X_test, # previous name: x,
    X_cf, # previous name: cf_x, 
    y_original_labels, # previous name: y_,
    context_test, # previous name: context,
    y_cf_labels, # previous name: cf_y_
    data.scaler_inverse_transform(X_test),
    data.scaler_inverse_transform(X_cf),
    child_to_parents_dict,
    cat_idx,
    num_idx
)

print(cf_scores, cf_scores_labels)

[1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1
 0 1 1 0 1 0 0 1 0 0 1 0 0]
[1 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 1 1 1 0 0
 0 0 1 0 1 0 0 1 0 0 0 0 0]
0.88
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0038540023649731 1.0702465089471858
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (12, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9510664947867516 1.1149647747792517
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (4, 14)
X_ shape: (165, 14)
lof_cf min/max: 0.9744191368359223 1.2272022067814206
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (31, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.961255258220692 1.365735141997353
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9510664947867516 1.0032080089702782 1.365735141997353 50
[1.2624566394277672, 0.42081887980925575, 0.88, 0.24222222222222223, 1.0285503250833, 0.38, 0.845, 0.2772222222222222, 1.0] ['proximity', 'n_proximity', 'validity', 'compactness', 'lof_context', 'causal_validity_hard', 'causal_validity_soft', 'causal_compact_val', 'inlier_fraction']

## Graph 2 (Moderate priors)

In [12]:
N = 50 
N_BOOTSTRAP = 5
# SEED_list = [23] * N_BOOTSTRAP
SEED_list = [11, 22, 33, 44, 55]

# Number of samples to compute the metrics for CF evaluation
METRICS = []
for i, exp in enumerate(EXP):
    print("\n" * 2)
    print("*" * 200)
    print(f"Running exp: {exp['name']} ({i}/{len(EXP)})")
    print("*" * 200)
    print("\n" * 2)
    
    # Reading the data
    CLASS_CONFIG_PATH = exp["classifier"]
    AE_CONFIG_PATH = exp["AE"]

    class_config = get_exp_config(CLASS_CONFIG_PATH)
    print("Reading data")
    data = getData(class_config)

    # Getting classifier
    classifier = modelGen(class_config["type"], data, params=class_config, debug=True)
    classifier.load()

    # Getting AE-based Model
    AE_config = get_exp_config(AE_CONFIG_PATH)
    aeModel = modelGen(AE_config["type"], data, params=AE_config, debug=True)
    aeModel.load()

    # CF generation
    child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
        data.features_lbls,
        # TODO: change the string below for graph_str1 and graph_str2
        graph_str2
    )
    print("Feature → index:")
    print(feat2idx)
    print("\nChild → Parents (index form):")
    print(child_to_parents_dict)
    
    if exp["name"] == "CausalCACTUS":
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train,
            x_min=data.X_train.min(axis=0),
            x_max=data.X_train.max(axis=0),
            causal_index_map=child_to_parents_dict
        )
    else:
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train
        )

    for trial in range(N_BOOTSTRAP):

        # --- Sampling test data ---
        SEED = SEED_list[trial]
        os.environ['PYTHONHASHSEED'] = str(SEED)
        random.seed(SEED)
        np.random.seed(SEED)
        tf_random.set_seed(SEED)
        rand_idx = np.random.choice(len(data.X_test), N, replace=True)
        
        # previous name: x
        X_test = data.X_test[rand_idx, ...]
        # previous name: contest
        context_test = data.context_test[exp['context']].values
        context_test = context_test[rand_idx, ...]

        context_training = data.context_train[exp['context']].values

        # previous name: y
        y_test = np.argmax(data.y_test[rand_idx, ...], axis=1)
        y_original_logits = classifier.predict(X_test)
        # previous name: y_
        y_original_labels = np.argmax(y_original_logits, axis=1)

        # --- CF generation ---
        # previous names: 
        # cf_x, cf_y_, x, __
        X_cf, y_cf_labels, X_internal, y_internal = CF_method.transform(
            X_test,
            y_original_labels,
            target_context=context_test,
            verbose=0
        )              

        # TODO: One-hot encoding function for datasets with catergorical features
        cat_idx = [8] #     "tier"
        num_idx = [0, 1, 2, 3, 4, 5, 6, 7]
        X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])
        
        # --- CF evaluation ---
        cf_scores, cf_scores_labels = cf_eval(
            data.X_train, # previous name: data.X_train
            context_training, # previous name: context_training,
            X_test, # previous name: x,
            X_cf, # previous name: cf_x, 
            y_original_labels, # previous name: y_,
            context_test, # previous name: context,
            y_cf_labels, # previous name: cf_y_
            data.scaler_inverse_transform(X_test),
            data.scaler_inverse_transform(X_cf),
            child_to_parents_dict, 
            cat_idx,
            num_idx
        )

        for i_metric, label in enumerate(cf_scores_labels):
            METRICS.append([
                exp["name"],
                exp["data"],
                exp["CFmethod"],
                label,
                cf_scores[i_metric]
            ])

    # Cleaning GPU models
    cleanup_gpu()

# --- Metrics aggregation ---
df_metrics = pd.DataFrame(
    data=METRICS,
    columns=["Model", "Dataset", "CFMethod", "Metric", "Value"]
)
df_metrics = df_metrics.round(3)
print(df_metrics)

********************************************************************************************************************************************************************************************************
Running exp: LatentCF++ (0/5)
********************************************************************************************************************************************************************************************************



Reading data
male
1    10550
0     8142
Name: count, dtype: int64
racetxt
1    17491
0     1201
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 3672
Positive class: 1836.0
Context 'sex=Male': 1992
Context 'race=White': 3138
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 dense (Dense)               (None, 64)                640

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:100: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["male"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["racetxt"]))

 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,394
Trainable params: 34,626
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: LAW_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 model_1 (Functional)        (None, 16)                4672

 model_2 (Functional)        (None, 9)                 4665

=================================================================
Total params: 9,337
Trainable params: 9,337
Non-trainable params: 0
_________________________________________________________________
restoring weights of model AE: LAW_AE

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Feature → index:
{'lsat': 0, 'ugpa': 1, 'zfygpa': 2, 'zgpa': 3, 'faminc': 4, 'decile1b': 5, 'decile3': 6, 'fulltime': 7, 'tier': 8}

Child → Parents (index form):
{4: [7], 6: [1], 5: [0]}
Building model: latentCF [CF]
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 16)]              0

 model_2 (Functional)        (None, 9)                 4665

 model (Functional)          (None, 2)                 35394

=================================================================
Total params: 40,059
Trainable params: 39,291
Non-trainable params: 768
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 1 0 1 0 0 0 1 0 1 1]
[0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 1 0 1 0 0 0 1 0 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (4, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0223191809489656 1.1561892332957229
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (20, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9626353511304669 1.7196524285130195
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.0605148901354007 1.360400655354493
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (23, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9780536475057544 1.2884624203035493
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9626353511304669 1.0666179520580132 1.7196524285130195 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 1 0 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0
 1 1 1 0 0 0 0 1 0 0 1 0 1]
[0 0 1 0 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0
 1 1 1 0 0 0 0 1 0 0 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0494989960825123 1.080843480187032
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (22, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9607863601358275 1.7915050986195327
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.002659934539433 1.0529359321601708
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (20, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9673784100256079 1.530666327061765
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9607863601358275 1.0563174465934666 1.7915050986195327 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1
 1 0 1 0 0 1 1 0 0 0 0 0 1]
[0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1
 1 0 1 0 0 1 1 0 0 0 0 0 0]
0.98
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.1538224707126583 1.291393399908345
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9614687519414649 1.591551123175512
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (2, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.078171796952804 1.452920120761657
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (27, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9836822629437442 1.4315109007160223
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9614687519414649 1.069220548784437 1.591551123175512 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 1 1 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0
 0 1 0 0 0 1 0 1 1 1 1 0 1]
[1 0 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0
 0 1 0 0 0 1 0 1 1 1 1 0 1]
0.98
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (6, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.030051956560055 1.2912636693064017
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (17, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9569240037833442 1.2688524546310422
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (1, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.0995845808021776 1.0995845808021776
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (26, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9736869877086644 1.385819540018089
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9569240037833442 1.0655431984132404 1.385819540018089 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0]
[0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.987398320430078 1.101028680726429
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.990430269129916 1.7596354286731646
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.1041001720911894 1.413507377812319
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (24, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9787336249347159 1.8999437110579631
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9787336249347159 1.0946045655760686 1.8999437110579631 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype C (1/5)
********************************************************************************************************************************************************************************************************



Reading data
male
1    10550
0     8142
Name: count, dtype: int64
racetxt
1    17491
0     1201
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 3672
Positive class: 1836.0
Context 'sex=Male': 1992
Context 'race=White': 3138
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 dense (Dense)               (None, 64)                640

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:100: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["male"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["racetxt"]))

 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,394
Trainable params: 34,626
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: LAW_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 model_1 (Functional)        (None, 16)                4672

 model_2 (Functional)        (None, 9)                 4665

=================================================================
Total params: 9,337
Trainable params: 9,337
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: LAW_AE
Feature → index:
{'lsat': 0, 'ugpa': 1, 'zfygpa': 2, 'zgpa': 3, 'faminc': 4, 'decile1b': 5, 'decile3': 6, 'fulltime': 7, 'tier': 8}

Child → Parents (index form):
{4: [7], 6: [1], 5: [0]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 1 0 1 0 0 0 1 0 1 1]
[0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 1 0 1 0 0 0 1 0 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (4, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.6013837976013907 2.438260066702638
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (20, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.0424577608258538 3.8228772440954217
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 2.197799392306518 2.614545673845987
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (23, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.359480525474033 4.131431993671221
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.0424577608258538 2.520468392114882 4.131431993671221 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 0 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0
 1 1 1 0 0 0 0 1 0 0 1 0 1]
[0 0 1 0 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0
 1 1 1 0 0 0 0 1 0 0 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 2.3122420823044765 3.874702191994725
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (22, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.3677667063814465 3.3088247322644397
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.5897090830673009 3.249521551381774
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (20, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9890533256547998 4.299240368722356
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9890533256547998 2.399442737447851 4.299240368722356 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1
 1 0 1 0 0 1 1 0 0 0 0 0 1]
[0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1
 1 0 1 0 0 1 1 0 0 0 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 2.2963040744834453 3.1057524593420047
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.632989261518644 4.406504492709367
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (2, 14)
X_ shape: (165, 14)
lof_cf min/max: 2.5806294524959315 2.6598880358816177
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (27, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9890533256547998 4.143020072622403
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9890533256547998 2.5881770645442814 4.406504492709367 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 1 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0
 0 1 0 0 0 1 0 1 1 1 1 0 1]
[1 0 1 1 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0
 0 1 0 0 0 1 0 1 1 1 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (6, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.7203896921571413 2.910084265597559
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (17, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.4831361888236567 4.33911573309849
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (1, 14)
X_ shape: (165, 14)
lof_cf min/max: 2.5806294524959315 2.5806294524959315
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (26, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.8596154925635342 3.703817931652436
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.4831361888236567 2.3701784634872283 4.33911573309849 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0]
[0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.8575018619986043 2.438260066702638
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.4831361888236567 4.849564685603226
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.8534823675332337 2.614545673845987
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (24, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.5219787994486107 3.9356155135963973
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.4831361888236567 2.494738478087383 4.849564685603226 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype D (2/5)
********************************************************************************************************************************************************************************************************



Reading data
male
1    10550
0     8142
Name: count, dtype: int64
racetxt
1    17491
0     1201
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 3672
Positive class: 1836.0
Context 'sex=Male': 1992
Context 'race=White': 3138
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 dense (Dense)               (None, 64)                640

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:100: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["male"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["racetxt"]))

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,394
Trainable params: 34,626
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: LAW_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 model_1 (Functional)        (None, 16)                4672

 model_2 (Functional)        (None, 9)                 4665

=================================================================
Total params: 9,337
Trainable params: 9,337
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: LAW_AE
Feature → index:
{'lsat': 0, 'ugpa': 1, 'zfygpa': 2, 'zgpa': 3, 'faminc': 4, 'decile1b': 5, 'decile3': 6, 'fulltime': 7, 'tier': 8}

Child → Parents (index form):
{4: [7], 6: [1], 5: [0]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 1 0 1 0 0 0 1 0 1 1]
[0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 1 0 1 0 0 0 1 0 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (4, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.5472724168970924 2.5905392121439172
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (20, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.3411947961945925 2.7461692523542243
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.5280277162287597 2.0848091413988334
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (23, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.2008814431618162 3.646375936450689
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.2008814431618162 2.0117572120010627 3.646375936450689 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 0 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0
 1 1 1 0 0 0 0 1 0 0 1 0 1]
[0 0 1 0 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0
 1 1 1 0 0 0 0 1 0 0 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.5292129168769235 2.577129798628687
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (22, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.2627008479028292 3.7461739807057213
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.4994333737395518 2.238441576673626
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (20, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.3654819865294598 2.76966594451762
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.2627008479028292 1.9573733209046962 3.7461739807057213 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1
 1 0 1 0 0 1 1 0 0 0 0 0 1]
[0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1
 1 0 1 0 0 1 1 0 0 0 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.7161304155823593 2.0797744468249717
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.1275430240713318 3.14418573002293
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (2, 14)
X_ shape: (165, 14)
lof_cf min/max: 2.351299766817474 2.8028966091625755
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (27, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.0475781349453321 3.094601719526347
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.0475781349453321 1.9373827700217818 3.14418573002293 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 1 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0
 0 1 0 0 0 1 0 1 1 1 1 0 1]
[1 0 1 1 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0
 0 1 0 0 0 1 0 1 1 1 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (6, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.7599711399059697 2.3431475660157144
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (17, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.3966729858161064 2.7586051214223883
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (1, 14)
X_ shape: (165, 14)
lof_cf min/max: 2.351299766817474 2.351299766817474
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (26, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.2659217617997829 2.66887743612078
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.2659217617997829 2.0071344275264433 2.7586051214223883 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0]
[0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.5292129168769235 2.9622566639043963
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 1.2439704750281533 3.173931911597738
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.3857314597846648 1.9255327837667402
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (24, 14)
X_ shape: (1405, 14)
lof_cf min/max: 1.4907999974848187 4.016667120220452
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
1.2439704750281533 2.0128595764967594 4.016667120220452 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CACTUS (3/5)
********************************************************************************************************************************************************************************************************



Reading data
male
1    10550
0     8142
Name: count, dtype: int64
racetxt
1    17491
0     1201
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 3672
Positive class: 1836.0
Context 'sex=Male': 1992
Context 'race=White': 3138
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:100: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["male"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["racetxt"]))

 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 dense (Dense)               (None, 64)                640

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,394
Trainable params: 34,626
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: LAW_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 9)]          0           []

 model_1 (Functional)           (None, 4)            1508        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 9)            1513        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 3,031
Trainable params: 3,031
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: LAW_CACTUS
Feature → index:
{'lsat': 0, 'ugpa': 1, 'zfygpa': 2, 'zgpa': 3, 'faminc': 4, 'decile1b': 5, 'decile3': 6, 'fulltime': 7, 'tier': 8}

Child → Parents (index form):
{4: [7], 6: [1], 5: [0]}
Building model: CondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 9)                 1513

 model (Functional)          (None, 2)                 35394

=================================================================
Total params: 36,907
Trainable params: 0
Non-trainable params: 36,907
_________________________________________________________________
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 1 0 1 0 0 0 1 0 1 1]
[0 0 0 0 0 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 0 1
 0 1 0 1 1 1 0 0 0 1 1 1 1]
0.74
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (4, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.006860926848192 1.1362137785588207
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (20, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9436762995222555 1.2527539309948523
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.2387504109122334 1.3704891443683958
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (23, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.951798979315151 1.2630154878423294
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9436762995222555 1.03365276873039 1.3704891443683958 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 0 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0
 1 1 1 0 0 0 0 1 0 0 1 0 1]
[1 1 0 0 0 1 1 1 0 0 0 0 0 1 0 0 1 1 0 1 1 0 1 1 0 0 0 1 0 0 1 1 1 0 1 0 0
 0 0 0 0 1 1 0 1 0 1 1 1 0]
0.6
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9769185404866247 1.1053153648073955
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (22, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.954028880198017 1.4518767009380844
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 0.9721345461255716 1.0092040939014981
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (20, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.962749182282745 1.5146901935848323
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.954028880198017 1.0183595289048277 1.5146901935848323 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1
 1 0 1 0 0 1 1 0 0 0 0 0 1]
[0 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 0 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 0 1 0]
0.76
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0195842812204536 1.1602820142409234
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9542716248515521 1.3016091641303575
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (2, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.1021930565920548 1.3658756323151622
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (27, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9531701888547165 1.252171783219203
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9531701888547165 1.0234614070284551 1.3658756323151622 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 1 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0
 0 1 0 0 0 1 0 1 1 1 1 0 1]
[1 0 1 1 0 0 1 0 0 1 0 0 1 0 1 1 1 1 0 0 0 1 1 0 1 1 1 0 0 0 0 0 1 1 1 0 0
 1 0 0 0 0 1 1 1 1 1 0 0 1]
0.72
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (6, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0195842812204536 1.1362137785588207
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (17, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9533728998765536 1.1429336871300468
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (1, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.1021930565920548 1.1021930565920548
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (26, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9541265191822477 1.2130907274205596
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9533728998765536 1.0211496920395615 1.2130907274205596 50
2/2 [==============================] - 0s 4ms/step
[0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0]
[0 1 0 0 1 0 1 1 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 1
 1 0 0 0 0 0 1 1 0 0 1 0 0]
0.58
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9769185404866247 1.006860926848192
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9582211571797642 1.4862607718717642
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 0.9713093881200431 1.3704891443683958
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (24, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9586250499794396 1.1996755048882908
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9582211571797642 1.0426218200426312 1.4862607718717642 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CausalCACTUS (4/5)
********************************************************************************************************************************************************************************************************



Reading data
male
1    10550
0     8142
Name: count, dtype: int64
racetxt
1    17491
0     1201
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 3672
Positive class: 1836.0
Context 'sex=Male': 1992
Context 'race=White': 3138
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 9)]               0

 dense (Dense)               (None, 64)                640

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:100: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["male"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_Law.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["racetxt"]))

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,394
Trainable params: 34,626
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: LAW_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 9)]          0           []

 model_1 (Functional)           (None, 4)            1508        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 9)            1513        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 3,031
Trainable params: 3,031
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: LAW_CACTUS
Feature → index:
{'lsat': 0, 'ugpa': 1, 'zfygpa': 2, 'zgpa': 3, 'faminc': 4, 'decile1b': 5, 'decile3': 6, 'fulltime': 7, 'tier': 8}

Child → Parents (index form):
{4: [7], 6: [1], 5: [0]}
Building model: CausalCondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 9)                 1513

 model (Functional)          (None, 2)                 35394

=================================================================
Total params: 36,907
Trainable params: 0
Non-trainable params: 36,907
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 1 0 1 0 0 0 1 0 1 1]
[0 0 0 0 0 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1
 0 1 0 1 1 1 0 0 0 1 0 1 1]
0.86
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (4, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0032241694477186 1.222881502655324
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (20, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9510664947867516 1.2354784003079453
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.0797043662749854 1.2272009297100765
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (23, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9579245200238854 1.30483298034884
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9510664947867516 1.0090170826840121 1.30483298034884 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 0 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0
 1 1 1 0 0 0 0 1 0 0 1 0 1]
[1 0 0 0 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 1 0 1 0 0
 1 0 1 0 1 0 0 1 0 0 1 0 0]
0.78
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9995591830177742 1.0431815774553865
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (22, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9512687507925445 1.2492495181164684
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 0.9629064101234764 1.066433336115246
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (20, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9626299358086183 1.5263665289178872
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9512687507925445 1.0058322847073677 1.5263665289178872 50
2/2 [==============================] - 0s 4ms/step
[0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1
 1 0 1 0 0 1 1 0 0 0 0 0 1]
[0 0 1 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 0 0 0]
0.88
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (3, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0783481518495974 1.1028781667686922
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9512687507925445 1.1633047257591986
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (2, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.0649581354459594 1.3658756323151622
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (27, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9526052504872198 1.2574782563114262
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9512687507925445 1.0010056942040724 1.3658756323151622 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 1 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0
 0 1 0 0 0 1 0 1 1 1 1 0 1]
[1 0 1 1 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0
 0 1 0 0 0 1 1 1 1 1 0 0 1]
0.88
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (6, 14)
X_ shape: (277, 14)
lof_cf min/max: 1.0438345723383002 1.1511981955930795
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (17, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9502170751558697 1.145895702107759
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (1, 14)
X_ shape: (165, 14)
lof_cf min/max: 1.0649581354459594 1.0649581354459594
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (26, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9497097017420152 1.2130907274205596
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9497097017420152 1.001458826072707 1.2130907274205596 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 0 0]
[0 0 0 0 1 0 1 1 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0 1 0 0 0 1 1 0 0
 0 0 0 0 0 0 1 1 0 0 1 0 0]
0.74
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 277
Unique rows: 277
After np.unique(): subset size: 277
cf_samples_ shape: (5, 14)
X_ shape: (277, 14)
lof_cf min/max: 0.9895111622526231 1.0671233133980675
lof_train min/max: 0.9471415053747453 1.546608176758252
mean train LOF: 1.054292255128558
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1090
Unique rows: 1090
After np.unique(): subset size: 1090
cf_samples_ shape: (18, 14)
X_ shape: (1090, 14)
lof_cf min/max: 0.9541257994646444 1.217476161269838
lof_train min/max: 0.9597768787247467 1.9180628303323088
mean train LOF: 1.058482696208251
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 165
Unique rows: 165
After np.unique(): subset size: 165
cf_samples_ shape: (3, 14)
X_ shape: (165, 14)
lof_cf min/max: 0.9839455449766202 1.1961221459326976
lof_train min/max: 0.950404472052804 1.4948478686018654
mean train LOF: 1.0873161524400456
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 1405
Unique rows: 1405
After np.unique(): subset size: 1405
cf_samples_ shape: (24, 14)
X_ shape: (1405, 14)
lof_cf min/max: 0.9650013502980399 1.2466875913106277
lof_train min/max: 0.958797290702651 1.7125102787822348
mean train LOF: 1.0531235012029854
0.9541257994646444 1.0203685490702867 1.2466875913106277 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
            Model Dataset      CFMethod                Metric  Value
0      LatentCF++     LAW    LatentCFpp             proximity  1.289
1      LatentCF++     LAW    LatentCFpp           n_proximity  0.430
2      LatentCF++     LAW    LatentCFpp              validity  1.000
3      LatentCF++     LAW    LatentCFpp           compactness  0.156
4      LatentCF++     LAW    LatentCFpp           lof_context  1.101
..            ...     ...           ...                   ...    ...
220  CausalCACTUS     LAW  CausalCACTUS           lof_context  1.053
221  CausalCACTUS     LAW  CausalCACTUS  causal_validity_hard  0.280
222  CausalCACTUS     LAW  CausalCACTUS  causal_validity_soft  0.753
223  CausalCACTUS     LAW  CausalCACTUS    causal_compact_val  0.363
224  CausalCACTUS     LAW  CausalCACTUS       inlier_fraction  1.000

[225 rows x 5 columns]

In [13]:
child_to_parents_dict

{4: [7], 6: [1], 5: [0]}

In [14]:
# Pivoting the dataframe
df_metrics_pivot = df_metrics.pivot_table(
    index=["Dataset", "Model"],
    columns="Metric",
    values="Value",
    aggfunc=['mean', 'std']
)

desired_order = [
    "validity",
    "lof_context",
    "compactness",
    "n_proximity",
    "causal_validity_hard",
    "causal_validity_soft",
    "causal_compact_val",
    "inlier_fraction"
]
df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)
df_metrics_pivot = df_metrics_pivot[desired_order]

df_metrics_pivot.rename(
    columns={
        "validity": "Validity",
        "lof_context": "LOF",
        "compactness": "Compactness",
        "n_proximity": "Proximity",
        "causal_validity_hard": "Causal Validity (Hard)",
        "causal_validity_soft": "Causal Validity (Soft)",
        "causal_compact_val": "Causal Compact Validity",
        "inlier_fraction": "inlier_fraction"
    },
    inplace=True
)

df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)

# df_formatted = df_metrics_pivot.apply(
#     lambda x: x["mean"].map("${:2.2f}".format)
#     + " \\pm "
#     + x["std"].map("{:2.2f} $".format),
#     axis=1
# )
# df_formatted

df_formatted = df_metrics_pivot.apply(
    lambda x: (
        x["mean"].round(2).astype(str)
        + " ± "
        + x["std"].round(2).astype(str)
    ),
    axis=1
)
df_formatted

Metric                   Validity          LOF  Compactness    Proximity  \
Dataset Model
LAW     CACTUS        0.68 ± 0.08  1.06 ± 0.01  0.16 ± 0.02  0.53 ± 0.04
        CausalCACTUS  0.83 ± 0.06  1.04 ± 0.01  0.27 ± 0.06  0.39 ± 0.04
        LatentCF++    0.99 ± 0.01  1.11 ± 0.02  0.12 ± 0.03  0.53 ± 0.07
        Prototype C     1.0 ± 0.0  2.54 ± 0.09  0.02 ± 0.01  2.26 ± 0.05
        Prototype D     1.0 ± 0.0  2.01 ± 0.06  0.04 ± 0.01  1.81 ± 0.06

Metric               Causal Validity (Hard) Causal Validity (Soft)  \
Dataset Model
LAW     CACTUS                   0.1 ± 0.04            0.69 ± 0.01
        CausalCACTUS            0.22 ± 0.06            0.73 ± 0.03
        LatentCF++                0.0 ± 0.0             0.67 ± 0.0
        Prototype C             0.44 ± 0.02            0.81 ± 0.01
        Prototype D             0.37 ± 0.05            0.79 ± 0.02

Metric               Causal Compact Validity inlier_fraction
Dataset Model
LAW     CACTUS                    0.2 ± 0.02      1.0 ± 0.01
        CausalCACTUS             0.28 ± 0.06      1.0 ± 0.01
        LatentCF++               0.14 ± 0.01     0.98 ± 0.01
        Prototype C               0.06 ± 0.0     0.02 ± 0.02
        Prototype D              0.07 ± 0.01     0.12 ± 0.02