In [1]:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="2,3"

%load_ext autoreload
%autoreload 2

In [2]:
import ipdb
from Data import *
from address import *
from modelGen import *
from utils import cf_eval, cleanup_gpu
from models import CausalCondLatentCF, latentCFpp, PrototypeLatentCF
from models import CondLatentCF # Note: get the vanilla CondLatentCF
import numpy as np
import random 
from tensorflow import random as tf_random
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from itertools import product
import argparse
import os
import pandas as pd

In [3]:
SEED = 23

os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf_random.set_seed(SEED)

CF_METHODS = {  
    "LatentCFpp": latentCFpp,
    "Prototype": PrototypeLatentCF,
    "CausalCACTUS": CausalCondLatentCF,
    "CACTUS": CondLatentCF
}

In [4]:
# Experimentos que a realizar
EXP = [
    {
        "name": "LatentCF++",
        "data": "GERMANCREDIT",
        "classifier": "./exp/GERMANCREDIT_class/config.json",
        "AE": "./exp/GERMANCREDIT_AE/config.json",
        "CFmethod": "LatentCFpp",
        "context": [
            "Sex",
            "AgeAbove40"
        ],
        "epochs": 100,
        "tol": 0.001,
        "target_prob": 0.5,
        "learning_rate": 0.1
    },
    {
        "name": "Prototype C",
        "data": "GERMANCREDIT",
        "classifier": "./exp/GERMANCREDIT_class/config.json",
        "AE": "./exp/GERMANCREDIT_AE/config.json",
        "CFmethod": "Prototype",
        "context": [
            "Sex",
            "AgeAbove40"
        ],
        "epochs": 100,
        "kappa": 0.0,
        "c": 1.0,
        "c_steps": 1,
        "beta": 0.1,
        "gamma": 0.0,
        "theta": 100.0,
        "clip": [
            -1000,
            1000
        ],
        "feat_range": [
            -4,
            4
        ],
        "lr": 0.01
    },
    {
        "name": "Prototype D",
        "data": "GERMANCREDIT",
        "classifier": "./exp/GERMANCREDIT_class/config.json",
        "AE": "./exp/GERMANCREDIT_AE/config.json",
        "CFmethod": "Prototype",
        "context": [
            "Sex",
            "AgeAbove40"
        ],
        "epochs": 100,
        "kappa": 0.0,
        "c": 1.0,
        "c_steps": 1,
        "beta": 0.1,
        "gamma": 100.0,
        "theta": 100.0,
        "clip": [
            -1000,
            1000
        ],
        "feat_range": [
            -4,
            4
        ],
        "lr": 0.01
    },
    {
        "name": "CACTUS",
        "data": "GERMANCREDIT",
        "classifier": "./exp/GERMANCREDIT_class/config.json",
        "AE": "./exp/GERMANCREDIT_CACTUS/config.json",
        "CFmethod": "CACTUS",
        "context": [
            "Sex",
            "AgeAbove40"
        ],
        "epochs": 300,
        "target_prob": 0.5,
        # "learning_rate": 0.005,
        "learning_rate": 0.01,
        "power": 0.5,
        "alpha": 0.7,
        "gamma": 0.1,
        "beta": 0.01,
        # "dynamicAlpha": True
        "dynamicAlpha": False
    },
    {
        "name": "CausalCACTUS",
        "data": "GERMANCREDIT",
        "classifier": "./exp/GERMANCREDIT_class/config.json",
        "AE": "./exp/GERMANCREDIT_CACTUS/config.json",
        "CFmethod": "CausalCACTUS",
        "context": [
            "Sex",
            "AgeAbove40"
        ],
        "epochs": 300,
        "target_prob": 0.5,
        # "learning_rate": 0.005,
        "learning_rate": 0.01,
        "power": 0.5,
        "alpha": 0.7,
        "gamma": 0.1,
        "beta": 0.01,
        "dynamicAlpha": True
        # "dynamicAlpha": False
    }
]

In [5]:
import re
from collections import defaultdict
# TODO: make a function to convert the causal paths for all the test samples
def build_causal_index_map(input_features, graph_str):
    """
    Returns:
        child_to_parents: dict {child_idx: [parent_idx, ...]}
        parent_to_children: dict {parent_idx: [child_idx, ...]}
        feat2idx: dict {feature_name: index}
    """

    # Feature name to index
    feat2idx = {f: i for i, f in enumerate(input_features)}

    # Extract edges using regex
    edges = re.findall(r'(\w+)\s*->\s*(\w+)', graph_str)

    child_to_parents = defaultdict(list)
    parent_to_children = defaultdict(list)

    for parent, child in edges:

        if parent not in feat2idx or child not in feat2idx:
            raise ValueError(f"Feature in graph not found in dataset: {parent} or {child}")

        p_idx = feat2idx[parent]
        c_idx = feat2idx[child]

        child_to_parents[c_idx].append(p_idx)
        parent_to_children[p_idx].append(c_idx)

    return dict(child_to_parents), dict(parent_to_children), feat2idx

# credit_rex5_constraints_min.dot
graph_str1 = """ 
strict digraph {
CreditAmount;
Duration;
Age;
CheckingAccount;
Sex;
Job;
SavingAccounts;
Housing;
Job -> Duration;
Job -> CheckingAccount;
SavingAccounts -> Job;
SavingAccounts -> CheckingAccount;
Housing -> CheckingAccount;
Housing -> Job;
}
"""

# adult_rex6_constraints_mod.dot
graph_str2 = """
strict digraph {
CreditAmount;
Duration;
Age;
CheckingAccount;
Sex;
Job;
SavingAccounts;
Housing;
SavingAccounts -> Job;
SavingAccounts -> CheckingAccount;
Housing -> CheckingAccount;
Housing -> Job;
}
"""

# # CF generation
# child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
#     data.features_lbls,
#     # graph_str
#     graph_str1
# )
# print("Feature → index:")
# print(feat2idx)
# print("\nChild → Parents (index form):")
# print(child_to_parents_dict)

In [6]:
# data.features_lbls

## Graph 1 (Minimum priors)

In [7]:
N = 50
N_BOOTSTRAP = 5
# SEED_list = [23] * N_BOOTSTRAP
SEED_list = [12, 23, 34, 45, 56]

# Number of samples to compute the metrics for CF evaluation
METRICS = []

for i, exp in enumerate(EXP):
    print("\n" * 2)
    print("*" * 200)
    print(f"Running exp: {exp['name']} ({i}/{len(EXP)})")
    print("*" * 200)
    print("\n" * 2)
    
    # Reading the data
    CLASS_CONFIG_PATH = exp["classifier"]
    AE_CONFIG_PATH = exp["AE"]

    class_config = get_exp_config(CLASS_CONFIG_PATH)
    print("Reading data")
    data = getData(class_config)

    # Getting classifier
    classifier = modelGen(class_config["type"], data, params=class_config, debug=True)
    classifier.load()

    # Getting AE-based Model
    AE_config = get_exp_config(AE_CONFIG_PATH)
    aeModel = modelGen(AE_config["type"], data, params=AE_config, debug=True)
    aeModel.load()

    # CF generation
    child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
        data.features_lbls,
        # TODO: change the string below for graph_str1 and graph_str2
        graph_str1
    )
    print("Feature → index:")
    print(feat2idx)
    print("\nChild → Parents (index form):")
    print(child_to_parents_dict)
    
    if exp["name"] == "CausalCACTUS":
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train,
            x_min=data.X_train.min(axis=0),
            x_max=data.X_train.max(axis=0),
            causal_index_map=child_to_parents_dict
        )
    else:
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train
        )

    for trial in range(N_BOOTSTRAP):

        # --- Sampling test data ---
        SEED = SEED_list[trial]
        os.environ['PYTHONHASHSEED'] = str(SEED)
        random.seed(SEED)
        np.random.seed(SEED)
        tf_random.set_seed(SEED)
        rand_idx = np.random.choice(len(data.X_test), N, replace=True)
        
        # previous name: x
        X_test = data.X_test[rand_idx, ...]
        # previous name: contest
        context_test = data.context_test[exp['context']].values
        context_test = context_test[rand_idx, ...]

        context_training = data.context_train[exp['context']].values

        # previous name: y
        y_test = np.argmax(data.y_test[rand_idx, ...], axis=1)
        y_original_logits = classifier.predict(X_test)
        # previous name: y_
        y_original_labels = np.argmax(y_original_logits, axis=1)

        # --- CF generation ---
        # previous names: 
        # cf_x, cf_y_, x, __
        X_cf, y_cf_labels, X_internal, y_internal = CF_method.transform(
            X_test,
            y_original_labels,
            target_context=context_test,
            verbose=0
        )              

        # TODO: One-hot encoding function for datasets with catergorical features
        cat_idx = [2, 3, 4, 5] #    CheckingAccount", "Job", "Housing", "SavingAccounts"
        num_idx = [0, 1]
        X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])
        
        # --- CF evaluation ---
        cf_scores, cf_scores_labels = cf_eval(
            data.X_train, # previous name: data.X_train
            context_training, # previous name: context_training,
            X_test, # previous name: x,
            X_cf, # previous name: cf_x, 
            y_original_labels, # previous name: y_,
            context_test, # previous name: context,
            y_cf_labels, # previous name: cf_y_
            data.scaler_inverse_transform(X_test),
            data.scaler_inverse_transform(X_cf),
            child_to_parents_dict, 
            cat_idx,
            num_idx
        )

        for i_metric, label in enumerate(cf_scores_labels):
            METRICS.append([
                exp["name"],
                exp["data"],
                exp["CFmethod"],
                label,
                cf_scores[i_metric]
            ])

    # Cleaning GPU models
    cleanup_gpu()

# --- Metrics aggregation ---
df_metrics = pd.DataFrame(
    data=METRICS,
    columns=["Model", "Dataset", "CFMethod", "Metric", "Value"]
)
df_metrics = df_metrics.round(3)
print(df_metrics)

********************************************************************************************************************************************************************************************************
Running exp: LatentCF++ (0/5)
********************************************************************************************************************************************************************************************************



Reading data
Sex
1    354
0    168
Name: count, dtype: int64
AgeAbove40
0    387
1    135
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 462
Positive class: 231.0
Context 'Sex=1': 315
Context 'AgeAbove40=1': 125
----------------------------------------------------------------------------------------------------




Building model

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["Sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:102: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["AgeAbove40"]))

Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 dense (Dense)               (None, 64)                448

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,202
Trainable params: 34,434
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: GERMANCREDIT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 model_1 (Functional)        (None, 16)                4624

 model_2 (Functional)        (None, 6)                 4614

=================================================================
Total params: 9,238
Trainable params: 9,238
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: GERMANCREDIT_AE
Feature → index:
{'CreditAmount': 0, 'Duration': 1, 'CheckingAccount': 2, 'Job': 3, 'Housing': 4, 'SavingAccounts': 5}

Child → Parents (index form):
{1: [3], 2: [3, 5, 4], 3: [5, 4]}
Building model: latentCF [CF]
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 16)]              0

 model_2 (Functional)        (None, 6)                 4614

 model (Functional)          (None, 2)                 35202

=================================================================
Total params: 39,816
Trainable params: 39,048
Non-trainable params: 768
_________________________________________________________________
2/2 [==============================] - 1s 4ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0
 1 0 0 1 0 0 0 1 1 1 0 1 0]
[0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0
 1 0 0 1 0 0 0 1 1 1 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (9, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.0064986059915437 1.346635126686142
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (5, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.98913088156685 0.995544284146135
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (25, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9892575382784404 1.3572855440410196
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9497399139767907 1.369510797670587
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9497399139767907 1.0811583815883874 1.369510797670587 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0 1
 1 1 0 0 1 0 1 1 1 1 0 1 1]
[0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0 1
 1 1 0 0 1 0 1 1 1 1 0 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (12, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9858286832994546 1.3485800891685469
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (4, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9893628309590496 1.0155502622181696
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (27, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9750073573569213 1.2833614678767293
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9524878914113704 1.205751115788908
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9524878914113704 1.0657262223400832 1.3485800891685469 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 1 0 1 1 1 0 1 0 0 0]
[0 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 1 0 1 1 1 0 1 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (6, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9895374294610104 1.1405950622224201
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9894384621162333 1.0154803566746418
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (30, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9783194296377692 1.7236296061700216
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9732403741226907 1.2283434232080075
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9732403741226907 1.0298020905625926 1.7236296061700216 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 1 1 0 1 0]
[0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 1 1 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (14, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.020849129221411 1.370010513218873
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (6, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9863292067293916 0.9949458460578178
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (19, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9783479286338366 1.3555134117713776
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9531687243615149 1.316299005006203
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9531687243615149 1.0680147628523655 1.370010513218873 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1
 0 1 1 0 0 0 0 1 0 1 1 1 1]
[0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1
 0 1 1 0 0 0 0 1 0 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (14, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9976137112028243 1.4202896786914638
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9896403814250323 0.9949373227850351
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (22, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9749175875932284 1.2969566156559593
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9531687243615149 1.2882126920106667
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9531687243615149 1.0479040612882349 1.4202896786914638 50



********************************************************************************************************************************************************************************************************
Running exp: Prototype C (1/5)
********************************************************************************************************************************************************************************************************



Reading data
Sex
1    354
0    168
Name: count, dtype: int64
AgeAbove40
0    387
1    135
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 462
Positive class: 231.0
Context 'Sex=1': 315
Context 'AgeAbove40=1': 125
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 dense (Dense)               (None, 64)                448

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,202
Trainable params: 34,434
Non-trainable params: 768
_________________________________________________________________

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["Sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:102: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["AgeAbove40"]))

restoring weights of model DNN: GERMANCREDIT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 model_1 (Functional)        (None, 16)                4624

 model_2 (Functional)        (None, 6)                 4614

=================================================================
Total params: 9,238
Trainable params: 9,238
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: GERMANCREDIT_AE
Feature → index:
{'CreditAmount': 0, 'Duration': 1, 'CheckingAccount': 2, 'Job': 3, 'Housing': 4, 'SavingAccounts': 5}

Child → Parents (index form):
{1: [3], 2: [3, 5, 4], 3: [5, 4]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
WARNING:tensorflow:AutoGraph could not transform <bound method PrototypeLatentCF._loss of <tensorflow.python.eager.function.TfMethodTarget object at 0x7fdfe05b9e50>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <bound method PrototypeLatentCF._loss of <tensorflow.python.eager.function.TfMethodTarget object at 0x7fdfe05b9e50>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0
 1 0 0 1 0 0 0 1 1 1 0 1 0]
[0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0
 1 0 0 1 0 0 0 1 1 1 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (9, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.24031608079879 3.004697930940101
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (5, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9922079421766966 1.001849714648059
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (25, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1524625640023949 2.7504429580187675
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.1092939452499229 2.620324349626994
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9922079421766966 1.5585661937393707 3.004697930940101 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0 1
 1 1 0 0 1 0 1 1 1 1 0 1 1]
[0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0 1
 1 1 0 0 1 0 1 1 1 1 0 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (12, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.610056814731734 3.004697930940101
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (4, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9915690187225163 1.3021646028190523
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (27, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1029261004873465 3.1239079260063036
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0881597146765805 1.7219760193845715
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9915690187225163 1.6709768238040654 3.1239079260063036 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 1 0 1 1 1 0 1 0 0 0]
[0 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 1 0 1 1 1 0 1 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (6, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.270413832522936 2.826170570941393
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9915690187225163 1.3021646028190523
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (30, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1029261004873465 3.214220685919551
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.1092939452499229 1.7219760193845715
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9915690187225163 1.5446626960756094 3.214220685919551 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 1 1 0 1 0]
[0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 1 1 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (14, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.270413832522936 2.713660517883308
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (6, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9915690187225163 1.284012819626068
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (19, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1689686676520867 2.7504429580187675
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0881597146765805 2.620324349626994
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9915690187225163 1.4932986145246407 2.7504429580187675 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1
 0 1 1 0 0 0 0 1 0 1 1 1 1]
[0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1
 0 1 1 0 0 0 0 1 0 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (14, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.24031608079879 2.826170570941393
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9915690187225163 1.033629706504978
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (22, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9964792195150582 3.214220685919551
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0881597146765805 2.620324349626994
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9915690187225163 1.5966734247003986 3.214220685919551 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype D (2/5)
********************************************************************************************************************************************************************************************************



Reading data
Sex
1    354
0    168
Name: count, dtype: int64
AgeAbove40
0    387
1    135
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 462
Positive class: 231.0
Context 'Sex=1': 315
Context 'AgeAbove40=1': 125
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 dense (Dense)               (None, 64)                448

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["Sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:102: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["AgeAbove40"]))

=================================================================
Total params: 35,202
Trainable params: 34,434
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: GERMANCREDIT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 model_1 (Functional)        (None, 16)                4624

 model_2 (Functional)        (None, 6)                 4614

=================================================================
Total params: 9,238
Trainable params: 9,238
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: GERMANCREDIT_AE
Feature → index:
{'CreditAmount': 0, 'Duration': 1, 'CheckingAccount': 2, 'Job': 3, 'Housing': 4, 'SavingAccounts': 5}

Child → Parents (index form):
{1: [3], 2: [3, 5, 4], 3: [5, 4]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0
 1 0 0 1 0 0 0 1 1 1 0 1 0]
[0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0
 1 0 0 1 0 0 0 1 1 1 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (9, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.3328277953826948 2.0061293142931302
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (5, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9853015517300253 1.5905015595228893
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (25, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1017552755634248 2.4050347874990754
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.144433316846995 1.5775771072763052
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9853015517300253 1.3639996815775044 2.4050347874990754 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0 1
 1 1 0 0 1 0 1 1 1 1 0 1 1]
[0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0 1
 1 1 0 0 1 0 1 1 1 1 0 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (12, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.3109485975572523 2.0061293142931302
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (4, 16)
X_ shape: (24, 16)
lof_cf min/max: 1.0070344064168704 1.5905015595228893
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (27, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1017552755634248 2.406738498295007
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.1782562273760955 1.529760381807858
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
1.0070344064168704 1.3918570373526513 2.406738498295007 50
2/2 [==============================] - 0s 4ms/step
[0 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 1 0 1 1 1 0 1 0 0 0]
[0 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 1 0 1 1 1 0 1 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (6, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.3683348002381848 2.0061273701129148
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9853015517300253 1.157058940211597
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (30, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.0961411961672347 2.406738498295007
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.2515354002320183 1.5574993126642862
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9853015517300253 1.348920009088421 2.406738498295007 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 1 1 0 1 0]
[0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 1 1 0 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (14, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.2789836034967925 2.366051244503029
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (6, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9853015517300253 1.5905015595228893
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (19, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1017552755634248 2.4050347874990754
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.144433316846995 1.5775771072763052
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9853015517300253 1.3580241849818098 2.4050347874990754 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1
 0 1 1 0 0 0 0 1 0 1 1 1 1]
[0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1
 0 1 1 0 0 0 0 1 0 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (14, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.3328277953826948 2.366051244503029
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9853015517300253 1.5905015595228893
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (22, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.0961411961672347 2.406738498295007
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.144433316846995 1.479662431819511
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9853015517300253 1.3909085841505873 2.406738498295007 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CACTUS (3/5)
********************************************************************************************************************************************************************************************************



Reading data
Sex
1    354
0    168
Name: count, dtype: int64
AgeAbove40
0    387
1    135
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 462
Positive class: 231.0
Context 'Sex=1': 315
Context 'AgeAbove40=1': 125
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 dense (Dense)               (None, 64)                448

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,202
Trainable params: 34,434
Non-trainable params: 768
_________________________________________________________________

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["Sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:102: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["AgeAbove40"]))

restoring weights of model DNN: GERMANCREDIT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 6)]          0           []

 model_1 (Functional)           (None, 4)            1412        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 6)            1414        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,836
Trainable params: 2,836
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: GERMANCREDIT_CACTUS
Feature → index:
{'CreditAmount': 0, 'Duration': 1, 'CheckingAccount': 2, 'Job': 3, 'Housing': 4, 'SavingAccounts': 5}

Child → Parents (index form):
{1: [3], 2: [3, 5, 4], 3: [5, 4]}
Building model: CondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 6)                 1414

 model (Functional)          (None, 2)                 35202

=================================================================
Total params: 36,616
Trainable params: 0
Non-trainable params: 36,616
_________________________________________________________________
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0
 1 0 0 1 0 0 0 1 1 1 0 1 0]
[0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 1 1
 1 0 0 1 0 0 0 1 1 1 0 0 0]
0.82
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (9, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9888733513877164 1.4356366933710731
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (5, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9882858139236885 1.0140893313145694
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (25, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9773853010780321 1.2216097720034804
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9774929347197288 1.2405271855202895
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9773853010780321 1.0309199706281575 1.4356366933710731 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0 1
 1 1 0 0 1 0 1 1 1 1 0 1 1]
[0 1 1 0 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0
 1 0 0 0 1 0 1 1 1 1 0 1 1]
0.88
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (12, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9770684332369504 1.4356366933710731
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (4, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9882858139236885 1.0080751195424722
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (27, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9773853010780321 1.2216097720034804
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9774929347197288 1.1794024412984672
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9770684332369504 1.0325074815536066 1.4356366933710731 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 1 0 1 1 1 0 1 0 0 0]
[0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0
 0 0 0 0 0 1 1 1 0 1 0 0 0]
0.84
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (6, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9770684332369504 1.0413814254824196
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9887191541757645 1.0140893313145694
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (30, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9721729666029966 1.3192391718852774
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9878513142280188 1.157507817842378
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9721729666029966 1.0520947742273123 1.3192391718852774 50
2/2 [==============================] - 0s 2ms/step
[0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 1 1 0 1 0]
[0 1 0 1 1 0 1 0 1 0 0 1 0 1 1 1 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 0 1 1 0 1 0]
0.82
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (14, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9888733513877164 1.3536475205661673
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (6, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9882858139236885 1.0140893313145694
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (19, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9803922029680441 1.1759922789396078
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9774929347197288 1.2405271855202895
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9774929347197288 1.042252670454187 1.3536475205661673 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1
 0 1 1 0 0 0 0 1 0 1 1 1 1]
[0 1 0 1 0 1 1 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 1 1 1 1 1 0 1 0 1 0 1 1 0 0 1
 0 0 0 0 0 0 0 1 0 0 1 0 0]
0.8
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (14, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9932163851940905 1.4356366933710731
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9882858139236885 1.0140893313145694
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (22, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9721729666029966 1.290395852646433
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9811997452635222 1.2405271855202895
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9721729666029966 1.0360311059013525 1.4356366933710731 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CausalCACTUS (4/5)
********************************************************************************************************************************************************************************************************



Reading data
Sex
1    354
0    168
Name: count, dtype: int64
AgeAbove40
0    387
1    135
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 462
Positive class: 231.0
Context 'Sex=1': 315
Context 'AgeAbove40=1': 125
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 dense (Dense)               (None, 64)                448

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,202
Trainable params: 34,434
Non-trainable params: 768
_________________________________________________________________

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["Sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:102: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["AgeAbove40"]))

restoring weights of model DNN: GERMANCREDIT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 6)]          0           []

 model_1 (Functional)           (None, 4)            1412        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 6)            1414        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,836
Trainable params: 2,836
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: GERMANCREDIT_CACTUS
Feature → index:
{'CreditAmount': 0, 'Duration': 1, 'CheckingAccount': 2, 'Job': 3, 'Housing': 4, 'SavingAccounts': 5}

Child → Parents (index form):
{1: [3], 2: [3, 5, 4], 3: [5, 4]}
Building model: CausalCondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 6)                 1414

 model (Functional)          (None, 2)                 35202

=================================================================
Total params: 36,616
Trainable params: 0
Non-trainable params: 36,616
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
[0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0
 1 0 0 1 0 0 0 1 1 1 0 1 0]
[0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1 1 0 1 0 0
 1 0 0 1 0 0 0 1 1 1 0 1 0]
0.98
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (9, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9770684332369504 1.3269866386211853
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (5, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9887235910911911 1.0068057481549657
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (25, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9803955405169497 1.2454861132330532
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9486914668600491 1.2286406307583753
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9486914668600491 1.025143499197961 1.3269866386211853 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0 1
 1 1 0 0 1 0 1 1 1 1 0 1 1]
[0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0 0
 1 0 0 0 1 1 1 1 1 1 0 1 1]
0.9
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (12, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9770684332369504 1.3269866386211853
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (4, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9853015517300253 0.9980311097407413
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (27, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9721729666029966 1.3707737209591775
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9486914668600491 1.1293554484502217
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9486914668600491 1.0217893623404346 1.3707737209591775 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 1 0 1 1 1 0 1 0 0 0]
[0 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0
 1 0 0 0 0 1 1 1 0 1 0 0 0]
0.96
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (6, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9770684332369504 1.0523929792033098
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9853015517300253 1.0068057481549657
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (30, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9803955405169497 1.3707737209591775
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0023626187670984 1.1606969728182062
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9770684332369504 1.018267629236701 1.3707737209591775 50
2/2 [==============================] - 0s 2ms/step
[0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 1 1 0 1 0]
[0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 0 1 1 0 1 0]
0.96
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (14, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9770684332369504 1.1986284953710376
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (6, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9887235910911911 1.0068057481549657
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (19, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9803955405169497 1.0971641840118536
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9486914668600491 1.2286406307583753
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9486914668600491 1.0283447697815673 1.2286406307583753 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1
 0 1 1 0 0 0 0 1 0 1 1 1 1]
[0 1 0 0 1 1 1 0 0 0 1 0 1 0 0 1 0 1 0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 0 0 1
 0 1 1 0 0 0 0 1 0 1 1 0 1]
0.92
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (14, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9770684332369504 1.189539973876614
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9887235910911911 1.0068057481549657
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (22, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9855446008479343 1.3707737209591775
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (7, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9799791332286274 1.2286406307583753
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9770684332369504 1.0308074743994735 1.3707737209591775 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
            Model       Dataset      CFMethod                Metric  Value
0      LatentCF++  GERMANCREDIT    LatentCFpp             proximity  0.825
1      LatentCF++  GERMANCREDIT    LatentCFpp           n_proximity  0.337
2      LatentCF++  GERMANCREDIT    LatentCFpp              validity  1.000
3      LatentCF++  GERMANCREDIT    LatentCFpp           compactness  0.607
4      LatentCF++  GERMANCREDIT    LatentCFpp           lof_context  1.098
..            ...           ...           ...                   ...    ...
220  CausalCACTUS  GERMANCREDIT  CausalCACTUS           lof_context  1.071
221  CausalCACTUS  GERMANCREDIT  CausalCACTUS  causal_validity_hard  0.200
222  CausalCACTUS  GERMANCREDIT  CausalCACTUS  causal_validity_soft  0.700
223  CausalCACTUS  GERMANCREDIT  CausalCACTUS    causal_compact_val  0.357
224  CausalCACTUS  GERMANCREDIT  CausalCACTUS       inlier_fraction  1.000

[225 rows x 5 columns]

In [8]:
child_to_parents_dict

{1: [3], 2: [3, 5, 4], 3: [5, 4]}

In [9]:
# Pivoting the dataframe
df_metrics_pivot = df_metrics.pivot_table(
    index=["Dataset", "Model"],
    columns="Metric",
    values="Value",
    aggfunc=['mean', 'std']
)

desired_order = [
    "validity",
    "lof_context",
    "compactness",
    "n_proximity",
    "causal_validity_hard",
    "causal_validity_soft",
    "causal_compact_val",
    "inlier_fraction"
]
df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)
df_metrics_pivot = df_metrics_pivot[desired_order]

df_metrics_pivot.rename(
    columns={
        "validity": "Validity",
        "lof_context": "LOF",
        "compactness": "Compactness",
        "n_proximity": "Proximity",
        "causal_validity_hard": "Causal Validity (Hard)",
        "causal_validity_soft": "Causal Validity (Soft)",
        "causal_compact_val": "Causal Compact Validity",
        "inlier_fraction": "inlier_fraction"
    },
    inplace=True
)

df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)

# df_formatted = df_metrics_pivot.apply(
#     lambda x: x["mean"].map("${:2.2f}".format)
#     + " \\pm "
#     + x["std"].map("{:2.2f} $".format),
#     axis=1
# )
# df_formatted

df_formatted = df_metrics_pivot.apply(
    lambda x: (
        x["mean"].round(2).astype(str)
        + " ± "
        + x["std"].round(2).astype(str)
    ),
    axis=1
)
df_formatted

Metric                        Validity          LOF  Compactness    Proximity  \
Dataset      Model
GERMANCREDIT CACTUS        0.83 ± 0.03  1.07 ± 0.01  0.39 ± 0.02  0.69 ± 0.03
             CausalCACTUS  0.94 ± 0.03  1.06 ± 0.01  0.48 ± 0.02  0.55 ± 0.04
             LatentCF++      1.0 ± 0.0   1.1 ± 0.01  0.57 ± 0.03  0.41 ± 0.06
             Prototype C     1.0 ± 0.0  1.71 ± 0.09  0.11 ± 0.02   2.4 ± 0.09
             Prototype D     1.0 ± 0.0  1.49 ± 0.03  0.14 ± 0.02  1.72 ± 0.03

Metric                    Causal Validity (Hard) Causal Validity (Soft)  \
Dataset      Model
GERMANCREDIT CACTUS                  0.23 ± 0.08            0.71 ± 0.03
             CausalCACTUS            0.22 ± 0.07            0.68 ± 0.04
             LatentCF++              0.14 ± 0.04            0.69 ± 0.01
             Prototype C             0.78 ± 0.04            0.93 ± 0.01
             Prototype D              0.7 ± 0.08            0.89 ± 0.03

Metric                    Causal Compact Validity inlier_fraction
Dataset      Model
GERMANCREDIT CACTUS                   0.27 ± 0.01       1.0 ± 0.0
             CausalCACTUS             0.32 ± 0.03       1.0 ± 0.0
             LatentCF++               0.39 ± 0.03     0.99 ± 0.01
             Prototype C              0.09 ± 0.02     0.55 ± 0.04
             Prototype D              0.11 ± 0.02     0.64 ± 0.07

## Graph 2 (Moderate priors)

In [10]:
N = 50
N_BOOTSTRAP = 5
# SEED_list = [23] * N_BOOTSTRAP
SEED_list = [11, 22, 33, 44, 55]

# Number of samples to compute the metrics for CF evaluation
METRICS = []

for i, exp in enumerate(EXP):
    print("\n" * 2)
    print("*" * 200)
    print(f"Running exp: {exp['name']} ({i}/{len(EXP)})")
    print("*" * 200)
    print("\n" * 2)
    
    # Reading the data
    CLASS_CONFIG_PATH = exp["classifier"]
    AE_CONFIG_PATH = exp["AE"]

    class_config = get_exp_config(CLASS_CONFIG_PATH)
    print("Reading data")
    data = getData(class_config)

    # Getting classifier
    classifier = modelGen(class_config["type"], data, params=class_config, debug=True)
    classifier.load()

    # Getting AE-based Model
    AE_config = get_exp_config(AE_CONFIG_PATH)
    aeModel = modelGen(AE_config["type"], data, params=AE_config, debug=True)
    aeModel.load()

    # CF generation
    child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
        data.features_lbls,
        # TODO: change the string below for graph_str1 and graph_str2
        graph_str2
    )
    print("Feature → index:")
    print(feat2idx)
    print("\nChild → Parents (index form):")
    print(child_to_parents_dict)
    
    if exp["name"] == "CausalCACTUS":
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train,
            x_min=data.X_train.min(axis=0),
            x_max=data.X_train.max(axis=0),
            causal_index_map=child_to_parents_dict
        )
    else:
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train
        )

    for trial in range(N_BOOTSTRAP):

        # --- Sampling test data ---
        SEED = SEED_list[trial]
        os.environ['PYTHONHASHSEED'] = str(SEED)
        random.seed(SEED)
        np.random.seed(SEED)
        tf_random.set_seed(SEED)
        rand_idx = np.random.choice(len(data.X_test), N, replace=True)
        
        # previous name: x
        X_test = data.X_test[rand_idx, ...]
        # previous name: contest
        context_test = data.context_test[exp['context']].values
        context_test = context_test[rand_idx, ...]

        context_training = data.context_train[exp['context']].values

        # previous name: y
        y_test = np.argmax(data.y_test[rand_idx, ...], axis=1)
        y_original_logits = classifier.predict(X_test)
        # previous name: y_
        y_original_labels = np.argmax(y_original_logits, axis=1)

        # --- CF generation ---
        # previous names: 
        # cf_x, cf_y_, x, __
        X_cf, y_cf_labels, X_internal, y_internal = CF_method.transform(
            X_test,
            y_original_labels,
            target_context=context_test,
            verbose=0
        )              

        # TODO: One-hot encoding function for datasets with catergorical features
        cat_idx = [2, 3, 4, 5] #    CheckingAccount", "Job", "Housing", "SavingAccounts"
        num_idx = [0, 1]
        X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])
        
        # --- CF evaluation ---
        cf_scores, cf_scores_labels = cf_eval(
            data.X_train, # previous name: data.X_train
            context_training, # previous name: context_training,
            X_test, # previous name: x,
            X_cf, # previous name: cf_x, 
            y_original_labels, # previous name: y_,
            context_test, # previous name: context,
            y_cf_labels, # previous name: cf_y_
            data.scaler_inverse_transform(X_test),
            data.scaler_inverse_transform(X_cf),
            child_to_parents_dict, 
            cat_idx,
            num_idx
        )

        for i_metric, label in enumerate(cf_scores_labels):
            METRICS.append([
                exp["name"],
                exp["data"],
                exp["CFmethod"],
                label,
                cf_scores[i_metric]
            ])

    # Cleaning GPU models
    cleanup_gpu()

# --- Metrics aggregation ---
df_metrics = pd.DataFrame(
    data=METRICS,
    columns=["Model", "Dataset", "CFMethod", "Metric", "Value"]
)
df_metrics = df_metrics.round(3)
print(df_metrics)

********************************************************************************************************************************************************************************************************
Running exp: LatentCF++ (0/5)
********************************************************************************************************************************************************************************************************



Reading data
Sex
1    354
0    168
Name: count, dtype: int64
AgeAbove40
0    387
1    135
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 462
Positive class: 231.0
Context 'Sex=1': 315
Context 'AgeAbove40=1': 125
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 dense (Dense)               (None, 64)                448

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,202
Trainable params: 34,434

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["Sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:102: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["AgeAbove40"]))

Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: GERMANCREDIT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 model_1 (Functional)        (None, 16)                4624

 model_2 (Functional)        (None, 6)                 4614

=================================================================
Total params: 9,238
Trainable params: 9,238
Non-trainable params: 0
_________________________________________________________________
restoring weights of model AE: GERMANCREDIT_AE

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Feature → index:
{'CreditAmount': 0, 'Duration': 1, 'CheckingAccount': 2, 'Job': 3, 'Housing': 4, 'SavingAccounts': 5}

Child → Parents (index form):
{3: [5, 4], 2: [5, 4]}
Building model: latentCF [CF]
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 16)]              0

 model_2 (Functional)        (None, 6)                 4614

 model (Functional)          (None, 2)                 35202

=================================================================
Total params: 39,816
Trainable params: 39,048
Non-trainable params: 768
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0
 0 0 0 1 1 0 0 0 1 0 1 1 1]
[1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0
 0 0 0 1 1 0 0 0 1 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (10, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9936727186984129 1.346252545792494
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9948231279008437 0.9955831991319289
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (32, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9892575382784404 1.2760479609758728
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (6, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9543295657197938 1.3596886188747261
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9543295657197938 1.0430173364556752 1.3596886188747261 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0
 1 0 0 0 1 0 1 0 1 1 1 0 1]
[1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0
 1 0 0 0 1 0 1 0 1 1 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9923420116804313 1.1999183769450656
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (4, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9922079421766966 1.0030957093517632
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (28, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9750302003488581 1.3564796083534225
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (5, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9587930171669342 1.1557328019035418
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9587930171669342 1.0282154470637235 1.3564796083534225 50
2/2 [==============================] - 0s 4ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 1
 1 0 1 1 1 1 1 0 1 0 0 0 0]
[0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 1
 1 0 1 1 1 1 1 0 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9935161728877148 1.2312065635873932
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9922079421766966 0.9923135827562731
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (24, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9861052939133815 1.696196330803799
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9534936084441293 1.3606474499366197
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9534936084441293 1.0622986974294655 1.696196330803799 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 0 0 0 0 0 0 1 1 1 0 0 0 0]
[0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 0 0 0 0 0 0 1 1 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (11, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9936232315342475 1.2317321098785639
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9894384621162333 0.9949453780059084
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (20, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9783322354510628 1.3282001637911238
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (12, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9477604509139426 1.2243453088197085
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9477604509139426 1.0284109796986591 1.3282001637911238 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1]
[0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9983930396617826 1.224685368752226
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9896403814250323 0.9909821568804282
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (30, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9783639622852762 1.3393852414249183
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (5, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0061820098902445 1.2140674379854215
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9783639622852762 1.140830091094338 1.3393852414249183 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype C (1/5)
********************************************************************************************************************************************************************************************************



Reading data
Sex
1    354
0    168
Name: count, dtype: int64
AgeAbove40
0    387
1    135
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 462
Positive class: 231.0
Context 'Sex=1': 315
Context 'AgeAbove40=1': 125
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["Sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:102: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["AgeAbove40"]))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 dense (Dense)               (None, 64)                448

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,202
Trainable params: 34,434
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: GERMANCREDIT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 model_1 (Functional)        (None, 16)                4624

 model_2 (Functional)        (None, 6)                 4614

=================================================================
Total params: 9,238
Trainable params: 9,238
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: GERMANCREDIT_AE
Feature → index:
{'CreditAmount': 0, 'Duration': 1, 'CheckingAccount': 2, 'Job': 3, 'Housing': 4, 'SavingAccounts': 5}

Child → Parents (index form):
{3: [5, 4], 2: [5, 4]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0
 0 0 0 1 1 0 0 0 1 0 1 1 1]
[1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0
 0 0 0 1 1 0 0 0 1 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (10, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.24031608079879 3.004697930940101
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9922079421766966 0.9922079421766972
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (32, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1029261004873465 3.214220685919551
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (6, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0881597146765805 2.620324349626994
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9922079421766966 1.5094849494818043 3.214220685919551 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0
 1 0 0 0 1 0 1 0 1 1 1 0 1]
[1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0
 1 0 0 0 1 0 1 0 1 1 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.24031608079879 2.9877986414927835
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (4, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9922079421766966 1.3021646028190523
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (28, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.0725638722039055 3.1239079260063036
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (5, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.1092939452499229 1.6590528253079668
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9922079421766966 1.5237232403382386 3.1239079260063036 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 1
 1 0 1 1 1 1 1 0 1 0 0 0 0]
[0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 1
 1 0 1 1 1 1 1 0 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.24031608079879 2.9877986414927835
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9915690187225163 1.033629706504978
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (24, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.160216349965796 2.7504429580187675
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0881597146765805 2.620324349626994
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9915690187225163 1.595757823305588 2.9877986414927835 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 0 0 0 0 0 0 1 1 1 0 0 0 0]
[0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 0 0 0 0 0 0 1 1 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (11, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.2457556075664749 2.9877986414927835
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9915690187225163 1.284012819626068
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (20, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1689686676520867 3.077324661848424
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (12, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0881597146765805 2.195424593903586
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9915690187225163 1.4624234015599744 3.077324661848424 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1]
[0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.24031608079879 2.872639646318632
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9915690187225163 1.001849714648059
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (30, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1029261004873465 3.214220685919551
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (5, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0881597146765805 1.9440413394677853
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9915690187225163 1.6256779211307233 3.214220685919551 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype D (2/5)
********************************************************************************************************************************************************************************************************



Reading data
Sex
1    354
0    168
Name: count, dtype: int64
AgeAbove40
0    387
1    135
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 462
Positive class: 231.0
Context 'Sex=1': 315
Context 'AgeAbove40=1': 125
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 dense (Dense)               (None, 64)                448

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,202
Trainable params: 34,434
Non-trainable params: 768
_________________________________________________________________

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["Sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:102: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["AgeAbove40"]))

restoring weights of model DNN: GERMANCREDIT_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 model_1 (Functional)        (None, 16)                4624

 model_2 (Functional)        (None, 6)                 4614

=================================================================
Total params: 9,238
Trainable params: 9,238
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: GERMANCREDIT_AE
Feature → index:
{'CreditAmount': 0, 'Duration': 1, 'CheckingAccount': 2, 'Job': 3, 'Housing': 4, 'SavingAccounts': 5}

Child → Parents (index form):
{3: [5, 4], 2: [5, 4]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0
 0 0 0 1 1 0 0 0 1 0 1 1 1]
[1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0
 0 0 0 1 1 0 0 0 1 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (10, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.1799959882000255 2.366051244503029
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9853015517300253 1.0007185645242855
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (32, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.0961411961672347 2.406738498295007
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (6, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.144433316846995 1.5574993126642862
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9853015517300253 1.3745410232709139 2.406738498295007 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0
 1 0 0 0 1 0 1 0 1 1 1 0 1]
[1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0
 1 0 0 0 1 0 1 0 1 1 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.1799959882000255 2.217221917388307
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (4, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9853015517300253 1.1286578769586555
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (28, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1150416149894102 2.3412572668390714
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (5, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.2625837024634372 1.5574993126642862
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9853015517300253 1.4378444619541497 2.3412572668390714 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 1
 1 0 1 1 1 1 1 0 1 0 0 0 0]
[0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 1
 1 0 1 1 1 1 1 0 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.1799959882000255 2.1934628636346973
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 1.0070344064168704 1.1286578769586555
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (24, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1368159451582127 2.4050347874990754
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.144433316846995 1.5775771072763052
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
1.0070344064168704 1.327813477780167 2.4050347874990754 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 0 0 0 0 0 0 1 1 1 0 0 0 0]
[0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 0 0 0 0 0 0 1 1 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (11, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.3109485975572523 2.1934628636346973
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9853015517300253 1.5905015595228893
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (20, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.1017552755634248 2.4050347874990754
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (12, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.1782562273760955 1.529760381807858
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9853015517300253 1.3453513058233328 2.4050347874990754 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1]
[0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.2789836034967925 2.366051244503029
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 1.0070344064168704 1.5905015595228893
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (30, 16)
X_ shape: (173, 16)
lof_cf min/max: 1.0961411961672347 2.406738498295007
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (5, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.1782562273760955 1.529760381807858
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
1.0070344064168704 1.3678498396644097 2.406738498295007 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CACTUS (3/5)
********************************************************************************************************************************************************************************************************



Reading data
Sex
1    354
0    168
Name: count, dtype: int64
AgeAbove40
0    387
1    135
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 462
Positive class: 231.0
Context 'Sex=1': 315
Context 'AgeAbove40=1': 125
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 dense (Dense)               (None, 64)                448

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,202
Trainable params: 34,434
Non-trainable params: 768

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["Sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:102: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["AgeAbove40"]))

_________________________________________________________________
restoring weights of model DNN: GERMANCREDIT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 6)]          0           []

 model_1 (Functional)           (None, 4)            1412        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 6)            1414        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,836
Trainable params: 2,836
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: GERMANCREDIT_CACTUS
Feature → index:
{'CreditAmount': 0, 'Duration': 1, 'CheckingAccount': 2, 'Job': 3, 'Housing': 4, 'SavingAccounts': 5}

Child → Parents (index form):
{3: [5, 4], 2: [5, 4]}
Building model: CondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 6)                 1414

 model (Functional)          (None, 2)                 35202

=================================================================
Total params: 36,616
Trainable params: 0
Non-trainable params: 36,616
_________________________________________________________________
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0
 0 0 0 1 1 0 0 0 1 0 1 1 1]
[1 0 1 0 1 0 1 1 0 0 0 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1 0 1 0 0 0 0 1 0 0 1 0
 0 0 0 0 1 0 0 0 1 0 1 1 0]
0.88
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (10, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.0063110800559931 1.4356366933710731
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9969483721789028 1.0140893313145694
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (32, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9773853010780321 1.3192391718852774
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (6, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9878513142280188 1.2405271855202895
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9773853010780321 1.0804556602530813 1.4356366933710731 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0
 1 0 0 0 1 0 1 0 1 1 1 0 1]
[1 0 0 1 0 0 0 1 0 1 1 1 0 1 1 0 1 1 0 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0
 1 0 0 0 1 0 0 0 1 1 1 0 1]
0.86
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9770684332369504 1.165195890207688
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (4, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9887191541757645 1.0140893313145694
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (28, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9773853010780321 1.203908685871715
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (5, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9878513142280188 1.157507817842378
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9770684332369504 1.1022755541758724 1.203908685871715 50
2/2 [==============================] - 0s 2ms/step
[0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 1
 1 0 1 1 1 1 1 0 1 0 0 0 0]
[0 1 0 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 0
 1 0 1 1 1 1 0 1 1 0 0 0 0]
0.88
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9885392675576874 1.165195890207688
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9894384621162329 0.9969483721789028
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (24, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9721729666029966 1.2216097720034804
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9811997452635222 1.2405271855202895
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9721729666029966 1.069501645326258 1.2405271855202895 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 0 0 0 0 0 0 1 1 1 0 0 0 0]
[0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 1 0 1 1 1 1 0 1 1 0 0 0 0 0 0
 0 0 0 0 1 0 1 1 1 0 0 1 0]
0.76
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (11, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9885392675576874 1.4356366933710731
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9882858139236885 1.0140893313145694
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (20, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9854948086999438 1.1750020975666722
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (12, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9774929347197288 1.1794024412984672
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9774929347197288 1.0606724741683982 1.4356366933710731 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1]
[0 0 1 1 0 1 0 0 0 0 0 1 1 1 0 0 1 0 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 1 1]
0.84
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9770684332369504 1.4356366933710731
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9882858139236885 0.9969483721789028
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (30, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9721729666029966 1.203908685871715
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (5, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0036532865169667 1.157507817842378
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9721729666029966 1.0688798687240602 1.4356366933710731 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CausalCACTUS (4/5)
********************************************************************************************************************************************************************************************************



Reading data
Sex
1    354
0    168
Name: count, dtype: int64
AgeAbove40
0    387
1    135
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 462
Positive class: 231.0
Context 'Sex=1': 315
Context 'AgeAbove40=1': 125
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 6)]               0

 dense (Dense)               (None, 64)                448

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:101: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["Sex"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_GermanCredit.py:102: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["AgeAbove40"]))

=================================================================
Total params: 35,202
Trainable params: 34,434
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: GERMANCREDIT_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 6)]          0           []

 model_1 (Functional)           (None, 4)            1412        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 6)            1414        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 2,836
Trainable params: 2,836
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: GERMANCREDIT_CACTUS
Feature → index:
{'CreditAmount': 0, 'Duration': 1, 'CheckingAccount': 2, 'Job': 3, 'Housing': 4, 'SavingAccounts': 5}

Child → Parents (index form):
{3: [5, 4], 2: [5, 4]}
Building model: CausalCondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 6)                 1414

 model (Functional)          (None, 2)                 35202

=================================================================
Total params: 36,616
Trainable params: 0
Non-trainable params: 36,616
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
[1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0
 0 0 0 1 1 0 0 0 1 0 1 1 1]
[1 0 1 0 1 0 1 1 0 0 0 1 0 1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 0 0 0 0 1 0 0 1 0
 0 0 0 1 1 0 0 0 1 0 1 1 0]
0.94
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (10, 16)
X_ shape: (93, 16)
lof_cf min/max: 1.0312406302766806 1.2789506835129496
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9900879351963893 1.0068057481549657
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (32, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9721729666029966 1.388393739370163
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (6, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0023626187670984 1.1985943986527592
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9721729666029966 1.0602022340139146 1.388393739370163 50
2/2 [==============================] - 0s 3ms/step
[1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0
 1 0 0 0 1 0 1 0 1 1 1 0 1]
[1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0
 1 0 0 0 1 0 1 0 1 1 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9810214973151089 1.2789506835129496
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (4, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9882118640166657 1.0068057481549657
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (28, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9721729666029966 1.1890365422207272
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (5, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0023626187670984 1.165254733568916
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9721729666029966 1.022898143090479 1.2789506835129496 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 1
 1 0 1 1 1 1 1 0 1 0 0 0 0]
[0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 1
 1 0 1 1 1 1 1 0 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9770684332369504 1.2789506835129496
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9900879351963893 0.9922079421766966
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (24, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9803946091281504 1.2032790528521868
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (11, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.99033932882173 1.1985943986527592
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9770684332369504 1.0306888967614924 1.2789506835129496 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 0 0 0 0 0 0 1 1 1 0 0 0 0]
[0 1 0 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 0 0 0 0 0 0 1 1 1 0 0 0 0]
0.98
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (11, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9770684332369504 1.2789506835129496
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (7, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9894384621162329 1.0068057481549657
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (20, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9824912633494798 1.1708903872120646
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (12, 16)
X_ shape: (79, 16)
lof_cf min/max: 0.9486914668600491 1.232220893624018
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9486914668600491 1.0376837622834292 1.2789506835129496 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1]
[0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1]
0.96
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 93
Unique rows: 93
After np.unique(): subset size: 93
cf_samples_ shape: (13, 16)
X_ shape: (93, 16)
lof_cf min/max: 0.9810214973151089 1.1986284953710376
lof_train min/max: 0.9754660367682033 1.9036779630134486
mean train LOF: 1.105128781175989
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 24
Unique rows: 24
After np.unique(): subset size: 24
cf_samples_ shape: (2, 16)
X_ shape: (24, 16)
lof_cf min/max: 0.9894384621162329 0.9900879351963893
lof_train min/max: 0.985171848979778 1.5588082925857287
mean train LOF: 1.0290132547443687
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 173
Unique rows: 173
After np.unique(): subset size: 173
cf_samples_ shape: (30, 16)
X_ shape: (173, 16)
lof_cf min/max: 0.9721729666029966 1.3707737209591775
lof_train min/max: 0.9721729666029966 1.7317121962940139
mean train LOF: 1.0733424969220349
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 79
Unique rows: 79
After np.unique(): subset size: 79
cf_samples_ shape: (5, 16)
X_ shape: (79, 16)
lof_cf min/max: 1.0392523213153626 1.232220893624018
lof_train min/max: 0.945877269170392 1.597852941097265
mean train LOF: 1.0977444322831795
0.9721729666029966 1.037178187546966 1.3707737209591775 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
            Model       Dataset      CFMethod                Metric  Value
0      LatentCF++  GERMANCREDIT    LatentCFpp             proximity  0.916
1      LatentCF++  GERMANCREDIT    LatentCFpp           n_proximity  0.374
2      LatentCF++  GERMANCREDIT    LatentCFpp              validity  1.000
3      LatentCF++  GERMANCREDIT    LatentCFpp           compactness  0.607
4      LatentCF++  GERMANCREDIT    LatentCFpp           lof_context  1.089
..            ...           ...           ...                   ...    ...
220  CausalCACTUS  GERMANCREDIT  CausalCACTUS           lof_context  1.056
221  CausalCACTUS  GERMANCREDIT  CausalCACTUS  causal_validity_hard  0.820
222  CausalCACTUS  GERMANCREDIT  CausalCACTUS  causal_validity_soft  0.900
223  CausalCACTUS  GERMANCREDIT  CausalCACTUS    causal_compact_val  0.387
224  CausalCACTUS  GERMANCREDIT  CausalCACTUS       inlier_fraction  1.000

[225 rows x 5 columns]

In [11]:
child_to_parents_dict

{3: [5, 4], 2: [5, 4]}

In [12]:
# Pivoting the dataframe
df_metrics_pivot = df_metrics.pivot_table(
    index=["Dataset", "Model"],
    columns="Metric",
    values="Value",
    aggfunc=['mean', 'std']
)

desired_order = [
    "validity",
    "lof_context",
    "compactness",
    "n_proximity",
    "causal_validity_hard",
    "causal_validity_soft",
    "causal_compact_val",
    "inlier_fraction"
]
df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)
df_metrics_pivot = df_metrics_pivot[desired_order]

df_metrics_pivot.rename(
    columns={
        "validity": "Validity",
        "lof_context": "LOF",
        "compactness": "Compactness",
        "n_proximity": "Proximity",
        "causal_validity_hard": "Causal Validity (Hard)",
        "causal_validity_soft": "Causal Validity (Soft)",
        "causal_compact_val": "Causal Compact Validity",
        "inlier_fraction": "inlier_fraction"
    },
    inplace=True
)

df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)

# df_formatted = df_metrics_pivot.apply(
#     lambda x: x["mean"].map("${:2.2f}".format)
#     + " \\pm "
#     + x["std"].map("{:2.2f} $".format),
#     axis=1
# )
# df_formatted

df_formatted = df_metrics_pivot.apply(
    lambda x: (
        x["mean"].round(2).astype(str)
        + " ± "
        + x["std"].round(2).astype(str)
    ),
    axis=1
)
df_formatted

Metric                        Validity          LOF  Compactness    Proximity  \
Dataset      Model
GERMANCREDIT CACTUS        0.84 ± 0.05  1.09 ± 0.01  0.39 ± 0.02  0.66 ± 0.02
             CausalCACTUS  0.98 ± 0.03  1.06 ± 0.02  0.45 ± 0.04  0.57 ± 0.03
             LatentCF++      1.0 ± 0.0  1.09 ± 0.02  0.58 ± 0.02  0.37 ± 0.04
             Prototype C     1.0 ± 0.0  1.69 ± 0.07   0.1 ± 0.01  2.36 ± 0.03
             Prototype D     1.0 ± 0.0  1.51 ± 0.02  0.16 ± 0.02  1.67 ± 0.04

Metric                    Causal Validity (Hard) Causal Validity (Soft)  \
Dataset      Model
GERMANCREDIT CACTUS                  0.82 ± 0.04            0.89 ± 0.03
             CausalCACTUS            0.77 ± 0.05            0.87 ± 0.04
             LatentCF++              0.94 ± 0.01            0.97 ± 0.01
             Prototype C             0.99 ± 0.01            0.99 ± 0.01
             Prototype D             0.97 ± 0.02            0.98 ± 0.01

Metric                    Causal Compact Validity inlier_fraction
Dataset      Model
GERMANCREDIT CACTUS                   0.35 ± 0.02       1.0 ± 0.0
             CausalCACTUS              0.4 ± 0.04       1.0 ± 0.0
             LatentCF++               0.57 ± 0.02       1.0 ± 0.0
             Prototype C               0.1 ± 0.01      0.6 ± 0.03
             Prototype D              0.16 ± 0.02     0.63 ± 0.06

In [13]:
# TODO: One-hot encoding function for datasets with catergorical features
cat_idx = [2, 3, 4, 5] #    CheckingAccount", "Job", "Housing", "SavingAccounts"
num_idx = [0, 1]
X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])


# --- CF evaluation ---
cf_scores, cf_scores_labels = cf_eval(
    data.X_train, # previous name: data.X_train
    context_training, # previous name: context_training,
    X_test, # previous name: x,
    X_cf, # previous name: cf_x, 
    y_original_labels, # previous name: y_,
    context_test, # previous name: context,
    y_cf_labels, # previous name: cf_y_
    data.scaler_inverse_transform(X_test),
    data.scaler_inverse_transform(X_cf),
    child_to_parents_dict,
    cat_idx,
    num_idx
)

print(cf_scores, cf_scores_labels)

[0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1]
[0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 0 1]
0.96
0.9721729666029966 1.037178187546966 1.3707737209591775 50
[1.4037098890891124, 0.5730621625278489, 0.96, 0.43, 1.0564613794714903, 0.82, 0.9, 0.38666666666666666, 1.0] ['proximity', 'n_proximity', 'validity', 'compactness', 'lof_context', 'causal_validity_hard', 'causal_validity_soft', 'causal_compact_val', 'inlier_fraction']