In [1]:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="2,3"

%load_ext autoreload
%autoreload 2

In [2]:
import ipdb
from Data import *
from address import *
from modelGen import *
from utils import cf_eval, cleanup_gpu
from models import CausalCondLatentCF, latentCFpp, PrototypeLatentCF
from models import CondLatentCF # Note: get the vanilla CondLatentCF
import numpy as np
import random 
from tensorflow import random as tf_random
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from itertools import product
import argparse
import os
import pandas as pd

In [3]:
SEED = 23

os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf_random.set_seed(SEED)

CF_METHODS = {  
    "LatentCFpp": latentCFpp,
    "Prototype": PrototypeLatentCF,
    "CausalCACTUS": CausalCondLatentCF,
    "CACTUS": CondLatentCF
}

In [4]:
# Experimentos que a realizar
EXP = [
    {
        "name": "LatentCF++",
        "data": "HELOC",
        "classifier": "./exp/HELOC_class/config.json",
        "AE": "./exp/HELOC_AE/config.json",
        "CFmethod": "LatentCFpp",
        "context": [
            "MOpenAbove15years", 
            "MInFileAbove6years"
        ],
        "epochs": 100,
        "tol": 0.001,
        "target_prob": 0.5,
        "learning_rate": 0.1
    },
    {
        "name": "Prototype C",
        "data": "HELOC",
        "classifier": "./exp/HELOC_class/config.json",
        "AE": "./exp/HELOC_AE/config.json",
        "CFmethod": "Prototype",
        "context": [
            "MOpenAbove15years", 
            "MInFileAbove6years"
        ],
        "epochs": 100,
        "kappa": 0.0,
        "c": 1.0,
        "c_steps": 1,
        "beta": 0.1,
        "gamma": 0.0,
        "theta": 100.0,
        "clip": [
            -1000,
            1000
        ],
        "feat_range": [
            -4,
            4
        ],
        "lr": 0.01
    },
    {
        "name": "Prototype D",
        "data": "HELOC",
        "classifier": "./exp/HELOC_class/config.json",
        "AE": "./exp/HELOC_AE/config.json",
        "CFmethod": "Prototype",
        "context": [
            "MOpenAbove15years", 
            "MInFileAbove6years"
        ],
        "epochs": 100,
        "kappa": 0.0,
        "c": 1.0,
        "c_steps": 1,
        "beta": 0.1,
        "gamma": 100.0,
        "theta": 100.0,
        "clip": [
            -1000,
            1000
        ],
        "feat_range": [
            -4,
            4
        ],
        "lr": 0.01
    },
    {
        "name": "CACTUS",
        "data": "HELOC",
        "classifier": "./exp/HELOC_class/config.json",
        "AE": "./exp/HELOC_CACTUS/config.json",
        "CFmethod": "CACTUS",
        "context": [
            "MOpenAbove15years", 
            "MInFileAbove6years"
        ],
        "epochs": 300,
        "target_prob": 0.5,
        # "learning_rate": 0.005,
        "learning_rate": 0.01,
        "power": 0.5,
        "alpha": 0.7,
        "gamma": 0.1,
        "beta": 0.01,
        # "dynamicAlpha": True
        "dynamicAlpha": False
    },
    {
        "name": "CausalCACTUS",
        "data": "HELOC",
        "classifier": "./exp/HELOC_class/config.json",
        "AE": "./exp/HELOC_CACTUS/config.json",
        "CFmethod": "CausalCACTUS",
        "context": [
            "MOpenAbove15years", 
            "MInFileAbove6years"
        ],
        "epochs": 300,
        "target_prob": 0.5,
        # "learning_rate": 0.005,
        "learning_rate": 0.01,
        "power": 0.5,
        "alpha": 0.7,
        "gamma": 0.1,
        "beta": 0.01,
        "dynamicAlpha": True
        # "dynamicAlpha": False
    }
]

In [5]:
import re
from collections import defaultdict
# TODO: make a function to convert the causal paths for all the test samples
def build_causal_index_map(input_features, graph_str):
    """
    Returns:
        child_to_parents: dict {child_idx: [parent_idx, ...]}
        parent_to_children: dict {parent_idx: [child_idx, ...]}
        feat2idx: dict {feature_name: index}
    """

    # Feature name to index
    feat2idx = {f: i for i, f in enumerate(input_features)}

    # Extract edges using regex
    edges = re.findall(r'(\w+)\s*->\s*(\w+)', graph_str)

    child_to_parents = defaultdict(list)
    parent_to_children = defaultdict(list)

    for parent, child in edges:

        if parent not in feat2idx or child not in feat2idx:
            raise ValueError(f"Feature in graph not found in dataset: {parent} or {child}")

        p_idx = feat2idx[parent]
        c_idx = feat2idx[child]

        child_to_parents[c_idx].append(p_idx)
        parent_to_children[p_idx].append(c_idx)

    return dict(child_to_parents), dict(parent_to_children), feat2idx


# credit_rex5_constraints_min.dot
graph_str1 = """
strict digraph {
NumRevolvingTradesWBalance;
MaxDelqEver;
NumSatisfactoryTrades;
MSinceMostRecentInqexcl7days;
NumTotalTrades;
NumTrades90Ever2DerogPubRec;
NetFractionRevolvingBurden;
PercentInstallTrades;
MaxDelq2PublicRecLast12M;
MSinceMostRecentDelq;
PercentTradesNeverDelq;
MSinceOldestTradeOpen;
NumTradesOpeninLast12M;
NetFractionInstallBurden;
AverageMInFile;
PercentTradesWBalance;
NumTrades60Ever2DerogPubRec;
NumInqLast6M;
NumBank2NatlTradesWHighUtilization;
NumInstallTradesWBalance;
NumSatisfactoryTrades -> MaxDelq2PublicRecLast12M;
MSinceMostRecentInqexcl7days -> NumTradesOpeninLast12M;
MSinceMostRecentInqexcl7days -> NumBank2NatlTradesWHighUtilization;
MSinceMostRecentInqexcl7days -> NumRevolvingTradesWBalance;
MSinceMostRecentInqexcl7days -> PercentTradesWBalance;
NumTotalTrades -> PercentTradesWBalance;
NumTrades90Ever2DerogPubRec -> PercentTradesNeverDelq;
NumTrades90Ever2DerogPubRec -> MaxDelq2PublicRecLast12M;
NetFractionRevolvingBurden -> PercentInstallTrades;
NetFractionRevolvingBurden -> NumRevolvingTradesWBalance;
NetFractionRevolvingBurden -> PercentTradesWBalance;
PercentTradesNeverDelq -> MSinceMostRecentDelq;
PercentTradesNeverDelq -> MaxDelq2PublicRecLast12M;
PercentTradesNeverDelq -> MaxDelqEver;
NetFractionInstallBurden -> NetFractionRevolvingBurden;
NetFractionInstallBurden -> PercentTradesWBalance;
PercentTradesWBalance -> NumTradesOpeninLast12M;
NumTrades60Ever2DerogPubRec -> MaxDelqEver;
NumInqLast6M -> MaxDelqEver;
NumInqLast6M -> NumTradesOpeninLast12M;
NumBank2NatlTradesWHighUtilization -> NetFractionRevolvingBurden;
NumInstallTradesWBalance -> NumTotalTrades;
NumInstallTradesWBalance -> PercentInstallTrades;
NumInstallTradesWBalance -> NumInqLast6M;
NumInstallTradesWBalance -> NetFractionRevolvingBurden;
NumInstallTradesWBalance -> NumRevolvingTradesWBalance;
}
"""

# adult_rex6_constraints_mod.dot
graph_str2 = """
strict digraph {
NumRevolvingTradesWBalance;
MaxDelqEver;
NumSatisfactoryTrades;
MSinceMostRecentInqexcl7days;
NumTotalTrades;
NumTrades90Ever2DerogPubRec;
NetFractionRevolvingBurden;
PercentInstallTrades;
MaxDelq2PublicRecLast12M;
MSinceMostRecentDelq;
PercentTradesNeverDelq;
MSinceOldestTradeOpen;
NumTradesOpeninLast12M;
NetFractionInstallBurden;
AverageMInFile;
PercentTradesWBalance;
NumTrades60Ever2DerogPubRec;
NumInqLast6M;
NumBank2NatlTradesWHighUtilization;
NumInstallTradesWBalance;
NumRevolvingTradesWBalance -> MaxDelq2PublicRecLast12M;
NumSatisfactoryTrades -> MaxDelqEver;
MSinceMostRecentInqexcl7days -> NumBank2NatlTradesWHighUtilization;
MSinceMostRecentInqexcl7days -> PercentTradesWBalance;
NetFractionRevolvingBurden -> NumInqLast6M;
PercentInstallTrades -> MaxDelqEver;
MSinceMostRecentDelq -> MSinceMostRecentInqexcl7days;
MSinceMostRecentDelq -> NumInqLast6M;
PercentTradesNeverDelq -> PercentTradesWBalance;
NetFractionInstallBurden -> MSinceMostRecentInqexcl7days;
NetFractionInstallBurden -> NetFractionRevolvingBurden;
PercentTradesWBalance -> NumTradesOpeninLast12M;
PercentTradesWBalance -> MaxDelqEver;
PercentTradesWBalance -> NumInqLast6M;
NumBank2NatlTradesWHighUtilization -> MaxDelqEver;
}
"""

# # CF generation
# child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
#     data.features_lbls,
#     # graph_str
#     graph_str1
# )
# print("Feature → index:")
# print(feat2idx)
# print("\nChild → Parents (index form):")
# print(child_to_parents_dict)

In [6]:
# data.features_lbls

## Graph 1 (Minimum priors)

In [7]:
N = 50
N_BOOTSTRAP = 5
# SEED_list = [23] * N_BOOTSTRAP
SEED_list = [12, 23, 34, 45, 56]

# Number of samples to compute the metrics for CF evaluation
METRICS = []

for i, exp in enumerate(EXP):
    print("\n" * 2)
    print("*" * 200)
    print(f"Running exp: {exp['name']} ({i}/{len(EXP)})")
    print("*" * 200)
    print("\n" * 2)
    
    # Reading the data
    CLASS_CONFIG_PATH = exp["classifier"]
    AE_CONFIG_PATH = exp["AE"]

    class_config = get_exp_config(CLASS_CONFIG_PATH)
    print("Reading data")
    data = getData(class_config)

    # Getting classifier
    classifier = modelGen(class_config["type"], data, params=class_config, debug=True)
    classifier.load()

    # Getting AE-based Model
    AE_config = get_exp_config(AE_CONFIG_PATH)
    aeModel = modelGen(AE_config["type"], data, params=AE_config, debug=True)
    aeModel.load()

    # CF generation
    child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
        data.features_lbls,
        # TODO: change the string below for graph_str1 and graph_str2
        graph_str1
    )
    print("Feature → index:")
    print(feat2idx)
    print("\nChild → Parents (index form):")
    print(child_to_parents_dict)
    
    if exp["name"] == "CausalCACTUS":
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train,
            x_min=data.X_train.min(axis=0),
            x_max=data.X_train.max(axis=0),
            causal_index_map=child_to_parents_dict
        )
    else:
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train
        )

    for trial in range(N_BOOTSTRAP):

        # --- Sampling test data ---
        SEED = SEED_list[trial]
        os.environ['PYTHONHASHSEED'] = str(SEED)
        random.seed(SEED)
        np.random.seed(SEED)
        tf_random.set_seed(SEED)
        rand_idx = np.random.choice(len(data.X_test), N, replace=True)
        
        # previous name: x
        X_test = data.X_test[rand_idx, ...]
        # previous name: contest
        context_test = data.context_test[exp['context']].values
        context_test = context_test[rand_idx, ...]

        context_training = data.context_train[exp['context']].values

        # previous name: y
        y_test = np.argmax(data.y_test[rand_idx, ...], axis=1)
        y_original_logits = classifier.predict(X_test)
        # previous name: y_
        y_original_labels = np.argmax(y_original_logits, axis=1)

        # --- CF generation ---
        # previous names: 
        # cf_x, cf_y_, x, __
        X_cf, y_cf_labels, X_internal, y_internal = CF_method.transform(
            X_test,
            y_original_labels,
            target_context=context_test,
            verbose=0
        )              

        # # TODO: One-hot encoding function for datasets with catergorical features
        # cat_idx = [2, 3, 4, 5] #    CheckingAccount", "Job", "Housing", "SavingAccounts"
        # num_idx = [0, 1]
        # X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])
        
        # --- CF evaluation ---
        cf_scores, cf_scores_labels = cf_eval(
            data.X_train, # previous name: data.X_train
            context_training, # previous name: context_training,
            X_test, # previous name: x,
            X_cf, # previous name: cf_x, 
            y_original_labels, # previous name: y_,
            context_test, # previous name: context,
            y_cf_labels, # previous name: cf_y_
            data.scaler_inverse_transform(X_test),
            data.scaler_inverse_transform(X_cf),
            child_to_parents_dict
            # cat_idx,
            # num_idx
        )

        for i_metric, label in enumerate(cf_scores_labels):
            METRICS.append([
                exp["name"],
                exp["data"],
                exp["CFmethod"],
                label,
                cf_scores[i_metric]
            ])

    # Cleaning GPU models
    cleanup_gpu()

# --- Metrics aggregation ---
df_metrics = pd.DataFrame(
    data=METRICS,
    columns=["Model", "Dataset", "CFMethod", "Metric", "Value"]
)
df_metrics = df_metrics.round(3)
print(df_metrics)

********************************************************************************************************************************************************************************************************
Running exp: LatentCF++ (0/5)
********************************************************************************************************************************************************************************************************



Reading data
MOpenAbove15years
0    5387
1    5072
Name: count, dtype: int64
MInFileAbove6years
1    5389
0    5070
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 10000
Positive class: 5000.0
Context 'MOpenAbove15years=1': 4885
Context 'MInFileAbove6years=1': 5198
----------------------------------------------------------------------------------------------------




Building model

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:139: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MOpenAbove15years"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:140: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MInFileAbove6years"]))

Building model: DNN [class]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 dense (Dense)               (None, 64)                1216

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,970
Trainable params: 35,202
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: HELOC_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 model_1 (Functional)        (None, 16)                4816

 model_2 (Functional)        (None, 18)                4818

=================================================================
Total params: 9,634
Trainable params: 9,634
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: HELOC_AE
Feature → index:
{'NumSatisfactoryTrades': 0, 'NumTrades60Ever2DerogPubRec': 1, 'NumTrades90Ever2DerogPubRec': 2, 'PercentTradesNeverDelq': 3, 'MSinceMostRecentDelq': 4, 'MaxDelq2PublicRecLast12M': 5, 'MaxDelqEver': 6, 'NumTotalTrades': 7, 'NumTradesOpeninLast12M': 8, 'PercentInstallTrades': 9, 'MSinceMostRecentInqexcl7days': 10, 'NumInqLast6M': 11, 'NetFractionRevolvingBurden': 12, 'NetFractionInstallBurden': 13, 'NumRevolvingTradesWBalance': 14, 'NumInstallTradesWBalance': 15, 'NumBank2NatlTradesWHighUtilization': 16, 'PercentTradesWBalance': 17}

Child → Parents (index form):
{5: [0, 2, 3], 8: [10, 17, 11], 16: [10], 14: [10, 12, 15], 17: [10, 7, 12, 13], 3: [2], 9: [12, 15], 4: [3], 6: [3, 1, 11], 12: [13, 16, 15], 7: [15], 11: [15]}
Building model: latentCF [CF]
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 16)]              0

 model_2 (Functional)        (None, 18)                4818

 model (Functional)          (None, 2)                 35970

=================================================================
Total params: 40,788
Trainable params: 40,020
Non-trainable params: 768
_________________________________________________________________
2/2 [==============================] - 1s 4ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 0 0 0 0]
[1 0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (22, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9795758842629853 3.45274177321068
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (5, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9823691959067146 1.5566806077300914
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.0203072944333897 1.2970658281601484
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (16, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.0090957787354642 1.8218859716466391
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9795758842629853 1.0792243774505095 3.45274177321068 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1
 1 0 1 0 0 1 1 1 0 1 1 1 1]
[0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1
 1 0 1 0 0 1 1 1 0 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (19, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.0049733740901425 3.6246668935414066
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (3, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.0273647977029696 1.2708477963033986
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9870684646795043 1.3295635563292647
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (21, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9909209210025695 1.8400169529769297
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9870684646795043 1.1117928270100608 3.6246668935414066 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 1 1 0 0]
[0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 1 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (19, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.99420530157649 3.458733352837829
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.0437185034779635 1.6418681709381926
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (5, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9971832153567189 1.5894976059820254
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (19, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.0134386653796008 1.643135227861327
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.99420530157649 1.1628625161299302 3.458733352837829 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 0 0 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 1 0 1]
[0 0 0 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (16, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.0500936483729002 3.559538227451951
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (10, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.0040860382679218 1.4891741670506191
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (6, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.0307806602296403 1.371243297017048
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (18, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.003100957260115 1.630112825014617
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.003100957260115 1.139241705591781 3.559538227451951 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1
 1 1 1 1 1 1 1 0 0 0 1 0 1]
[0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1
 1 1 1 1 1 1 1 0 0 0 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (21, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9987420429725141 3.455159312712501
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (8, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.10297632490007 1.5763148817396126
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (4, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.1172074285835147 1.6397048526351878
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (17, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.0132767248295587 1.554203669334528
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9987420429725141 1.160573544309018 3.455159312712501 50



********************************************************************************************************************************************************************************************************
Running exp: Prototype C (1/5)
********************************************************************************************************************************************************************************************************



Reading data
MOpenAbove15years
0    5387
1    5072
Name: count, dtype: int64
MInFileAbove6years
1    5389
0    5070
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 10000
Positive class: 5000.0
Context 'MOpenAbove15years=1': 4885
Context 'MInFileAbove6years=1': 5198
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:139: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MOpenAbove15years"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:140: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MInFileAbove6years"]))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 dense (Dense)               (None, 64)                1216

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,970
Trainable params: 35,202
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: HELOC_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 model_1 (Functional)        (None, 16)                4816

 model_2 (Functional)        (None, 18)                4818

=================================================================
Total params: 9,634
Trainable params: 9,634
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: HELOC_AE
Feature → index:
{'NumSatisfactoryTrades': 0, 'NumTrades60Ever2DerogPubRec': 1, 'NumTrades90Ever2DerogPubRec': 2, 'PercentTradesNeverDelq': 3, 'MSinceMostRecentDelq': 4, 'MaxDelq2PublicRecLast12M': 5, 'MaxDelqEver': 6, 'NumTotalTrades': 7, 'NumTradesOpeninLast12M': 8, 'PercentInstallTrades': 9, 'MSinceMostRecentInqexcl7days': 10, 'NumInqLast6M': 11, 'NetFractionRevolvingBurden': 12, 'NetFractionInstallBurden': 13, 'NumRevolvingTradesWBalance': 14, 'NumInstallTradesWBalance': 15, 'NumBank2NatlTradesWHighUtilization': 16, 'PercentTradesWBalance': 17}

Child → Parents (index form):
{5: [0, 2, 3], 8: [10, 17, 11], 16: [10], 14: [10, 12, 15], 17: [10, 7, 12, 13], 3: [2], 9: [12, 15], 4: [3], 6: [3, 1, 11], 12: [13, 16, 15], 7: [15], 11: [15]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
WARNING:tensorflow:AutoGraph could not transform <bound method PrototypeLatentCF._loss of <tensorflow.python.eager.function.TfMethodTarget object at 0x7fa6343deaf0>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <bound method PrototypeLatentCF._loss of <tensorflow.python.eager.function.TfMethodTarget object at 0x7fa6343deaf0>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[1 0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 0 0 0 0]
[1 0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (22, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.0752531602288546 4.252994111100521
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (5, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.8594912151142742 2.634177542395074
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.3515909557705958 3.156751406984917
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (16, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.378579222518112 3.218402051772488
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.0752531602288546 2.179017536443987 4.252994111100521 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1
 1 0 1 0 0 1 1 1 0 1 1 1 1]
[0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1
 1 0 1 0 0 1 1 1 0 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (19, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.4625507920329603 4.252994111100521
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (3, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.6834432002505404 2.8658982971386964
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.3634416546314565 2.8874887746623887
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (21, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.1959185729807356 3.5834760749502625
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.1959185729807356 2.1578693967230054 4.252994111100521 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 1 1 0 0]
[0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 1 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (19, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.1806729277532388 4.252994111100521
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.9068545359774756 2.8104094384476492
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (5, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.7555192850336976 2.695712499866614
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (19, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.1975004530796285 3.8028032504123277
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.1806729277532388 2.3055373829669374 4.252994111100521 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 1 0 1]
[0 0 0 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (16, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.144826782937448 4.252994111100521
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (10, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.4992541696828627 2.6617858121316433
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (6, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.3634416546314565 2.458259597645635
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (18, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.2938589963029692 3.2888547644494976
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.144826782937448 2.1821028160160427 4.252994111100521 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1
 1 1 1 1 1 1 1 0 0 0 1 0 1]
[0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1
 1 1 1 1 1 1 1 0 0 0 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (21, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.412025673013795 4.252994111100521
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (8, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.648370825835714 2.8155337959760205
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (4, 18)
X_ shape: (766, 18)
lof_cf min/max: 2.3289933192512757 3.094617808855575
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (17, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.3187069195811307 3.5893815484720903
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.3187069195811307 2.16237808223378 4.252994111100521 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype D (2/5)
********************************************************************************************************************************************************************************************************



Reading data
MOpenAbove15years
0    5387
1    5072
Name: count, dtype: int64
MInFileAbove6years
1    5389
0    5070
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 10000
Positive class: 5000.0
Context 'MOpenAbove15years=1': 4885
Context 'MInFileAbove6years=1': 5198
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:139: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MOpenAbove15years"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:140: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MInFileAbove6years"]))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 dense (Dense)               (None, 64)                1216

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,970
Trainable params: 35,202
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: HELOC_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 model_1 (Functional)        (None, 16)                4816

 model_2 (Functional)        (None, 18)                4818

=================================================================
Total params: 9,634
Trainable params: 9,634
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: HELOC_AE
Feature → index:
{'NumSatisfactoryTrades': 0, 'NumTrades60Ever2DerogPubRec': 1, 'NumTrades90Ever2DerogPubRec': 2, 'PercentTradesNeverDelq': 3, 'MSinceMostRecentDelq': 4, 'MaxDelq2PublicRecLast12M': 5, 'MaxDelqEver': 6, 'NumTotalTrades': 7, 'NumTradesOpeninLast12M': 8, 'PercentInstallTrades': 9, 'MSinceMostRecentInqexcl7days': 10, 'NumInqLast6M': 11, 'NetFractionRevolvingBurden': 12, 'NetFractionInstallBurden': 13, 'NumRevolvingTradesWBalance': 14, 'NumInstallTradesWBalance': 15, 'NumBank2NatlTradesWHighUtilization': 16, 'PercentTradesWBalance': 17}

Child → Parents (index form):
{5: [0, 2, 3], 8: [10, 17, 11], 16: [10], 14: [10, 12, 15], 17: [10, 7, 12, 13], 3: [2], 9: [12, 15], 4: [3], 6: [3, 1, 11], 12: [13, 16, 15], 7: [15], 11: [15]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[1 0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 0 0 0 0]
[1 0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 0 0 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (22, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.0177545915247306 2.3687950739261128
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (5, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.0889253215765238 1.7596604007912673
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.196603101795535 2.3301565749468334
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (16, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.0658385222648377 1.9651977236897984
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.0177545915247306 1.514175770549344 2.3687950739261128 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1
 1 0 1 0 0 1 1 1 0 1 1 1 1]
[0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1
 1 0 1 0 0 1 1 1 0 1 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (19, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.212172282489273 2.7525719157558983
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (3, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.0864881634466272 1.7209303997173555
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.1657444846179412 2.3301565749468334
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (21, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.2201532501476247 1.9847006191466992
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.0864881634466272 1.5379613324419394 2.7525719157558983 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 1 1 0 0]
[0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 1 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (19, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.1631127443603382 2.3371422090698415
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.0854512768262765 2.1101910383362537
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (5, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.3877742584507982 2.3301565749468334
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (19, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.1471303679847624 2.795620789173778
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.0854512768262765 1.6504363950116165 2.795620789173778 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 1 0 1]
[0 0 0 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (16, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.049418940525401 2.7525719157558983
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (10, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.020244332100829 1.4540216606384666
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (6, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.2985289265626363 1.6715960577144235
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (18, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.1108838217704227 2.1855221155335465
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.020244332100829 1.478935228576817 2.7525719157558983 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1
 1 1 1 1 1 1 1 0 0 0 1 0 1]
[0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1
 1 1 1 1 1 1 1 0 0 0 1 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (21, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.0730037016168785 2.3371422090698415
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (8, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.1749853499357543 2.237851573282414
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (4, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.1888873132825264 1.9662811349833131
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (17, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.214845718481892 2.1088314695836665
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.0730037016168785 1.6123480313855447 2.3371422090698415 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CACTUS (3/5)
********************************************************************************************************************************************************************************************************



Reading data
MOpenAbove15years
0    5387
1    5072
Name: count, dtype: int64
MInFileAbove6years
1    5389
0    5070
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 10000
Positive class: 5000.0
Context 'MOpenAbove15years=1': 4885
Context 'MInFileAbove6years=1': 5198
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:139: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MOpenAbove15years"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:140: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MInFileAbove6years"]))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 dense (Dense)               (None, 64)                1216

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,970
Trainable params: 35,202
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: HELOC_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 18)]         0           []

 model_1 (Functional)           (None, 4)            1796        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 18)           1810        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 3,616
Trainable params: 3,616
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: HELOC_CACTUS
Feature → index:
{'NumSatisfactoryTrades': 0, 'NumTrades60Ever2DerogPubRec': 1, 'NumTrades90Ever2DerogPubRec': 2, 'PercentTradesNeverDelq': 3, 'MSinceMostRecentDelq': 4, 'MaxDelq2PublicRecLast12M': 5, 'MaxDelqEver': 6, 'NumTotalTrades': 7, 'NumTradesOpeninLast12M': 8, 'PercentInstallTrades': 9, 'MSinceMostRecentInqexcl7days': 10, 'NumInqLast6M': 11, 'NetFractionRevolvingBurden': 12, 'NetFractionInstallBurden': 13, 'NumRevolvingTradesWBalance': 14, 'NumInstallTradesWBalance': 15, 'NumBank2NatlTradesWHighUtilization': 16, 'PercentTradesWBalance': 17}

Child → Parents (index form):
{5: [0, 2, 3], 8: [10, 17, 11], 16: [10], 14: [10, 12, 15], 17: [10, 7, 12, 13], 3: [2], 9: [12, 15], 4: [3], 6: [3, 1, 11], 12: [13, 16, 15], 7: [15], 11: [15]}
Building model: CondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 18)                1810

 model (Functional)          (None, 2)                 35970

=================================================================
Total params: 37,780
Trainable params: 0
Non-trainable params: 37,780
_________________________________________________________________
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[1 0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 0 0 0 0]
[1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 1 0 0
 1 1 1 1 0 0 1 1 0 1 0 1 0]
0.56
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (22, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9479157885327562 3.803479820949607
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (5, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9781316861684551 1.1068252777880516
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9684252349674675 1.188045541745844
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (16, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9662153865155251 1.3668967365135793
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9479157885327562 1.0025221464959602 3.803479820949607 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1
 1 0 1 0 0 1 1 1 0 1 1 1 1]
[0 1 1 1 1 1 0 1 1 1 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 0 1 1 1 0 0 0 1
 1 1 1 0 1 1 1 0 1 1 1 1 1]
0.52
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (19, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9507610174399503 3.803479820949607
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (3, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9816252952333283 1.0555960042055137
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9555954922147684 1.1233441383555294
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (21, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9662153865155251 1.5454208965079803
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9507610174399503 1.0042883616273204 3.803479820949607 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 1 1 0 0]
[1 1 1 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 1
 1 0 0 0 0 0 0 1 1 1 0 0 1]
0.54
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (19, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9787703788817599 3.803479820949607
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9631322645565153 1.1068649807529927
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (5, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.951107039794823 1.159013354641994
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (19, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9807811376817583 1.4064961269130631
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.951107039794823 1.0192638453623306 3.803479820949607 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 1 0 1]
[1 1 1 0 1 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 1
 1 0 0 1 1 1 1 1 0 0 0 1 1]
0.54
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (16, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9566402894108815 3.803479820949607
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (10, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9507900985598922 1.2095048119065757
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (6, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9667117402835884 1.188045541745844
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (18, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9773884596779627 1.2575571539221384
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9507900985598922 1.006994915452848 3.803479820949607 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1
 1 1 1 1 1 1 1 0 0 0 1 0 1]
[1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 1]
0.54
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (21, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9694312778393483 3.803479820949607
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (8, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9763319257585913 1.0965180944296984
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (4, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.0137091299567718 1.4578351708652055
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (17, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9657565535841665 1.6225746135674655
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9657565535841665 1.022946864153833 3.803479820949607 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CausalCACTUS (4/5)
********************************************************************************************************************************************************************************************************



Reading data
MOpenAbove15years
0    5387
1    5072
Name: count, dtype: int64
MInFileAbove6years
1    5389
0    5070
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 10000
Positive class: 5000.0
Context 'MOpenAbove15years=1': 4885
Context 'MInFileAbove6years=1': 5198
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:139: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MOpenAbove15years"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:140: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MInFileAbove6years"]))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 dense (Dense)               (None, 64)                1216

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,970
Trainable params: 35,202
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: HELOC_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 18)]         0           []

 model_1 (Functional)           (None, 4)            1796        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 18)           1810        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 3,616
Trainable params: 3,616
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: HELOC_CACTUS
Feature → index:
{'NumSatisfactoryTrades': 0, 'NumTrades60Ever2DerogPubRec': 1, 'NumTrades90Ever2DerogPubRec': 2, 'PercentTradesNeverDelq': 3, 'MSinceMostRecentDelq': 4, 'MaxDelq2PublicRecLast12M': 5, 'MaxDelqEver': 6, 'NumTotalTrades': 7, 'NumTradesOpeninLast12M': 8, 'PercentInstallTrades': 9, 'MSinceMostRecentInqexcl7days': 10, 'NumInqLast6M': 11, 'NetFractionRevolvingBurden': 12, 'NetFractionInstallBurden': 13, 'NumRevolvingTradesWBalance': 14, 'NumInstallTradesWBalance': 15, 'NumBank2NatlTradesWHighUtilization': 16, 'PercentTradesWBalance': 17}

Child → Parents (index form):
{5: [0, 2, 3], 8: [10, 17, 11], 16: [10], 14: [10, 12, 15], 17: [10, 7, 12, 13], 3: [2], 9: [12, 15], 4: [3], 6: [3, 1, 11], 12: [13, 16, 15], 7: [15], 11: [15]}
Building model: CausalCondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 18)                1810

 model (Functional)          (None, 2)                 35970

=================================================================
Total params: 37,780
Trainable params: 0
Non-trainable params: 37,780
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
[1 0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 0 0 0 0]
[1 0 1 0 0 0 1 0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 0 1 1 1 0 1
 1 1 1 1 0 1 1 1 0 1 0 0 0]
0.82
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (22, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9497452079300764 3.753302927545895
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (5, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9771266982178293 1.0876671348244182
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9740782634841851 1.0867914395612734
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (16, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9774439050583051 1.3762496349712074
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9497452079300764 1.0024337777835637 3.753302927545895 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1
 1 0 1 0 0 1 1 1 0 1 1 1 1]
[0 1 1 1 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 1 0 1 0 1 1 1 1 0 1 1 1 1]
0.76
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (19, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9529663683233399 3.753302927545895
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (3, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9904106056810643 1.0367588582049971
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9740782634841851 1.1856875523660444
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (21, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9774632026338012 1.2747196280499176
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9529663683233399 1.0159443073983438 3.753302927545895 50
2/2 [==============================] - 0s 3ms/step
[0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0
 1 0 0 0 0 0 0 0 0 1 1 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0
 1 0 0 0 0 0 0 1 1 1 0 0 0]
0.78
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (19, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9665879666027054 3.753302927545895
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9786551531805343 1.1024445949634578
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (5, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9733902256061832 1.1145983024869677
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (19, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9734462826340575 1.407121111952445
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9665879666027054 1.027758014716003 3.753302927545895 50
2/2 [==============================] - 0s 3ms/step
[0 0 0 0 1 1 0 1 0 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 1 0 1]
[1 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 1 0 0 0 0 0 1]
0.72
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (16, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9627916052546991 3.753302927545895
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (10, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9786551531805343 1.1720368238511936
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (6, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9650142200713 1.0474521919840636
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (18, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.98877658356068 1.2495798160223435
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9627916052546991 1.023917042008263 3.753302927545895 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1
 1 1 1 1 1 1 1 0 0 0 1 0 1]
[0 1 0 1 1 0 0 1 1 1 0 1 0 1 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 0
 0 1 1 0 0 1 1 0 1 0 1 0 1]
0.74
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (21, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9669658922228529 3.753302927545895
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (8, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9658655732488753 1.2721821422283197
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (4, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.0063745953187482 1.3306200370188535
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (17, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9735141183415185 1.1838412520484378
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9658655732488753 1.031992299123687 3.753302927545895 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
            Model Dataset      CFMethod                Metric  Value
0      LatentCF++   HELOC    LatentCFpp             proximity  1.608
1      LatentCF++   HELOC    LatentCFpp           n_proximity  0.379
2      LatentCF++   HELOC    LatentCFpp              validity  1.000
3      LatentCF++   HELOC    LatentCFpp           compactness  0.039
4      LatentCF++   HELOC    LatentCFpp           lof_context  1.199
..            ...     ...           ...                   ...    ...
220  CausalCACTUS   HELOC  CausalCACTUS           lof_context  1.229
221  CausalCACTUS   HELOC  CausalCACTUS  causal_validity_hard  0.400
222  CausalCACTUS   HELOC  CausalCACTUS  causal_validity_soft  0.927
223  CausalCACTUS   HELOC  CausalCACTUS    causal_compact_val  0.389
224  CausalCACTUS   HELOC  CausalCACTUS       inlier_fraction  0.964

[225 rows x 5 columns]

In [8]:
child_to_parents_dict

{5: [0, 2, 3],
 8: [10, 17, 11],
 16: [10],
 14: [10, 12, 15],
 17: [10, 7, 12, 13],
 3: [2],
 9: [12, 15],
 4: [3],
 6: [3, 1, 11],
 12: [13, 16, 15],
 7: [15],
 11: [15]}

In [9]:
df_metrics

            Model Dataset      CFMethod                Metric  Value
0      LatentCF++   HELOC    LatentCFpp             proximity  1.608
1      LatentCF++   HELOC    LatentCFpp           n_proximity  0.379
2      LatentCF++   HELOC    LatentCFpp              validity  1.000
3      LatentCF++   HELOC    LatentCFpp           compactness  0.039
4      LatentCF++   HELOC    LatentCFpp           lof_context  1.199
..            ...     ...           ...                   ...    ...
220  CausalCACTUS   HELOC  CausalCACTUS           lof_context  1.229
221  CausalCACTUS   HELOC  CausalCACTUS  causal_validity_hard  0.400
222  CausalCACTUS   HELOC  CausalCACTUS  causal_validity_soft  0.927
223  CausalCACTUS   HELOC  CausalCACTUS    causal_compact_val  0.389
224  CausalCACTUS   HELOC  CausalCACTUS       inlier_fraction  0.964

[225 rows x 5 columns]

In [10]:
# Pivoting the dataframe
df_metrics_pivot = df_metrics.pivot_table(
    index=["Dataset", "Model"],
    columns="Metric",
    values="Value",
    aggfunc=['mean', 'std']
)

desired_order = [
    "validity",
    "lof_context",
    "compactness",
    "n_proximity",
    "causal_validity_hard",
    "causal_validity_soft",
    "causal_compact_val",
    "inlier_fraction"
]
df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)
df_metrics_pivot = df_metrics_pivot[desired_order]

df_metrics_pivot.rename(
    columns={
        "validity": "Validity",
        "lof_context": "LOF",
        "compactness": "Compactness",
        "n_proximity": "Proximity",
        "causal_validity_hard": "Causal Validity (Hard)",
        "causal_validity_soft": "Causal Validity (Soft)",
        "causal_compact_val": "Causal Compact Validity",
        "inlier_fraction": "inlier_fraction"
    },
    inplace=True
)

df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)

# df_formatted = df_metrics_pivot.apply(
#     lambda x: x["mean"].map("${:2.2f}".format)
#     + " \\pm "
#     + x["std"].map("{:2.2f} $".format),
#     axis=1
# )
# df_formatted

df_formatted = df_metrics_pivot.apply(
    lambda x: (
        x["mean"].round(2).astype(str)
        + " ± "
        + x["std"].round(2).astype(str)
    ),
    axis=1
)
df_formatted

Metric                   Validity          LOF  Compactness    Proximity  \
Dataset Model
HELOC   CACTUS        0.54 ± 0.01  1.22 ± 0.08  0.08 ± 0.03  0.49 ± 0.04
        CausalCACTUS  0.76 ± 0.04  1.22 ± 0.08  0.27 ± 0.04  0.39 ± 0.03
        LatentCF++      1.0 ± 0.0  1.32 ± 0.08  0.04 ± 0.01  0.45 ± 0.04
        Prototype C     1.0 ± 0.0  2.32 ± 0.06  0.05 ± 0.01  1.29 ± 0.03
        Prototype D     1.0 ± 0.0  1.62 ± 0.04  0.02 ± 0.01  1.08 ± 0.04

Metric               Causal Validity (Hard) Causal Validity (Soft)  \
Dataset Model
HELOC   CACTUS                  0.22 ± 0.04             0.9 ± 0.01
        CausalCACTUS            0.38 ± 0.06            0.93 ± 0.01
        LatentCF++              0.06 ± 0.03            0.88 ± 0.01
        Prototype C              0.7 ± 0.09            0.96 ± 0.01
        Prototype D              0.7 ± 0.07            0.97 ± 0.01

Metric               Causal Compact Validity inlier_fraction
Dataset Model
HELOC   CACTUS                   0.21 ± 0.03     0.95 ± 0.02
        CausalCACTUS             0.37 ± 0.03     0.96 ± 0.02
        LatentCF++               0.16 ± 0.01     0.88 ± 0.04
        Prototype C              0.09 ± 0.01     0.09 ± 0.07
        Prototype D              0.06 ± 0.01     0.46 ± 0.09

In [11]:
print(data.scaler_inverse_transform(X_test))
print(data.scaler_inverse_transform(X_cf))

[[ 34.   1.   0.  97.  30.   6.   5.  45.   6.  11.   0.   2.  11.  88.
    6.   2.   1.  33.]
 [ 32.   1.   0.  82.   5.   4.   5.  33.   4.  39.   0.   1.  43. 101.
    5.   4.   0.  90.]
 [  6.   0.   0. 100.  -7.   7.   8.  14.   1.  33.   3.   2.  14.  -8.
    1.  -8.   0.  33.]
 [ 28.   4.   4.  97.  56.   6.   4.  31.   8.  29.  -7.   4.  54.  58.
    6.   2.   0.  71.]
 [  4.   2.   2.  88.  23.   6.   4.   8.   4.  88.   2.   1.  -8. 103.
   -8.   4.  -8. 100.]
 [ 16.   0.   0. 100.  -7.   7.   8.  17.   1.  35.   0.   1.   6.  -8.
    7.  -8.   0. 100.]
 [ 14.   0.   0.  93.  -7.   6.   7.  15.   0.  47.  11.   0.  11.  -8.
    1.   2.   0.  75.]
 [ 24.   0.   0.  92.   5.   4.   6.  24.   2.  38.   0.   6.  57.  90.
    9.   3.   2.  86.]
 [ 24.   0.   0. 100.  -7.   7.   8.  27.   2.  26.   0.   2.   2.  76.
    2.   2.   0.  50.]
 [ 26.   0.   0. 100.  -7.   7.   8.  27.   2.  26.   0.   3.  70.  68.
    5.   3.   3.  80.]
 [ 14.   2.   2.  87.  27.   6.   6.  17.   2.  47.   0.   0.  29.  96.
    4.   2.   0.  67.]
 [  3.   0.   0. 100.  -7.   7.   8.   4.   3.  25.   0.   4.  85.  -8.
    1.   1.   1.  75.]
 [  9.   4.   4.  82.  35.   6.   2.  11.   2.  91.   7.   0.  64.  73.
    1.   4.   0. 100.]
 [ 29.   1.   0.  70.   4.   3.   5.  30.   2.  40.   0.   2.  41.  43.
    6.   5.   1.  58.]
 [ 14.   1.   0.  93.   3.   3.   5.  31.   1.  20.   4.   2.   8.  -8.
    5.  -8.   0.  56.]
 [ 15.   0.   0.  93.  40.   6.   6.   9.   0.  33.  14.   0.  60.  -8.
    4.   2.   2.  50.]
 [  6.   0.   0. 100.  -7.   7.   8.   6.   1.  17.   0.   0.   9.  -8.
    1.   1.   0.  50.]
 [ 40.   0.   0.  93.   2.   4.   6.  40.   4.  25.   1.   3.  37.  59.
    5.   3.   0.  80.]
 [ 27.   0.   0.  93.   5.   4.   6.  27.   2.  41.   3.   3.  58.  83.
    5.   6.   1.  75.]
 [ 18.   0.   0.  94.   5.   4.   6.  18.   1.  22.  -7.   3.  53.  -8.
    8.   1.   1. 100.]
 [ 25.   1.   0.  85.  21.   5.   5.  26.   1.  62.   0.   0.  49.  47.
    3.   4.   2.  64.]
 [ 16.   0.   0.  94.  43.   6.   6.  16.   2.  19.   0.   7.  98.  -8.
    5.   1.   4. 100.]
 [ 13.   0.   0. 100.  -7.   7.   8.  16.   6.  31.   0.   8.  39.  89.
    2.   4.   0.  54.]
 [ 21.   2.   2.  83.   4.   4.   3.  23.   1.  22.   0.   0.  61.  96.
    6.   2.   3.  73.]
 [ 25.   0.   0. 100.  -7.   7.   8.  25.   2.  52.  -7.   0.   0.  63.
    3.   3.   0.  64.]
 [ 44.   0.   0. 100.  -7.   7.   8.  68.   2.  28.  -7.   1.  14.  57.
    8.   3.   2.  58.]
 [ 15.   0.   0.  94.  52.   6.   6.  16.   2.  56.   0.   4.  77.  -8.
    4.   1.   3.  83.]
 [  6.   0.   0. 100.  -7.   7.   8.   6.   1.  50.   6.   0.  14.  -8.
    1.   2.   0.  75.]
 [  9.   0.   0.  90.  79.   6.   6.  10.   0.  20.   0.   2.   2.  -8.
    1.  -8.   0.  25.]
 [ 23.   2.   1.  87.   1.   4.   3.  31.   3.  58.   0.   0.   0.  91.
    0.   2.   0.  75.]
 [ 28.   0.   0.  90.   6.   4.   6.  29.   0.  55.   0.   0.  85.  58.
    2.   4.   1. 100.]
 [ 44.   0.   0.  98.  -7.   5.   7.  44.   5.  16.   1.   3.   4. 111.
    6.   2.   0.  39.]
 [ 32.   0.   0.  88.   4.   4.   6.  34.   5.  59.  -7.   4.  32.  62.
    4.   3.   0.  80.]
 [ 26.   0.   0.  97.  -7.   5.   7.  29.   1.  28.   0.   0.   3.  52.
    3.   1.   1.  45.]
 [ 22.   0.   0. 100.  -7.   7.   8.  24.   2.  75.   0.   0.  14.  71.
    2.   8.   0.  83.]
 [  4.   2.   2.  88.  23.   6.   4.   8.   4.  88.   2.   1.  -8. 103.
   -8.   4.  -8. 100.]
 [ 11.   1.   1.  83.   8.   4.   3.  12.   1.  25.   3.   1.  27.  58.
    2.   3.   1.  60.]
 [ -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.
   -9.  -9.  -9.  -9.]
 [  1.   0.   0. 100.  -7.   7.   8.  15.   0. 100.  -7.   0.  -8.   6.
   -8.   1.  -8. 100.]
 [  8.   2.   2. 100.  -7.   6.   8.   9.   2.  44.   0.   1.  87.  49.
    2.   4.   1. 100.]
 [ -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.
   -9.  -9.  -9.  -9.]
 [ -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.  -9.
   -9.  -9.  -9.  -9.]
 [ 14.   0.   0. 100.  -7.   7.   8.  14.   2.  14.   1.   1.  58.  38.
    2.   1.   1.  43.]
 [ 20.   0.   0.  95.  71.   6.   6.  22.  10.  19.   0.   1.  34.  -8.
    4.   1.   1.  50.]
 [ 10.   0.   0. 100.  -7.   7.   8.  10.   1.  20.  -8.   0.   4.  -8.
    1.   1.   0.  33.]
 [ 39.   0.   0. 100.  -7.   7.   8.  41.   3.  34.   7.   0.  44.  18.
    4.   2.   0.  55.]
 [ 25.   0.   0. 100.  -7.   7.   8.  25.   0.  12.  20.   0.  13.  -8.
    1.  -8.   0.  17.]
 [  8.   0.   0. 100.  -7.   7.   8.   9.   3.  67.   1.   2.  39.  69.
    1.   1.   0.  67.]
 [  6.   0.   0. 100.  -7.   7.   8.   6.   1.  50.   6.   0.  14.  -8.
    1.   2.   0.  75.]
 [  5.   0.   0.  83.  11.   4.   6.   6.   2.  33.   0.   0.  69.  74.
    3.   2.   1. 100.]]
[[ 3.90000000e+01  0.00000000e+00  0.00000000e+00  9.41893997e+01
   2.85700951e+01  5.35418940e+00  5.51404953e+00  4.50000000e+01
   4.00000000e+00  2.92511044e+01  8.80126715e-01  3.00000000e+00
   2.08589611e+01  6.29757042e+01  6.00000000e+00  3.00000000e+00
   1.00000000e+00  4.81199684e+01]
 [ 2.60000000e+01  0.00000000e+00  0.00000000e+00  9.34877625e+01
  -2.67447829e-01  5.27078724e+00  6.34285593e+00  2.80000000e+01
   2.00000000e+00  4.25560493e+01 -5.45801401e-01  1.00000000e+00
   4.02561073e+01  7.96859436e+01  5.00000000e+00  4.00000000e+00
   1.00000000e+00  7.13590698e+01]
 [ 7.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+02
  -7.33134651e+00  7.30022907e+00  8.00000000e+00  7.00000000e+00
   1.00000000e+00  1.55183916e+01 -1.17726970e+00  1.00000000e+00
   1.59000850e+00 -8.99999905e+00  0.00000000e+00 -8.00000000e+00
  -3.00000000e+00  2.33288326e+01]
 [ 2.70000000e+01  0.00000000e+00  0.00000000e+00  9.57442398e+01
   5.97419815e+01  6.34696341e+00  4.78768682e+00  3.10000000e+01
   5.00000000e+00  3.40269279e+01 -7.65970886e-01  3.00000000e+00
   3.63269920e+01  6.26224251e+01  6.00000000e+00  3.00000000e+00
   2.00000000e+00  6.84458313e+01]
 [ 8.00000000e+00  0.00000000e+00  0.00000000e+00  9.31303253e+01
  -3.45787621e+00  5.73894787e+00  6.67804813e+00  5.00000000e+00
   3.00000000e+00  4.77483292e+01  1.96631238e-01  3.00000000e+00
  -5.32852507e+00  6.65479126e+01  0.00000000e+00  2.00000000e+00
  -4.00000000e+00  5.97212448e+01]
 [ 2.10000000e+01  0.00000000e+00  0.00000000e+00  1.00000000e+02
  -7.40179920e+00  7.05355787e+00  8.00000000e+00  2.20000000e+01
   0.00000000e+00  2.88149214e+00  1.36986482e+00  1.00000000e+00
   4.53103065e+01 -8.99999905e+00  8.00000000e+00 -7.00000000e+00
   3.00000000e+00  7.59080963e+01]
 [ 1.30000000e+01  1.00000000e+00  1.00000000e+00  8.11912537e+01
   7.72307515e-01  5.05758142e+00  5.81399012e+00  1.10000000e+01
   0.00000000e+00  3.91656036e+01  1.01722467e+00  0.00000000e+00
   3.86220360e+01  6.92341375e+00  3.00000000e+00  1.00000000e+00
   0.00000000e+00  7.27268066e+01]
 [ 2.40000000e+01  0.00000000e+00  0.00000000e+00  9.17350235e+01
   4.21508431e-01  5.14332199e+00  6.10962343e+00  2.60000000e+01
   2.00000000e+00  4.14561310e+01 -2.38146037e-01  1.00000000e+00
   3.65342140e+01  7.61256104e+01  4.00000000e+00  3.00000000e+00
   1.00000000e+00  6.95244904e+01]
 [ 2.40000000e+01  0.00000000e+00  0.00000000e+00  1.00000000e+02
  -7.00000000e+00  7.00000000e+00  8.00000000e+00  2.70000000e+01
   2.00000000e+00  2.60000000e+01  7.86781307e-09  2.00000000e+00
   2.00000072e+00  7.60000000e+01  2.00000000e+00  2.00000000e+00
   0.00000000e+00  5.00000000e+01]
 [ 2.30000000e+01  0.00000000e+00  0.00000000e+00  1.00000000e+02
  -7.00000000e+00  6.63054132e+00  7.94843721e+00  2.40000000e+01
   3.00000000e+00  3.75788002e+01 -3.60322237e-01  2.00000000e+00
   5.22309151e+01  6.63253937e+01  6.00000000e+00  3.00000000e+00
   2.00000000e+00  7.96348038e+01]
 [ 1.40000000e+01  2.00000000e+00  2.00000000e+00  8.70000000e+01
   2.70000000e+01  6.00000000e+00  6.00000000e+00  1.70000000e+01
   2.00000000e+00  4.70000000e+01  7.86781307e-09  0.00000000e+00
   2.90000000e+01  9.60000000e+01  4.00000000e+00  2.00000000e+00
   0.00000000e+00  6.70000000e+01]
 [ 3.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+02
  -6.54228115e+00  7.07653236e+00  8.00000000e+00  1.00000000e+00
   2.00000000e+00  4.21341133e+01 -1.10515583e+00  1.00000000e+00
   4.93785744e+01  1.68091793e+01  1.00000000e+00  0.00000000e+00
  -1.00000000e+00  9.31020355e+01]
 [ 9.00000000e+00  4.00000000e+00  4.00000000e+00  8.20000000e+01
   3.50000000e+01  6.00000000e+00  1.99999988e+00  1.10000000e+01
   2.00000000e+00  9.10000000e+01  7.00000048e+00  0.00000000e+00
   6.40000000e+01  7.30000000e+01  1.00000000e+00  4.00000000e+00
   0.00000000e+00  1.00000000e+02]
 [ 2.40000000e+01  1.00000000e+00  0.00000000e+00  8.43244476e+01
   8.68239307e+00  4.27952719e+00  4.78877306e+00  2.60000000e+01
   1.00000000e+00  3.42061729e+01  1.88760325e-01  1.00000000e+00
   3.42554016e+01  5.72861786e+01  5.00000000e+00  3.00000000e+00
   1.00000000e+00  6.69962387e+01]
 [ 1.10000000e+01  1.00000000e+00  1.00000000e+00  8.13734970e+01
   1.57527268e+00  5.02064610e+00  5.33183861e+00  9.00000000e+00
   0.00000000e+00  3.02929020e+01 -3.51557302e+00  0.00000000e+00
   6.66141558e+00 -7.99999857e+00  2.00000000e+00 -5.00000000e+00
  -2.00000000e+00  4.77301407e+01]
 [ 1.50000000e+01  0.00000000e+00  0.00000000e+00  9.30000000e+01
   4.00000000e+01  6.00000000e+00  6.00000000e+00  9.00000000e+00
   0.00000000e+00  3.30000000e+01  1.40000000e+01  0.00000000e+00
   6.00000000e+01 -7.99999857e+00  4.00000000e+00  2.00000000e+00
   2.00000000e+00  5.00000000e+01]
 [ 6.00000000e+00  0.00000000e+00  0.00000000e+00  9.73650665e+01
  -5.78144646e+00  6.38141823e+00  7.57342291e+00  4.00000000e+00
   2.00000000e+00  1.44544725e+01 -4.07630861e-01  1.00000000e+00
   6.44405222e+00  6.30260611e+00  2.00000000e+00 -4.00000000e+00
  -1.00000000e+00  6.02868156e+01]
 [ 3.50000000e+01  1.00000000e+00  0.00000000e+00  8.99220963e+01
   9.78883648e+00  4.81868362e+00  5.38672781e+00  4.00000000e+01
   4.00000000e+00  3.55703087e+01 -1.51099491e+00  3.00000000e+00
   3.81252823e+01  7.59180222e+01  7.00000000e+00  4.00000000e+00
   2.00000000e+00  6.44755173e+01]
 [ 2.50000000e+01  0.00000000e+00  0.00000000e+00  9.78940277e+01
  -3.66315746e+00  5.92324686e+00  7.15866709e+00  2.60000000e+01
   3.00000000e+00  4.57515640e+01 -7.06227064e-01  2.00000000e+00
   4.01534081e+01  8.62878647e+01  5.00000000e+00  4.00000000e+00
   1.00000000e+00  7.22599869e+01]
 [ 1.70000000e+01  0.00000000e+00  0.00000000e+00  9.92338257e+01
  -6.41394901e+00  6.53678322e+00  7.88328743e+00  1.60000000e+01
   1.00000000e+00  3.56519470e+01  8.68259311e-01  1.00000000e+00
   4.44635506e+01  3.54914322e+01  4.00000000e+00  2.00000000e+00
   1.00000000e+00  7.55877762e+01]
 [ 2.50000000e+01  1.00000000e+00  0.00000000e+00  8.50000000e+01
   2.10000000e+01  5.00000000e+00  5.00000000e+00  2.60000000e+01
   1.00000000e+00  6.20000000e+01  7.86781307e-09  0.00000000e+00
   4.90000000e+01  4.70000000e+01  3.00000000e+00  4.00000000e+00
   2.00000000e+00  6.40000000e+01]
 [ 1.60000000e+01  0.00000000e+00  0.00000000e+00  9.40000000e+01
   4.30000000e+01  6.00000000e+00  6.00000000e+00  1.60000000e+01
   2.00000000e+00  1.90000000e+01  7.86781307e-09  7.00000000e+00
   9.80000000e+01 -7.99999857e+00  5.00000000e+00  1.00000000e+00
   4.00000000e+00  1.00000000e+02]
 [ 2.00000000e+01  0.00000000e+00  0.00000000e+00  9.44056168e+01
  -2.44225025e+00  5.84377861e+00  6.77439070e+00  2.30000000e+01
   6.00000000e+00  2.59408340e+01 -9.01518285e-01  5.00000000e+00
   1.34402723e+01  5.26831665e+01  3.00000000e+00  2.00000000e+00
   0.00000000e+00  4.82718163e+01]
 [ 2.10000000e+01  1.00000000e+00  0.00000000e+00  8.26390533e+01
   5.28856468e+00  4.17231560e+00  4.89694738e+00  2.20000000e+01
   1.00000000e+00  3.72648392e+01  3.92627686e-01  1.00000000e+00
   4.41779747e+01  5.17748299e+01  5.00000000e+00  2.00000000e+00
   1.00000000e+00  7.36810837e+01]
 [ 2.50000000e+01  0.00000000e+00  0.00000000e+00  1.00000000e+02
  -7.00000000e+00  7.00000000e+00  8.00000000e+00  2.50000000e+01
   2.00000000e+00  5.20000000e+01 -7.00000000e+00  0.00000000e+00
  -1.23596192e-06  6.30000000e+01  3.00000000e+00  3.00000000e+00
   0.00000000e+00  6.40000000e+01]
 [ 5.70000000e+01  0.00000000e+00  0.00000000e+00  9.84140472e+01
   1.19182551e+00  5.16968012e+00  6.79741621e+00  6.70000000e+01
   4.00000000e+00  3.33302879e+01  8.92598271e-01  3.00000000e+00
   2.15939140e+01  8.98244934e+01  9.00000000e+00  5.00000000e+00
   2.00000000e+00  5.47038040e+01]
 [ 1.50000000e+01  0.00000000e+00  0.00000000e+00  9.40000000e+01
   5.20000000e+01  6.00000000e+00  6.00000000e+00  1.60000000e+01
   2.00000000e+00  5.60000000e+01  7.86781307e-09  4.00000000e+00
   7.70000000e+01 -7.99999857e+00  4.00000000e+00  1.00000000e+00
   3.00000000e+00  8.30000000e+01]
 [ 9.00000000e+00  0.00000000e+00  0.00000000e+00  9.70935211e+01
  -7.50007343e+00  6.72192287e+00  8.00000000e+00  7.00000000e+00
   1.00000000e+00  5.86696320e+01 -2.95778587e-02  1.00000000e+00
   1.20399847e+01  2.71740608e+01 -1.00000000e+00  2.00000000e+00
  -3.00000000e+00  8.23230896e+01]
 [ 8.00000000e+00  0.00000000e+00  0.00000000e+00  8.83521347e+01
   6.90285339e+01  6.34122229e+00  4.39908934e+00  9.00000000e+00
   0.00000000e+00  2.11635284e+01  7.86781307e-09  0.00000000e+00
  -5.55425978e+00 -2.63223124e+00  0.00000000e+00 -5.00000000e+00
  -3.00000000e+00  3.07989140e+01]
 [ 2.00000000e+01  0.00000000e+00  0.00000000e+00  9.11887589e+01
   1.19105531e-02  5.23748112e+00  6.08568287e+00  2.10000000e+01
   2.00000000e+00  3.86827278e+01 -3.73644382e-01  2.00000000e+00
   2.32881298e+01  7.19525833e+01  3.00000000e+00  3.00000000e+00
   0.00000000e+00  5.91769714e+01]
 [ 1.50000000e+01  1.00000000e+00  0.00000000e+00  8.63983917e+01
   5.20866036e-01  5.16075563e+00  6.27002239e+00  1.50000000e+01
   0.00000000e+00  4.62093048e+01  9.33933616e-01  0.00000000e+00
   7.03096771e+01  3.32192078e+01  4.00000000e+00  2.00000000e+00
   1.00000000e+00  8.56979218e+01]
 [ 3.40000000e+01  0.00000000e+00  0.00000000e+00  9.40672913e+01
   9.39286232e+00  5.43678570e+00  6.12876701e+00  4.00000000e+01
   3.00000000e+00  2.98312130e+01  8.58262897e-01  2.00000000e+00
   1.54697886e+01  6.31269608e+01  4.00000000e+00  3.00000000e+00
   0.00000000e+00  4.38546371e+01]
 [ 2.30000000e+01  0.00000000e+00  0.00000000e+00  9.49091873e+01
  -2.23978233e+00  5.64191914e+00  6.70489979e+00  2.50000000e+01
   2.00000000e+00  4.30786781e+01 -3.86619627e-01  1.00000000e+00
   3.29953880e+01  8.12504807e+01  4.00000000e+00  4.00000000e+00
   1.00000000e+00  6.71954803e+01]
 [ 3.10000000e+01  0.00000000e+00  0.00000000e+00  9.21799240e+01
   1.49488440e+01  5.33264256e+00  5.65992308e+00  3.50000000e+01
   1.00000000e+00  2.74982910e+01  2.95709133e+00  1.00000000e+00
   1.21978865e+01  4.71051369e+01  4.00000000e+00  2.00000000e+00
   0.00000000e+00  4.37335701e+01]
 [ 1.70000000e+01  0.00000000e+00  0.00000000e+00  9.68162613e+01
  -3.15608501e+00  5.99642992e+00  7.24363804e+00  1.80000000e+01
   2.00000000e+00  5.08269691e+01 -3.34631205e-01  1.00000000e+00
   5.43315086e+01  8.54059372e+01  3.00000000e+00  4.00000000e+00
   1.00000000e+00  7.86520157e+01]
 [ 8.00000000e+00  0.00000000e+00  0.00000000e+00  9.31303253e+01
  -3.45787621e+00  5.73894787e+00  6.67804813e+00  5.00000000e+00
   3.00000000e+00  4.77483292e+01  1.96631238e-01  3.00000000e+00
  -5.32852507e+00  6.65479126e+01  0.00000000e+00  2.00000000e+00
  -4.00000000e+00  5.97212448e+01]
 [ 1.10000000e+01  1.00000000e+00  1.00000000e+00  8.30000000e+01
   8.00000000e+00  4.00000000e+00  3.00000000e+00  1.20000000e+01
   1.00000000e+00  2.50000000e+01  3.00000000e+00  1.00000000e+00
   2.70000000e+01  5.80000000e+01  2.00000000e+00  3.00000000e+00
   1.00000000e+00  6.00000000e+01]
 [-9.00000000e+00 -9.00000000e+00 -9.00000000e+00 -9.00000095e+00
  -9.00000000e+00 -9.00000095e+00 -9.00000000e+00 -9.00000000e+00
  -9.00000000e+00 -8.99999905e+00 -9.00000095e+00 -9.00000000e+00
  -8.99999905e+00 -8.99999905e+00 -9.00000000e+00 -9.00000000e+00
  -9.00000000e+00 -9.00000286e+00]
 [ 9.00000000e+00  0.00000000e+00  0.00000000e+00  9.56417618e+01
  -5.74082088e+00  6.27702188e+00  7.67984009e+00  6.00000000e+00
   1.00000000e+00  5.01847839e+01 -6.94055736e-01  1.00000000e+00
  -1.62763906e+00  2.08673058e+01 -1.00000000e+00  0.00000000e+00
  -4.00000000e+00  6.42164612e+01]
 [ 7.00000000e+00  0.00000000e+00  0.00000000e+00  9.68472977e+01
  -5.56202412e+00  6.59278536e+00  8.00000000e+00  5.00000000e+00
   1.00000000e+00  4.87573776e+01  7.15310946e-02  1.00000000e+00
   6.94631577e+01  3.27530403e+01  2.00000000e+00  1.00000000e+00
   0.00000000e+00  9.52758865e+01]
 [-9.00000000e+00 -9.00000000e+00 -9.00000000e+00 -9.00000095e+00
  -9.00000000e+00 -9.00000095e+00 -9.00000000e+00 -9.00000000e+00
  -9.00000000e+00 -8.99999905e+00 -9.00000095e+00 -9.00000000e+00
  -8.99999905e+00 -8.99999905e+00 -9.00000000e+00 -9.00000000e+00
  -9.00000000e+00 -9.00000286e+00]
 [-9.00000000e+00 -9.00000000e+00 -9.00000000e+00 -9.00000095e+00
  -9.00000000e+00 -9.00000095e+00 -9.00000000e+00 -9.00000000e+00
  -9.00000000e+00 -8.99999905e+00 -9.00000095e+00 -9.00000000e+00
  -8.99999905e+00 -8.99999905e+00 -9.00000000e+00 -9.00000000e+00
  -9.00000000e+00 -9.00000286e+00]
 [ 1.30000000e+01  0.00000000e+00  0.00000000e+00  1.00000000e+02
  -6.48335171e+00  6.77567768e+00  8.00000000e+00  1.20000000e+01
   3.00000000e+00  2.75211563e+01 -4.74180788e-01  1.00000000e+00
   1.84909325e+01  2.96635532e+01  2.00000000e+00  1.00000000e+00
   0.00000000e+00  5.97980003e+01]
 [ 2.60000000e+01  0.00000000e+00  0.00000000e+00  9.81688080e+01
   7.10000000e+01  7.01608133e+00  5.18777657e+00  3.10000000e+01
   3.00000000e+00  2.56546803e+01 -3.33790898e-01  3.00000000e+00
   2.14350009e+00  2.97839756e+01  2.00000000e+00  2.00000000e+00
   0.00000000e+00  4.05646477e+01]
 [ 8.00000000e+00  0.00000000e+00  0.00000000e+00  9.75562515e+01
  -4.80787373e+00  6.60924292e+00  7.87572432e+00  8.00000000e+00
   1.00000000e+00  2.27537289e+01 -8.46719384e-01  1.00000000e+00
  -1.77242208e+00 -4.65615702e+00 -1.00000000e+00 -5.00000000e+00
  -4.00000000e+00  2.04761600e+01]
 [ 3.90000000e+01  0.00000000e+00  0.00000000e+00  1.00000000e+02
  -7.00000000e+00  7.00000000e+00  8.00000000e+00  4.10000000e+01
   3.00000000e+00  3.40000000e+01  7.00000048e+00  0.00000000e+00
   4.40000000e+01  1.80000000e+01  4.00000000e+00  2.00000000e+00
   0.00000000e+00  5.50000000e+01]
 [ 9.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+02
  -8.91875458e+00  7.58857822e+00  8.00000000e+00  9.00000000e+00
   1.00000000e+00  1.58521643e+01 -2.37341189e+00  1.00000000e+00
   1.74715877e+00 -8.99999905e+00  0.00000000e+00 -9.00000000e+00
  -2.00000000e+00  2.40544071e+01]
 [ 8.00000000e+00  0.00000000e+00  0.00000000e+00  9.89476547e+01
  -5.91063309e+00  6.43488598e+00  7.89421082e+00  6.00000000e+00
   3.00000000e+00  4.88828659e+01 -7.26232767e-01  2.00000000e+00
   2.79829063e+01  6.90000000e+01  1.00000000e+00  3.00000000e+00
  -2.00000000e+00  7.69472656e+01]
 [ 9.00000000e+00  0.00000000e+00  0.00000000e+00  9.70935211e+01
  -7.50007343e+00  6.72192287e+00  8.00000000e+00  7.00000000e+00
   1.00000000e+00  5.86696320e+01 -2.95778587e-02  1.00000000e+00
   1.20399847e+01  2.71740608e+01 -1.00000000e+00  2.00000000e+00
  -3.00000000e+00  8.23230896e+01]
 [ 1.00000000e+01  0.00000000e+00  0.00000000e+00  9.84707565e+01
  -5.71475506e+00  6.32277870e+00  7.78721762e+00  8.00000000e+00
   3.00000000e+00  4.93863678e+01 -3.24442148e-01  1.00000000e+00
   3.29844055e+01  7.25869370e+01  1.00000000e+00  3.00000000e+00
  -1.00000000e+00  7.73899765e+01]]

In [12]:
# # TODO: One-hot encoding function for datasets with catergorical features
# cat_idx = [2, 3, 4, 5] #    CheckingAccount", "Job", "Housing", "SavingAccounts"
# num_idx = [0, 1]
# X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])


# --- CF evaluation ---
cf_scores, cf_scores_labels = cf_eval(
    data.X_train, # previous name: data.X_train
    context_training, # previous name: context_training,
    X_test, # previous name: x,
    X_cf, # previous name: cf_x, 
    y_original_labels, # previous name: y_,
    context_test, # previous name: context,
    y_cf_labels, # previous name: cf_y_
    data.scaler_inverse_transform(X_test),
    data.scaler_inverse_transform(X_cf),
    child_to_parents_dict,
    # cat_idx,
    # num_idx
)

print(cf_scores, cf_scores_labels)

[0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1
 1 1 1 1 1 1 1 0 0 0 1 0 1]
[0 1 0 1 1 0 0 1 1 1 0 1 0 1 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 0
 0 1 1 0 0 1 1 0 1 0 1 0 1]
0.74
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (21, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9669658922228529 3.753302927545895
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (8, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9658655732488753 1.2721821422283197
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (4, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.0063745953187482 1.3306200370188535
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (17, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9735141183415185 1.1838412520484378
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9658655732488753 1.031992299123687 3.753302927545895 50
[1.5893294632292092, 0.3746085469963165, 0.74, 0.2877777777777778, 1.2292325032699047, 0.4, 0.9266666666666667, 0.38888888888888884, 0.9642857142857143] ['proximity', 'n_proximity', 'validity', 'compactness', 'lof_context', 'causal_validity_hard', 'causal_validity_soft', 'causal_compact_val', 'inlier_fraction']

## Graph 2 (Moderate priors)

In [13]:
N = 50
N_BOOTSTRAP = 5
# SEED_list = [23] * N_BOOTSTRAP
SEED_list = [11, 22, 33, 44, 55]

# Number of samples to compute the metrics for CF evaluation
METRICS = []

for i, exp in enumerate(EXP):
    print("\n" * 2)
    print("*" * 200)
    print(f"Running exp: {exp['name']} ({i}/{len(EXP)})")
    print("*" * 200)
    print("\n" * 2)
    
    # Reading the data
    CLASS_CONFIG_PATH = exp["classifier"]
    AE_CONFIG_PATH = exp["AE"]

    class_config = get_exp_config(CLASS_CONFIG_PATH)
    print("Reading data")
    data = getData(class_config)

    # Getting classifier
    classifier = modelGen(class_config["type"], data, params=class_config, debug=True)
    classifier.load()

    # Getting AE-based Model
    AE_config = get_exp_config(AE_CONFIG_PATH)
    aeModel = modelGen(AE_config["type"], data, params=AE_config, debug=True)
    aeModel.load()

    # CF generation
    child_to_parents_dict, parent_to_children_dict, feat2idx = build_causal_index_map(
        data.features_lbls,
        # TODO: change the string below for graph_str1 and graph_str2
        graph_str2
    )
    print("Feature → index:")
    print(feat2idx)
    print("\nChild → Parents (index form):")
    print(child_to_parents_dict)
    
    if exp["name"] == "CausalCACTUS":
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train,
            x_min=data.X_train.min(axis=0),
            x_max=data.X_train.max(axis=0),
            causal_index_map=child_to_parents_dict
        )
    else:
        CF_method = CF_METHODS[exp["CFmethod"]](
            classifier=classifier,
            gen=aeModel,
            params=exp,
            x=data.X_train,
            y=data.y_train
        )

    for trial in range(N_BOOTSTRAP):

        # --- Sampling test data ---
        SEED = SEED_list[trial]
        os.environ['PYTHONHASHSEED'] = str(SEED)
        random.seed(SEED)
        np.random.seed(SEED)
        tf_random.set_seed(SEED)
        rand_idx = np.random.choice(len(data.X_test), N, replace=True)
        
        # previous name: x
        X_test = data.X_test[rand_idx, ...]
        # previous name: contest
        context_test = data.context_test[exp['context']].values
        context_test = context_test[rand_idx, ...]

        context_training = data.context_train[exp['context']].values

        # previous name: y
        y_test = np.argmax(data.y_test[rand_idx, ...], axis=1)
        y_original_logits = classifier.predict(X_test)
        # previous name: y_
        y_original_labels = np.argmax(y_original_logits, axis=1)

        # --- CF generation ---
        # previous names: 
        # cf_x, cf_y_, x, __
        X_cf, y_cf_labels, X_internal, y_internal = CF_method.transform(
            X_test,
            y_original_labels,
            target_context=context_test,
            verbose=0
        )              

        # # TODO: One-hot encoding function for datasets with catergorical features
        # cat_idx = [2, 3, 4, 5] #    CheckingAccount", "Job", "Housing", "SavingAccounts"
        # num_idx = [0, 1]
        # X_cf[:, cat_idx] = np.around(X_cf[:, cat_idx])
        
        # --- CF evaluation ---
        cf_scores, cf_scores_labels = cf_eval(
            data.X_train, # previous name: data.X_train
            context_training, # previous name: context_training,
            X_test, # previous name: x,
            X_cf, # previous name: cf_x, 
            y_original_labels, # previous name: y_,
            context_test, # previous name: context,
            y_cf_labels, # previous name: cf_y_
            data.scaler_inverse_transform(X_test),
            data.scaler_inverse_transform(X_cf),
            child_to_parents_dict
            # cat_idx,
            # num_idx
        )

        for i_metric, label in enumerate(cf_scores_labels):
            METRICS.append([
                exp["name"],
                exp["data"],
                exp["CFmethod"],
                label,
                cf_scores[i_metric]
            ])

    # Cleaning GPU models
    cleanup_gpu()

# --- Metrics aggregation ---
df_metrics = pd.DataFrame(
    data=METRICS,
    columns=["Model", "Dataset", "CFMethod", "Metric", "Value"]
)
df_metrics = df_metrics.round(3)
print(df_metrics)

********************************************************************************************************************************************************************************************************
Running exp: LatentCF++ (0/5)
********************************************************************************************************************************************************************************************************



Reading data
MOpenAbove15years
0    5387
1    5072
Name: count, dtype: int64
MInFileAbove6years
1    5389
0    5070
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 10000
Positive class: 5000.0
Context 'MOpenAbove15years=1': 4885
Context 'MInFileAbove6years=1': 5198
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:139: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MOpenAbove15years"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:140: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MInFileAbove6years"]))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 dense (Dense)               (None, 64)                1216

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,970
Trainable params: 35,202
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: HELOC_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 model_1 (Functional)        (None, 16)                4816

 model_2 (Functional)        (None, 18)                4818

=================================================================
Total params: 9,634
Trainable params: 9,634
Non-trainable params: 0
_________________________________________________________________
restoring weights of model AE: HELOC_AE

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Feature → index:
{'NumSatisfactoryTrades': 0, 'NumTrades60Ever2DerogPubRec': 1, 'NumTrades90Ever2DerogPubRec': 2, 'PercentTradesNeverDelq': 3, 'MSinceMostRecentDelq': 4, 'MaxDelq2PublicRecLast12M': 5, 'MaxDelqEver': 6, 'NumTotalTrades': 7, 'NumTradesOpeninLast12M': 8, 'PercentInstallTrades': 9, 'MSinceMostRecentInqexcl7days': 10, 'NumInqLast6M': 11, 'NetFractionRevolvingBurden': 12, 'NetFractionInstallBurden': 13, 'NumRevolvingTradesWBalance': 14, 'NumInstallTradesWBalance': 15, 'NumBank2NatlTradesWHighUtilization': 16, 'PercentTradesWBalance': 17}

Child → Parents (index form):
{5: [14], 6: [0, 9, 17, 16], 16: [10], 17: [10, 3], 11: [12, 4, 17], 10: [4, 13], 12: [13], 8: [17]}
Building model: latentCF [CF]
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 16)]              0

 model_2 (Functional)        (None, 18)                4818

 model (Functional)          (None, 2)                 35970

=================================================================
Total params: 40,788
Trainable params: 40,020
Non-trainable params: 768
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0
 1 0 0 1 1 0 0 0 0 1 1 0 0]
[0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0
 1 0 0 1 1 0 0 0 0 1 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (16, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.0313270441447653 3.602938062909662
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.009449334774842 1.3827297217764807
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (2, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.070860077177679 1.6062220458188023
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (25, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9952444523685928 1.547176050443734
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9952444523685928 1.1135103267844382 3.602938062909662 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1
 0 0 0 1 0 1 0 0 0 0 1 0 0]
[1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1
 0 0 0 1 0 1 0 0 0 0 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (20, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9925285394734338 3.625542529700222
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9795302218557611 1.1905283685066974
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.002057529538467 1.5257870307689738
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (16, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.007323984458095 1.421937432978829
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9795302218557611 1.0896237565586537 3.625542529700222 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1
 0 1 1 0 1 1 0 1 0 0 1 1 1]
[0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1
 0 1 1 0 1 1 0 1 0 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (20, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9793495008890502 3.421837467654938
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (5, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.023658476374932 1.5750296531884012
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (2, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.0391885089625235 1.3694666088682923
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (23, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.0354107563753652 1.672657971435833
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9793495008890502 1.1053797134584098 3.421837467654938 50
2/2 [==============================] - 0s 2ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1
 0 0 1 0 0 1 1 0 0 0 1 1 0]
[0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1
 0 0 1 0 0 1 1 0 0 0 1 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (14, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9925089340858185 3.3845715820944893
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (1, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.0888133266730133 1.0888133266730133
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (5, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9893181714947167 1.3218865683040537
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (30, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.0055075422874098 1.7755055252615144
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9893181714947167 1.138847764091702 3.3845715820944893 50
2/2 [==============================] - 0s 3ms/step
Generating CF 0/50
Generating CF 1/50
Generating CF 2/50
Generating CF 3/50
Generating CF 4/50
Generating CF 5/50
Generating CF 6/50
Generating CF 7/50
Generating CF 8/50
Generating CF 9/50
Generating CF 10/50
Generating CF 11/50
Generating CF 12/50
Generating CF 13/50
Generating CF 14/50
Generating CF 15/50
Generating CF 16/50
Generating CF 17/50
Generating CF 18/50
Generating CF 19/50
Generating CF 20/50
Generating CF 21/50
Generating CF 22/50
Generating CF 23/50
Generating CF 24/50
Generating CF 25/50
Generating CF 26/50
Generating CF 27/50
Generating CF 28/50
Generating CF 29/50
Generating CF 30/50
Generating CF 31/50
Generating CF 32/50
Generating CF 33/50
Generating CF 34/50
Generating CF 35/50
Generating CF 36/50
Generating CF 37/50
Generating CF 38/50
Generating CF 39/50
Generating CF 40/50
Generating CF 41/50
Generating CF 42/50
Generating CF 43/50
Generating CF 44/50
Generating CF 45/50
Generating CF 46/50
Generating CF 47/50
Generating CF 48/50
Generating CF 49/50
[1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1 1 0 1 0 0 0
 1 1 0 1 0 0 1 0 0 1 0 0 1]
[1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1 1 0 1 0 0 0
 1 1 0 1 0 0 1 0 0 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (12, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9894557324815659 3.457707274308311
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (3, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.1498297474178483 1.152141426850618
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (9, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9965906427843239 1.7057358847386317
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (26, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9971346492828647 1.7124940511022617
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9894557324815659 1.1514196164761836 3.457707274308311 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype C (1/5)
********************************************************************************************************************************************************************************************************



Reading data
MOpenAbove15years
0    5387
1    5072
Name: count, dtype: int64
MInFileAbove6years
1    5389
0    5070
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 10000
Positive class: 5000.0
Context 'MOpenAbove15years=1': 4885
Context 'MInFileAbove6years=1': 5198
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:139: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MOpenAbove15years"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:140: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MInFileAbove6years"]))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 dense (Dense)               (None, 64)                1216

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,970
Trainable params: 35,202
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: HELOC_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 model_1 (Functional)        (None, 16)                4816

 model_2 (Functional)        (None, 18)                4818

=================================================================
Total params: 9,634
Trainable params: 9,634
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: HELOC_AE
Feature → index:
{'NumSatisfactoryTrades': 0, 'NumTrades60Ever2DerogPubRec': 1, 'NumTrades90Ever2DerogPubRec': 2, 'PercentTradesNeverDelq': 3, 'MSinceMostRecentDelq': 4, 'MaxDelq2PublicRecLast12M': 5, 'MaxDelqEver': 6, 'NumTotalTrades': 7, 'NumTradesOpeninLast12M': 8, 'PercentInstallTrades': 9, 'MSinceMostRecentInqexcl7days': 10, 'NumInqLast6M': 11, 'NetFractionRevolvingBurden': 12, 'NetFractionInstallBurden': 13, 'NumRevolvingTradesWBalance': 14, 'NumInstallTradesWBalance': 15, 'NumBank2NatlTradesWHighUtilization': 16, 'PercentTradesWBalance': 17}

Child → Parents (index form):
{5: [14], 6: [0, 9, 17, 16], 16: [10], 17: [10, 3], 11: [12, 4, 17], 10: [4, 13], 12: [13], 8: [17]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0
 1 0 0 1 1 0 0 0 0 1 1 0 0]
[0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0
 1 0 0 1 1 0 0 0 0 1 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (16, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.107485267739015 4.252994111100521
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.8230576386208717 3.389934775046352
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (2, 18)
X_ shape: (766, 18)
lof_cf min/max: 2.211168808447028 2.6697202787956233
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (25, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.1667171213681722 3.547233347853438
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.107485267739015 2.1841116131417566 4.252994111100521 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1
 0 0 0 1 0 1 0 0 0 0 1 0 0]
[1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1
 0 0 0 1 0 1 0 0 0 0 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (20, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.3608487526484578 4.252994111100521
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.1805528430124979 2.210867098000155
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.817662902113719 3.156751406984917
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (16, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.2181563999663108 3.600776333648889
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.1805528430124979 2.230737801380126 4.252994111100521 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1
 0 1 1 0 1 1 0 1 0 0 1 1 1]
[0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1
 0 1 1 0 1 1 0 1 0 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (20, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.1202740388194947 4.252994111100521
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (5, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.9201925979224765 2.6065723861141996
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (2, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.2274148960274631 2.6923793202349398
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (23, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.1855550915812605 4.110399247416239
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.1202740388194947 2.3072481610778635 4.252994111100521 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1
 0 0 1 0 0 1 1 0 0 0 1 1 0]
[0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1
 0 0 1 0 0 1 1 0 0 0 1 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (14, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.2536112305608207 4.252994111100521
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (1, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.8687654929695365 1.8687654929695365
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (5, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.1573289661870674 4.095204448462768
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (30, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.302006458847851 3.7667636595884817
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.1573289661870674 2.351819123503671 4.252994111100521 50
2/2 [==============================] - 0s 3ms/step
[1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1 1 0 1 0 0 0
 1 1 0 1 0 0 1 0 0 1 0 0 1]
[1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1 1 0 1 0 0 0
 1 1 0 1 0 0 1 0 0 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (12, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.6339701723746318 4.252994111100521
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (3, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.340340631837111 1.6668697966732788
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (9, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.7107392923932754 2.8853586144576377
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (26, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.5190729629614106 4.150648656862164
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.340340631837111 2.193643576012996 4.252994111100521 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: Prototype D (2/5)
********************************************************************************************************************************************************************************************************



Reading data
MOpenAbove15years
0    5387
1    5072
Name: count, dtype: int64
MInFileAbove6years
1    5389
0    5070
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 10000
Positive class: 5000.0
Context 'MOpenAbove15years=1': 4885
Context 'MInFileAbove6years=1': 5198
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:139: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MOpenAbove15years"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:140: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MInFileAbove6years"]))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 dense (Dense)               (None, 64)                1216

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,970
Trainable params: 35,202
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: HELOC_class
Building model
Building model: AE [gen]
Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 model_1 (Functional)        (None, 16)                4816

 model_2 (Functional)        (None, 18)                4818

=================================================================
Total params: 9,634
Trainable params: 9,634
Non-trainable params: 0
_________________________________________________________________

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

restoring weights of model AE: HELOC_AE
Feature → index:
{'NumSatisfactoryTrades': 0, 'NumTrades60Ever2DerogPubRec': 1, 'NumTrades90Ever2DerogPubRec': 2, 'PercentTradesNeverDelq': 3, 'MSinceMostRecentDelq': 4, 'MaxDelq2PublicRecLast12M': 5, 'MaxDelqEver': 6, 'NumTotalTrades': 7, 'NumTradesOpeninLast12M': 8, 'PercentInstallTrades': 9, 'MSinceMostRecentInqexcl7days': 10, 'NumInqLast6M': 11, 'NetFractionRevolvingBurden': 12, 'NetFractionInstallBurden': 13, 'NumRevolvingTradesWBalance': 14, 'NumInstallTradesWBalance': 15, 'NumBank2NatlTradesWHighUtilization': 16, 'PercentTradesWBalance': 17}

Child → Parents (index form):
{5: [14], 6: [0, 9, 17, 16], 16: [10], 17: [10, 3], 11: [12, 4, 17], 10: [4, 13], 12: [13], 8: [17]}
Building model: PrototypeLatentCF [CF]
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 4ms/step
[0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0
 1 0 0 1 1 0 0 0 0 1 1 0 0]
[0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0
 1 0 0 1 1 0 0 0 0 1 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (16, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.2061071276330682 2.3687950739261128
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.057669203647153 2.0195230528873838
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (2, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.502035926038187 1.5252640934155028
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (25, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.0331610007976966 2.25472871125599
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.0331610007976966 1.589087759215223 2.3687950739261128 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1
 0 0 0 1 0 1 0 0 0 0 1 0 0]
[1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1
 0 0 0 1 0 1 0 0 0 0 1 0 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (20, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.2061071276330682 2.3371422090698415
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.140762343432589 1.85601577457986
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.3877742584507982 1.9813307913459668
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (16, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.3054145672147552 2.6303482364730013
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.140762343432589 1.63250710779059 2.6303482364730013 50
2/2 [==============================] - 0s 4ms/step
[0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1
 0 1 1 0 1 1 0 1 0 0 1 1 1]
[0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1
 0 1 1 0 1 1 0 1 0 0 1 1 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (20, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.0979593431853358 2.3371422090698415
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (5, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.4317408677602317 3.0931516643046404
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (2, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.2922888964496506 1.7954314854184092
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (23, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.1619460607493388 2.5476024569464513
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.0979593431853358 1.5230505912201937 3.0931516643046404 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1
 0 0 1 0 0 1 1 0 0 0 1 1 0]
[0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1
 0 0 1 0 0 1 1 0 0 0 1 1 0]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (14, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.070413197385063 2.3371422090698415
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (1, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.1064552189386372 1.1064552189386372
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (5, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.2526322512051848 1.5352676238385357
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (30, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.2454643911003813 2.384399597317772
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.070413197385063 1.5367761345439406 2.384399597317772 50
2/2 [==============================] - 0s 3ms/step
[1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1 1 0 1 0 0 0
 1 1 0 1 0 0 1 0 0 1 0 0 1]
[1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1 1 0 1 0 0 0
 1 1 0 1 0 0 1 0 0 1 0 0 1]
1.0
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (12, 18)
X_ shape: (2662, 18)
lof_cf min/max: 1.0828928632263504 2.3371422090698415
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (3, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.585789086283601 2.160698123478992
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (9, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.1886281608039073 1.7295452879361635
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (26, 18)
X_ shape: (3098, 18)
lof_cf min/max: 1.161474494950118 2.795620789173778
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
1.0828928632263504 1.6228307793980687 2.795620789173778 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CACTUS (3/5)
********************************************************************************************************************************************************************************************************



Reading data
MOpenAbove15years
0    5387
1    5072
Name: count, dtype: int64
MInFileAbove6years
1    5389
0    5070
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 10000
Positive class: 5000.0
Context 'MOpenAbove15years=1': 4885
Context 'MInFileAbove6years=1': 5198
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:139: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MOpenAbove15years"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:140: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MInFileAbove6years"]))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 dense (Dense)               (None, 64)                1216

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,970
Trainable params: 35,202
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: HELOC_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 18)]         0           []

 model_1 (Functional)           (None, 4)            1796        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 18)           1810        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 3,616
Trainable params: 3,616
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: HELOC_CACTUS
Feature → index:
{'NumSatisfactoryTrades': 0, 'NumTrades60Ever2DerogPubRec': 1, 'NumTrades90Ever2DerogPubRec': 2, 'PercentTradesNeverDelq': 3, 'MSinceMostRecentDelq': 4, 'MaxDelq2PublicRecLast12M': 5, 'MaxDelqEver': 6, 'NumTotalTrades': 7, 'NumTradesOpeninLast12M': 8, 'PercentInstallTrades': 9, 'MSinceMostRecentInqexcl7days': 10, 'NumInqLast6M': 11, 'NetFractionRevolvingBurden': 12, 'NetFractionInstallBurden': 13, 'NumRevolvingTradesWBalance': 14, 'NumInstallTradesWBalance': 15, 'NumBank2NatlTradesWHighUtilization': 16, 'PercentTradesWBalance': 17}

Child → Parents (index form):
{5: [14], 6: [0, 9, 17, 16], 16: [10], 17: [10, 3], 11: [12, 4, 17], 10: [4, 13], 12: [13], 8: [17]}
Building model: CondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 18)                1810

 model (Functional)          (None, 2)                 35970

=================================================================
Total params: 37,780
Trainable params: 0
Non-trainable params: 37,780
_________________________________________________________________
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
2/2 [==============================] - 0s 3ms/step
[0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0
 1 0 0 1 1 0 0 0 0 1 1 0 0]
[0 0 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 0
 0 1 0 1 1 0 0 0 1 0 1 0 1]
0.5
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (16, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9737976505803531 3.803479820949607
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9811705358355796 1.242941309012666
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (2, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.0144120993706225 1.19233053794055
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (25, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9812366875361683 1.4437434025981972
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9737976505803531 1.0217419109554209 3.803479820949607 50
2/2 [==============================] - 0s 3ms/step
[1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1
 0 0 0 1 0 1 0 0 0 0 1 0 0]
[1 1 1 1 0 0 0 0 1 1 0 1 0 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 0 1 1 1 0 0 0 1 0
 0 1 0 1 1 1 0 1 0 0 0 1 0]
0.56
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (20, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9715746956859016 3.803479820949607
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.953736245726414 1.0144727134570515
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (7, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9473628890319504 1.3223630162747257
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (16, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9729044190587542 1.456105500013525
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9473628890319504 1.001965656479646 3.803479820949607 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1
 0 1 1 0 1 1 0 1 0 0 1 1 1]
[1 1 1 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 1 1 1 1 0 1 0
 1 1 0 0 1 0 0 1 1 0 0 1 1]
0.64
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (20, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9566402894108815 3.803479820949607
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (5, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9830834473519888 1.0860841693703411
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (2, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9726998620458567 1.1233441383555294
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (23, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9727004120998369 1.1755504170434867
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9566402894108815 1.017389954707328 3.803479820949607 50
2/2 [==============================] - 0s 3ms/step
[0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1
 0 0 1 0 0 1 1 0 0 0 1 1 0]
[0 1 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 0 0 1 1 1 1 0 1 1
 0 0 1 0 0 1 0 1 1 0 1 1 0]
0.66
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (14, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9627174802633309 3.803479820949607
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (1, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.164044542761781 1.164044542761781
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (5, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9531143971659963 0.9837926905164146
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (30, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9878471424010152 1.3744783231106192
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9531143971659963 1.0268890667846324 3.803479820949607 50
2/2 [==============================] - 0s 3ms/step
[1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1 1 0 1 0 0 0
 1 1 0 1 0 0 1 0 0 1 0 0 1]
[1 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 0 0 1 1 0 0 0 0
 1 1 0 0 1 0 0 0 1 1 0 0 1]
0.72
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (12, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9635529577229839 3.803479820949607
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (3, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.0296861210183474 1.0928884837348263
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (9, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9596377160788463 1.112271778410249
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (26, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9727175413314265 1.2886465730470398
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9596377160788463 1.0068145230089942 3.803479820949607 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate



********************************************************************************************************************************************************************************************************
Running exp: CausalCACTUS (4/5)
********************************************************************************************************************************************************************************************************



Reading data
MOpenAbove15years
0    5387
1    5072
Name: count, dtype: int64
MInFileAbove6years
1    5389
0    5070
Name: count, dtype: int64




----------------------------------------------------------------------------------------------------
---- DATA SUMMARY ----
Total samples: 10000
Positive class: 5000.0
Context 'MOpenAbove15years=1': 4885
Context 'MInFileAbove6years=1': 5198
----------------------------------------------------------------------------------------------------




Building model
Building model: DNN [class]

/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:139: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MOpenAbove15years"]))
/home/zhwang/Projects/CondLatentCF_git/Data/DataReader_HELOC.py:140: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(self.context["MInFileAbove6years"]))

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 main_input (InputLayer)     [(None, 18)]              0

 dense (Dense)               (None, 64)                1216

 batch_normalization (BatchN  (None, 64)               256
 ormalization)

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 128)               8320

 batch_normalization_1 (Batc  (None, 128)              512
 hNormalization)

 dropout_1 (Dropout)         (None, 128)               0

 dense_2 (Dense)             (None, 128)               16512

 batch_normalization_2 (Batc  (None, 128)              512
 hNormalization)

 dropout_2 (Dropout)         (None, 128)               0

 dense_3 (Dense)             (None, 64)                8256

 batch_normalization_3 (Batc  (None, 64)               256
 hNormalization)

 dropout_3 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 2)                 130

=================================================================
Total params: 35,970
Trainable params: 35,202
Non-trainable params: 768
_________________________________________________________________
restoring weights of model DNN: HELOC_class
Building model
Building model: CACTUS_VAE_tabular [gen]

/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer VarianceScaling is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
/home/zhwang/miniconda3/envs/py39/lib/python3.9/site-packages/keras/initializers/initializers_v2.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 main_input (InputLayer)        [(None, 18)]         0           []

 model_1 (Functional)           (None, 4)            1796        ['main_input[0][0]',
                                                                  'main_input[0][0]']

 model_2 (Functional)           (None, 18)           1810        ['model_1[0][0]']

 model_3 (Functional)           (None, 2)            10          ['model_1[1][0]']

==================================================================================================
Total params: 3,616
Trainable params: 3,616
Non-trainable params: 0
__________________________________________________________________________________________________
restoring weights of model CACTUS_VAE_tabular: HELOC_CACTUS
Feature → index:
{'NumSatisfactoryTrades': 0, 'NumTrades60Ever2DerogPubRec': 1, 'NumTrades90Ever2DerogPubRec': 2, 'PercentTradesNeverDelq': 3, 'MSinceMostRecentDelq': 4, 'MaxDelq2PublicRecLast12M': 5, 'MaxDelqEver': 6, 'NumTotalTrades': 7, 'NumTradesOpeninLast12M': 8, 'PercentInstallTrades': 9, 'MSinceMostRecentInqexcl7days': 10, 'NumInqLast6M': 11, 'NetFractionRevolvingBurden': 12, 'NetFractionInstallBurden': 13, 'NumRevolvingTradesWBalance': 14, 'NumInstallTradesWBalance': 15, 'NumBank2NatlTradesWHighUtilization': 16, 'PercentTradesWBalance': 17}

Child → Parents (index form):
{5: [14], 6: [0, 9, 17, 16], 16: [10], 17: [10, 3], 11: [12, 4, 17], 10: [4, 13], 12: [13], 8: [17]}
Building model: CausalCondLatentCF [CF]
Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 z_input (InputLayer)        [(None, 4)]               0

 model_2 (Functional)        (None, 18)                1810

 model (Functional)          (None, 2)                 35970

=================================================================
Total params: 37,780
Trainable params: 0
Non-trainable params: 37,780
_________________________________________________________________
2/2 [==============================] - 0s 3ms/step
[0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0
 1 0 0 1 1 0 0 0 0 1 1 0 0]
[0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0
 1 1 0 1 1 0 0 0 1 1 1 0 1]
0.72
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (16, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9701714666745191 3.753302927545895
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (7, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.004944094163425 1.3243133132800784
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (2, 18)
X_ shape: (766, 18)
lof_cf min/max: 1.0326700057038598 1.1635782145577096
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (25, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.975785537589456 1.3762496349712074
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9701714666745191 1.047378727293812 3.753302927545895 50
2/2 [==============================] - 0s 3ms/step
[0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1
 0 1 1 0 1 1 0 1 0 0 1 1 1]
[0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0
 0 1 1 0 1 1 0 1 1 0 0 1 1]
0.86
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (20, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9708902918387201 3.753302927545895
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (5, 18)
X_ shape: (1021, 18)
lof_cf min/max: 0.9804627102799409 1.1243931683901291
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (2, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9879526288232298 1.1856960262138163
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (23, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9823442162833719 1.1480071378672427
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9708902918387201 1.0129432200109938 3.753302927545895 50
2/2 [==============================] - 0s 2ms/step
[0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1
 0 0 1 0 0 1 1 0 0 0 1 1 0]
[0 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 1 1
 0 0 1 0 0 1 1 1 1 0 1 1 0]
0.82
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (14, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9604682190570384 3.753302927545895
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (1, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.1343173825872794 1.1343173825872794
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (5, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9590356361236063 1.0579992055181997
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (30, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9898043403758615 1.2503076370358046
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9590356361236063 1.031725983848052 3.753302927545895 50
2/2 [==============================] - 0s 3ms/step
[1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1 1 0 1 0 0 0
 1 1 0 1 0 0 1 0 0 1 0 0 1]
[1 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 1 0 1 1 1 0 0 0
 1 1 0 0 1 0 1 0 0 1 0 0 1]
0.82
---- DEBUG Context-LOF score ----
Context: [0, 0]
Subset size: 3114
Unique rows: 2662
After np.unique(): subset size: 2662
cf_samples_ shape: (12, 18)
X_ shape: (2662, 18)
lof_cf min/max: 0.9556904279967996 3.753302927545895
lof_train min/max: 0.9572709929810846 4.949122384816732
mean train LOF: 1.1170444594235096
---- DEBUG Context-LOF score ----
Context: [0, 1]
Subset size: 1021
Unique rows: 1021
After np.unique(): subset size: 1021
cf_samples_ shape: (3, 18)
X_ shape: (1021, 18)
lof_cf min/max: 1.018370278602961 1.083447997469441
lof_train min/max: 0.9578591868059378 1.7940915147540137
mean train LOF: 1.108941553229546
---- DEBUG Context-LOF score ----
Context: [1, 0]
Subset size: 766
Unique rows: 766
After np.unique(): subset size: 766
cf_samples_ shape: (9, 18)
X_ shape: (766, 18)
lof_cf min/max: 0.9666343174680315 1.139183268947121
lof_train min/max: 0.9532369091095589 4.087661686056783
mean train LOF: 1.1163485422841601
---- DEBUG Context-LOF score ----
Context: [1, 1]
Subset size: 3099
Unique rows: 3098
After np.unique(): subset size: 3098
cf_samples_ shape: (26, 18)
X_ shape: (3098, 18)
lof_cf min/max: 0.9727175413314265 1.3231833517865086
lof_train min/max: 0.955518800353902 2.142231804068363
mean train LOF: 1.1133768055811497
0.9556904279967996 1.0110880446322696 3.753302927545895 50
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.iter
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_1
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.beta_2
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.decay
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer.learning_rate
            Model Dataset      CFMethod                Metric  Value
0      LatentCF++   HELOC    LatentCFpp             proximity  1.556
1      LatentCF++   HELOC    LatentCFpp           n_proximity  0.367
2      LatentCF++   HELOC    LatentCFpp              validity  1.000
3      LatentCF++   HELOC    LatentCFpp           compactness  0.048
4      LatentCF++   HELOC    LatentCFpp           lof_context  1.345
..            ...     ...           ...                   ...    ...
220  CausalCACTUS   HELOC  CausalCACTUS           lof_context  1.193
221  CausalCACTUS   HELOC  CausalCACTUS  causal_validity_hard  0.880
222  CausalCACTUS   HELOC  CausalCACTUS  causal_validity_soft  0.985
223  CausalCACTUS   HELOC  CausalCACTUS    causal_compact_val  0.309
224  CausalCACTUS   HELOC  CausalCACTUS       inlier_fraction  0.938

[225 rows x 5 columns]

In [14]:
child_to_parents_dict

{5: [14],
 6: [0, 9, 17, 16],
 16: [10],
 17: [10, 3],
 11: [12, 4, 17],
 10: [4, 13],
 12: [13],
 8: [17]}

In [15]:
df_metrics

            Model Dataset      CFMethod                Metric  Value
0      LatentCF++   HELOC    LatentCFpp             proximity  1.556
1      LatentCF++   HELOC    LatentCFpp           n_proximity  0.367
2      LatentCF++   HELOC    LatentCFpp              validity  1.000
3      LatentCF++   HELOC    LatentCFpp           compactness  0.048
4      LatentCF++   HELOC    LatentCFpp           lof_context  1.345
..            ...     ...           ...                   ...    ...
220  CausalCACTUS   HELOC  CausalCACTUS           lof_context  1.193
221  CausalCACTUS   HELOC  CausalCACTUS  causal_validity_hard  0.880
222  CausalCACTUS   HELOC  CausalCACTUS  causal_validity_soft  0.985
223  CausalCACTUS   HELOC  CausalCACTUS    causal_compact_val  0.309
224  CausalCACTUS   HELOC  CausalCACTUS       inlier_fraction  0.938

[225 rows x 5 columns]

In [16]:
# Pivoting the dataframe
df_metrics_pivot = df_metrics.pivot_table(
    index=["Dataset", "Model"],
    columns="Metric",
    values="Value",
    aggfunc=['mean', 'std']
)

desired_order = [
    "validity",
    "lof_context",
    "compactness",
    "n_proximity",
    "causal_validity_hard",
    "causal_validity_soft",
    "causal_compact_val",
    "inlier_fraction"
]
df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)
df_metrics_pivot = df_metrics_pivot[desired_order]

df_metrics_pivot.rename(
    columns={
        "validity": "Validity",
        "lof_context": "LOF",
        "compactness": "Compactness",
        "n_proximity": "Proximity",
        "causal_validity_hard": "Causal Validity (Hard)",
        "causal_validity_soft": "Causal Validity (Soft)",
        "causal_compact_val": "Causal Compact Validity",
        "inlier_fraction": "inlier_fraction"
    },
    inplace=True
)

df_metrics_pivot.columns = df_metrics_pivot.columns.swaplevel(0, 1)

# df_formatted = df_metrics_pivot.apply(
#     lambda x: x["mean"].map("${:2.2f}".format)
#     + " \\pm "
#     + x["std"].map("{:2.2f} $".format),
#     axis=1
# )
# df_formatted

df_formatted = df_metrics_pivot.apply(
    lambda x: (
        x["mean"].round(2).astype(str)
        + " ± "
        + x["std"].round(2).astype(str)
    ),
    axis=1
)
df_formatted

Metric                   Validity          LOF  Compactness    Proximity  \
Dataset Model
HELOC   CACTUS        0.62 ± 0.09  1.17 ± 0.07  0.07 ± 0.02   0.5 ± 0.02
        CausalCACTUS   0.8 ± 0.06  1.18 ± 0.07  0.23 ± 0.06   0.4 ± 0.04
        LatentCF++      1.0 ± 0.0  1.28 ± 0.06  0.04 ± 0.01  0.44 ± 0.06
        Prototype C     1.0 ± 0.0  2.37 ± 0.05  0.05 ± 0.01  1.29 ± 0.05
        Prototype D     1.0 ± 0.0  1.65 ± 0.03  0.03 ± 0.01  1.11 ± 0.03

Metric               Causal Validity (Hard) Causal Validity (Soft)  \
Dataset Model
HELOC   CACTUS                  0.81 ± 0.02             0.98 ± 0.0
        CausalCACTUS            0.84 ± 0.06            0.98 ± 0.01
        LatentCF++              0.75 ± 0.06            0.97 ± 0.01
        Prototype C             0.72 ± 0.05            0.96 ± 0.01
        Prototype D               0.8 ± 0.1            0.97 ± 0.01

Metric               Causal Compact Validity inlier_fraction
Dataset Model
HELOC   CACTUS                   0.21 ± 0.02     0.96 ± 0.02
        CausalCACTUS             0.34 ± 0.05     0.96 ± 0.02
        LatentCF++               0.18 ± 0.02     0.88 ± 0.06
        Prototype C              0.09 ± 0.01     0.12 ± 0.06
        Prototype D              0.07 ± 0.01     0.42 ± 0.15